#!/usr/bin/env python3
"""Generate first-party Go bindings from Mango OpenAPI using Python's stdlib.

This generates transport types, not a JSON Schema validator. The server remains
the authority for constraints (patterns, limits, cross-field invariants). Unknown
schema shapes fail generation; explicitly unconstrained and negation-only legacy
values are retained as json.RawMessage rather than inventing a wire shape.
"""

import argparse
import json
from pathlib import Path
import re
import subprocess
import sys

HERE = Path(__file__).resolve().parent
SPEC = json.loads((HERE.parent / "openapi.json").read_text())
SCHEMAS = SPEC["components"]["schemas"]
DEFINITIONS = {}
HEADER = "// Code generated by python3 sdk/go/generate.py; DO NOT EDIT.\n\npackage mango\n\n"


def ident(value):
    words = re.findall(r"[A-Za-z0-9]+", value)
    initialisms = {"id": "ID", "ids": "IDs", "url": "URL", "uri": "URI", "api": "API", "mcp": "MCP", "http": "HTTP", "sha256": "SHA256", "oauth": "OAuth", "ttl": "TTL"}
    result = "".join(initialisms.get(word.lower(), word[0].upper() + word[1:]) for word in words)
    if not result:
        raise ValueError(f"cannot name {value!r}")
    if result[0].isdigit():
        result = "Value" + result
    return result


def resolve(schema):
    while "$ref" in schema:
        reference = schema["$ref"]
        if not reference.startswith("#/components/"):
            raise ValueError(f"external reference unsupported: {reference}")
        value = SPEC
        for part in reference[2:].split("/"):
            value = value[part]
        schema = value
    return schema


def flatten(schema):
    schema = resolve(schema)
    if "allOf" not in schema:
        return schema
    result = {"type": "object", "properties": {}, "required": []}
    for part in schema["allOf"]:
        part = flatten(part)
        if part.get("type", "object") != "object":
            raise ValueError("only object allOf compositions are supported")
        result["properties"].update(part.get("properties", {}))
        result["required"].extend(part.get("required", []))
        if "additionalProperties" in part:
            result["additionalProperties"] = part["additionalProperties"]
    result["properties"].update(schema.get("properties", {}))
    result["required"].extend(schema.get("required", []))
    result["required"] = list(dict.fromkeys(result["required"]))
    return result


def without_null(schema):
    types = schema.get("type")
    if isinstance(types, list):
        non_null = [value for value in types if value != "null"]
        if len(non_null) != 1 or "null" not in types:
            raise ValueError(f"unsupported type list {types}")
        result = dict(schema, type=non_null[0])
        return result
    variants = schema.get("oneOf", schema.get("anyOf"))
    if variants and any(resolve(value).get("type") == "null" for value in variants):
        non_null = [value for value in variants if resolve(value).get("type") != "null"]
        if len(non_null) == 1:
            return non_null[0]
    return None


def expression(schema, hint):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    schema = flatten(schema)
    non_null = without_null(schema)
    if non_null is not None:
        return "*" + expression(non_null, hint + "Value")
    if "oneOf" in schema or "anyOf" in schema:
        emit_type(hint, schema)
        return hint
    kind = schema.get("type")
    if kind == "object":
        if schema.get("properties"):
            emit_type(hint, schema)
            return hint
        additional = schema.get("additionalProperties", True)
        if isinstance(additional, dict):
            return "map[string]" + expression(additional, hint + "Value")
        return "map[string]json.RawMessage"
    if kind == "array":
        if "items" not in schema:
            raise ValueError(f"array has no items: {hint}")
        return "[]" + expression(schema["items"], hint + "Item")
    if kind == "string":
        return "Upload" if schema.get("format") == "binary" else "string"
    if kind == "integer":
        return "int64"
    if kind == "number":
        return "float64"
    if kind == "boolean":
        return "bool"
    if kind == "null":
        return "json.RawMessage"
    if not kind and ("not" in schema or not set(schema) - {"description", "title"}):
        return "json.RawMessage"
    raise ValueError(f"unsupported schema at {hint}: {schema}")


def match_shape(schema):
    schema = flatten(schema)
    kind = schema.get("type", "")
    if isinstance(kind, list):
        kind = next(value for value in kind if value != "null")
    if kind == "integer":
        kind = "number"
    constants = {}
    for name, value in schema.get("properties", {}).items():
        value = resolve(value)
        if "const" in value:
            constants[name] = json.dumps(value["const"], separators=(",", ":"))
    return kind, schema.get("required", []), constants


def match_shapes(schema):
    schema = flatten(schema)
    variants = schema.get("oneOf", schema.get("anyOf"))
    if variants:
        return [shape for variant in variants for shape in match_shapes(variant)]
    return [match_shape(schema)]


def emit_type(name, schema):
    if name in DEFINITIONS:
        return
    DEFINITIONS[name] = ""  # Reserve before recursively generating fields.
    schema = flatten(schema)
    non_null = without_null(schema)
    if non_null is not None:
        DEFINITIONS[name] = f"type {name} = *{expression(non_null, name + 'Value')}\n"
        return
    variants = schema.get("oneOf", schema.get("anyOf"))
    if variants:
        fields, choices, args = [], [], []
        used = set()
        for index, variant in enumerate(variants):
            if "$ref" in variant:
                field = variant["$ref"].split("/")[-1]
            else:
                raw = flatten(variant)
                discriminator = raw.get("properties", {}).get("type", {}).get("const")
                field = ident(str(discriminator)) if discriminator else ident(str(raw.get("type", f"variant{index + 1}")))
            if field in used:
                field += str(index + 1)
            used.add(field)
            typ = expression(variant, name + field)
            fields.append(f"\t{field} *{typ} `json:\"-\"`\n")
            args.append("value." + field)
            # Nested unions must match their concrete alternatives. Treating a
            # nested SessionEvent as an unconstrained value would swallow SSE
            # EventStart/EventDelta siblings into its unknown-variant fallback.
            for kind, required, constants in match_shapes(variant):
                required_go = "[]string{" + ", ".join(json.dumps(x) for x in required) + "}"
                constants_go = "map[string]string{" + ", ".join(json.dumps(k) + ": " + json.dumps(v) for k, v in sorted(constants.items())) + "}"
                choices.append(f"\t\tunionChoice{{target: &value.{field}, kind: {json.dumps(kind)}, required: {required_go}, constants: {constants_go}}},\n")
        DEFINITIONS[name] = (
            f"// {name} is a wire union. Set exactly one variant when constructing it.\n"
            f"// Raw preserves an unknown variant received from the server.\n"
            f"type {name} struct {{\n\tRaw json.RawMessage `json:\"-\"`\n" + "".join(fields) + "}\n"
            f"func (value {name}) MarshalJSON() ([]byte, error) {{ return marshalUnion(value.Raw, {', '.join(args)}) }}\n"
            f"func (value *{name}) UnmarshalJSON(data []byte) error {{\n\t*value = {name}{{}}\n"
            "\treturn unmarshalUnion(data, &value.Raw,\n" + "".join(choices) + "\t)\n}\n"
        )
        return
    if schema.get("type") == "object" and schema.get("properties"):
        required = schema.get("required", [])
        fields = []
        property_names = []
        for key, value in sorted(schema["properties"].items()):
            property_names.append(key)
            typ = expression(value, name + ident(key))
            if key not in required:
                typ = f"Optional[{typ}]"
                tag = key + ",omitzero"
            else:
                tag = key
            field_name = ident(key)
            fields.append(f"\t{field_name} {typ} `json:{json.dumps(tag)}`\n")
        extra = schema.get("additionalProperties") is True
        if extra:
            fields.append('\tAdditionalProperties map[string]json.RawMessage `json:"-"`\n')
        definition = f"type {name} struct {{\n" + "".join(fields) + "}\n"
        if extra:
            known = ", ".join(json.dumps(key) for key in property_names)
            definition += (
                f"func (value {name}) MarshalJSON() ([]byte, error) {{\n"
                f"\ttype plain {name}\n\treturn marshalExtendedObject(plain(value), value.AdditionalProperties)\n}}\n"
                f"func (value *{name}) UnmarshalJSON(data []byte) error {{\n"
                f"\ttype plain {name}\n\treturn unmarshalExtendedObject(data, (*plain)(value), &value.AdditionalProperties, []string{{{known}}})\n}}\n"
            )
        DEFINITIONS[name] = definition
        return
    typ = expression(schema, name + "Value")
    definition = f"type {name} {typ}\n"
    if schema.get("enum") and schema.get("type") == "string":
        definition += "const (\n"
        for value in schema["enum"]:
            definition += f"\t{name}{ident(value)} {name} = {json.dumps(value)}\n"
        definition += ")\n"
    DEFINITIONS[name] = definition


def operations():
    result = []
    for path, item in SPEC["paths"].items():
        for method, operation in item.items():
            if method not in {"get", "post", "put", "patch", "delete", "head", "options"}:
                continue
            parameters = [resolve(value) for value in item.get("parameters", []) + operation.get("parameters", [])]
            request = resolve(operation.get("requestBody", {}))
            request_content = request.get("content", {})
            if len(request_content) > 1:
                raise ValueError(f"multiple request media types: {operation['operationId']}")
            request_type = next(iter(request_content), "")
            response_codes = sorted(key for key in operation["responses"] if str(key).startswith("2"))
            if not response_codes:
                raise ValueError("operation has no success response")
            response = resolve(operation["responses"][response_codes[0]])
            response_content = response.get("content", {})
            if len(response_content) > 1:
                raise ValueError(f"multiple response media types: {operation['operationId']}")
            response_type = next(iter(response_content), "")
            result.append(dict(id=operation["operationId"], method=method.upper(), path=path, summary=operation.get("summary", ""), parameters=parameters,
                request_type=request_type, request_schema=request_content.get(request_type, {}).get("schema"), request_required=request.get("required", False),
                response_type=response_type, response_schema=response_content.get(response_type, {}).get("schema"), public=operation.get("security", SPEC.get("security")) == []))
    return sorted(result, key=lambda op: op["id"])


def emit_operation(op):
    name = op["id"][0].upper() + op["id"][1:]
    paths = [value for value in op["parameters"] if value["in"] == "path"]
    queries = [value for value in op["parameters"] if value["in"] == "query"]
    if len(paths) + len(queries) != len(op["parameters"]):
        raise ValueError(f"unsupported parameter location in {name}")
    args = ["ctx context.Context"]
    invocation = ["ctx"]
    for parameter in paths:
        if resolve(parameter["schema"]).get("type") != "string":
            raise ValueError("non-string path parameter")
        variable = parameter["name"]
        args.append(variable + " string")
        invocation.append(variable)
    query_lines = []
    if queries:
        emit_type(name + "Params", {"type": "object", "properties": {p["name"]: p["schema"] for p in queries}, "required": [p["name"] for p in queries if p.get("required")]})
        args.append(f"params {name}Params")
        invocation.append("params")
        for parameter in queries:
            if parameter.get("required"):
                raise ValueError("required query parameter needs explicit generator support")
            helper = "addQueryArray" if resolve(parameter["schema"]).get("type") == "array" else "addQuery"
            query_lines.append(f"\t{helper}(query, {json.dumps(parameter['name'])}, params.{ident(parameter['name'])})\n")
    if op["request_schema"] is not None:
        request_type = expression(op["request_schema"], name + "Request")
        if not op["request_required"]:
            request_type = "*" + request_type
        args.append("body " + request_type)
    if op["response_type"] == "application/json":
        result_type = expression(op["response_schema"], name + "Response")
    elif op["response_type"] == "text/event-stream":
        result_type = "*EventStream"
    elif op["response_type"]:
        result_type = "*Download"
    else:
        result_type = ""
    result = f"({result_type}, error)" if result_type else "error"
    expression_path = json.dumps(op["path"])
    for parameter in paths:
        expression_path = expression_path.replace("{" + parameter["name"] + "}", '" + escapePath(' + parameter["name"] + ') + "')
    auth = str(not op["public"]).lower()
    prefix = f"// {name} {op['summary'].rstrip('.')} ({op['method']} {op['path']}).\n"
    code = prefix + f"func (c *Client) {name}({', '.join(args)}) {result} {{\n"
    code += "\tquery := make(url.Values)\n" + "".join(query_lines)
    code += f"\tpath := {expression_path}\n"
    call_args = f"ctx, {json.dumps(op['method'])}, path, query"
    if result_type == "*EventStream":
        code += f"\treturn c.stream({call_args}, {auth})\n"
    elif result_type == "*Download":
        code += f"\treturn c.download({call_args}, {json.dumps(op['response_type'])}, {auth})\n"
    elif op["request_type"] == "multipart/form-data":
        code += f"\tvar result {result_type}\n\tvar parts []multipartPart\n"
        request = flatten(op["request_schema"])
        for field, schema in sorted(request["properties"].items()):
            value = "body." + ident(field)
            if schema.get("type") == "array" and schema.get("items", {}).get("format") == "binary":
                code += f"\tfor i := range {value} {{ parts = append(parts, multipartPart{{name: {json.dumps(field)}, upload: &{value}[i]}}) }}\n"
            elif schema.get("format") == "binary":
                code += f"\tparts = append(parts, multipartPart{{name: {json.dumps(field)}, upload: &{value}}})\n"
            elif schema.get("type") == "string" and field not in request.get("required", []):
                code += f"\tif value, ok := {value}.Get(); ok {{ parts = append(parts, multipartPart{{name: {json.dumps(field)}, value: value}}) }}\n"
            else:
                raise ValueError("unsupported multipart property")
        code += f"\terr := c.doMultipart({call_args}, parts, &result, {auth})\n\treturn result, err\n"
    else:
        body = "body" if op["request_schema"] is not None else "nil"
        if result_type:
            code += f"\tvar result {result_type}\n\terr := c.doJSON({call_args}, {body}, &result, {auth})\n\treturn result, err\n"
        else:
            code += f"\treturn c.doJSON({call_args}, {body}, nil, {auth})\n"
    code += "}\n\n"
    if op["response_type"] == "application/json":
        response = flatten(op["response_schema"])
        fields = response.get("properties", {})
        query_names = {q["name"] for q in queries}
        if "data" in fields and "next_page" in fields and "page" in query_names:
            item = expression(fields["data"]["items"], name + "PageItem")
            code += f"// {name}AutoPaging iterates every result, preserving the initial filters.\n"
            code += f"func (c *Client) {name}AutoPaging({', '.join(args)}) *PageIterator[{item}] {{\n"
            code += "\tfirst, _ := params.Page.Get()\n"
            code += f"\treturn NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[{item}], error) {{\n"
            code += '\t\tif cursor != "" { params.Page = Some(cursor) }\n'
            code += f"\t\tresult, err := c.{name}({', '.join(invocation)})\n"
            code += f"\t\tif err != nil {{ return Page[{item}]{{}}, err }}\n\t\tnext := \"\"\n\t\tif result.NextPage != nil {{ next = *result.NextPage }}\n"
            code += f"\t\treturn Page[{item}]{{Data: result.Data, Next: next}}, nil\n\t}})\n}}\n\n"
        elif "data" in fields and "has_more" in fields and "after_id" in query_names:
            item = expression(fields["data"]["items"], name + "PageItem")
            code += f"// {name}AutoPaging follows Files cursors, preserving before_id direction.\n"
            code += f"func (c *Client) {name}AutoPaging({', '.join(args)}) *PageIterator[{item}] {{\n"
            code += "\tfirst, _ := params.AfterID.Get()\n\tbefore, reverse := params.BeforeID.Get()\n\tif reverse { first = before }\n"
            code += f"\treturn NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[{item}], error) {{\n"
            code += '\t\tif cursor != "" { if reverse { params.BeforeID = Some(cursor) } else { params.AfterID = Some(cursor) } }\n'
            code += f"\t\tresult, err := c.{name}({', '.join(invocation)})\n"
            code += f"\t\tif err != nil {{ return Page[{item}]{{}}, err }}\n\t\tnext := \"\"\n"
            code += "\t\tif result.HasMore {\n\t\t\tid := result.LastID\n\t\t\tif reverse { id = result.FirstID }\n"
            code += f"\t\t\tif id == nil || *id == \"\" {{ return Page[{item}]{{}}, errors.New(\"mango: Files has_more without a cursor\") }}\n\t\t\tnext = *id\n\t\t}}\n"
            code += f"\t\treturn Page[{item}]{{Data: result.Data, Next: next}}, nil\n\t}})\n}}\n\n"
    return code


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed source differs")
    args = parser.parse_args()
    for name, schema in sorted(SCHEMAS.items()):
        emit_type(name, schema)
    ops = operations()
    methods = "".join(emit_operation(operation) for operation in ops)
    metadata = "// Operation describes one supported OpenAPI operation.\ntype Operation struct { ID, Method, Path string }\n\n"
    metadata += "// Operations contains every public operation in the checked-in OpenAPI document.\nvar Operations = []Operation{\n"
    metadata += "".join("\t{" + ", ".join(json.dumps(operation[key]) for key in ["id", "method", "path"]) + "},\n" for operation in ops) + "}\n"
    files = {
        "types_generated.go": HEADER + 'import "encoding/json"\n\n' + "\n".join(DEFINITIONS[name] for name in sorted(DEFINITIONS)),
        "operations_generated.go": HEADER + 'import ("context"; "errors"; "net/url")\n\n' + metadata + "\n" + methods,
    }
    stale = []
    for name, source in files.items():
        formatted = subprocess.run(["gofmt"], input=source, text=True, capture_output=True, check=True).stdout
        destination = HERE / name
        if args.check:
            if not destination.exists() or destination.read_text() != formatted:
                stale.append(name)
        else:
            destination.write_text(formatted)
    if stale:
        sys.exit("Go SDK generated source is stale: " + ", ".join(stale))
    print(f"Go SDK: {len(ops)} operations, {len(DEFINITIONS)} types {'checked' if args.check else 'generated'}")


if __name__ == "__main__":
    main()
