// Code generated by python3 sdk/go/generate.py; DO NOT EDIT.

package mango

import (
	"context"
	"errors"
	"net/url"
)

// Operation describes one supported OpenAPI operation.
type Operation struct{ ID, Method, Path, Resource, Name string }

// Operations contains every public operation in the checked-in OpenAPI document.
var Operations = []Operation{
	{"acknowledgeEnvironmentWork", "POST", "/v1/environments/{environment_id}/work/{work_id}/ack", "Environments.Work", "Ack"},
	{"archiveAgent", "POST", "/v1/agents/{agent_id}/archive", "Agents", "Archive"},
	{"archiveDeployment", "POST", "/v1/deployments/{deployment_id}/archive", "Deployments", "Archive"},
	{"archiveEnvironment", "POST", "/v1/environments/{environment_id}/archive", "Environments", "Archive"},
	{"archiveMemoryStore", "POST", "/v1/memory_stores/{store_id}/archive", "MemoryStores", "Archive"},
	{"archiveSession", "POST", "/v1/sessions/{session_id}/archive", "Sessions", "Archive"},
	{"archiveSessionThread", "POST", "/v1/sessions/{session_id}/threads/{thread_id}/archive", "Sessions.Threads", "Archive"},
	{"archiveVault", "POST", "/v1/vaults/{vault_id}/archive", "Vaults", "Archive"},
	{"archiveVaultCredential", "POST", "/v1/vaults/{vault_id}/credentials/{credential_id}/archive", "Vaults.Credentials", "Archive"},
	{"createAgent", "POST", "/v1/agents", "Agents", "New"},
	{"createDeployment", "POST", "/v1/deployments", "Deployments", "New"},
	{"createEnvironment", "POST", "/v1/environments", "Environments", "New"},
	{"createMemory", "POST", "/v1/memory_stores/{store_id}/memories", "MemoryStores.Memories", "New"},
	{"createMemoryStore", "POST", "/v1/memory_stores", "MemoryStores", "New"},
	{"createSession", "POST", "/v1/sessions", "Sessions", "New"},
	{"createSkill", "POST", "/v1/skills", "Skills", "New"},
	{"createSkillVersion", "POST", "/v1/skills/{skill_id}/versions", "Skills.Versions", "New"},
	{"createVault", "POST", "/v1/vaults", "Vaults", "New"},
	{"createVaultCredential", "POST", "/v1/vaults/{vault_id}/credentials", "Vaults.Credentials", "New"},
	{"createWebhook", "POST", "/v1/webhooks", "Webhooks", "New"},
	{"deleteEnvironment", "DELETE", "/v1/environments/{environment_id}", "Environments", "Delete"},
	{"deleteFile", "DELETE", "/v1/files/{file_id}", "Files", "Delete"},
	{"deleteMemory", "DELETE", "/v1/memory_stores/{store_id}/memories/{memory_id}", "MemoryStores.Memories", "Delete"},
	{"deleteMemoryStore", "DELETE", "/v1/memory_stores/{store_id}", "MemoryStores", "Delete"},
	{"deleteSession", "DELETE", "/v1/sessions/{session_id}", "Sessions", "Delete"},
	{"deleteSkill", "DELETE", "/v1/skills/{skill_id}", "Skills", "Delete"},
	{"deleteSkillVersion", "DELETE", "/v1/skills/{skill_id}/versions/{version}", "Skills.Versions", "Delete"},
	{"deleteVault", "DELETE", "/v1/vaults/{vault_id}", "Vaults", "Delete"},
	{"deleteVaultCredential", "DELETE", "/v1/vaults/{vault_id}/credentials/{credential_id}", "Vaults.Credentials", "Delete"},
	{"deleteWebhook", "DELETE", "/v1/webhooks/{webhook_id}", "Webhooks", "Delete"},
	{"downloadFile", "GET", "/v1/files/{file_id}/content", "Files", "Download"},
	{"downloadSkillVersion", "GET", "/v1/skills/{skill_id}/versions/{version}/content", "Skills.Versions", "Download"},
	{"failEnvironmentWork", "POST", "/v1/environments/{environment_id}/work/{work_id}/fail", "Environments.Work", "Fail"},
	{"getAgent", "GET", "/v1/agents/{agent_id}", "Agents", "Get"},
	{"getDeployment", "GET", "/v1/deployments/{deployment_id}", "Deployments", "Get"},
	{"getDeploymentRun", "GET", "/v1/deployment_runs/{deployment_run_id}", "DeploymentRuns", "Get"},
	{"getEnvironment", "GET", "/v1/environments/{environment_id}", "Environments", "Get"},
	{"getEnvironmentWork", "GET", "/v1/environments/{environment_id}/work/{work_id}", "Environments.Work", "Get"},
	{"getEnvironmentWorkStats", "GET", "/v1/environments/{environment_id}/work/stats", "Environments.Work", "Stats"},
	{"getFileMetadata", "GET", "/v1/files/{file_id}", "Files", "Get"},
	{"getMemory", "GET", "/v1/memory_stores/{store_id}/memories/{memory_id}", "MemoryStores.Memories", "Get"},
	{"getMemoryStore", "GET", "/v1/memory_stores/{store_id}", "MemoryStores", "Get"},
	{"getMemoryVersion", "GET", "/v1/memory_stores/{store_id}/memory_versions/{version_id}", "MemoryStores.Versions", "Get"},
	{"getSession", "GET", "/v1/sessions/{session_id}", "Sessions", "Get"},
	{"getSessionThread", "GET", "/v1/sessions/{session_id}/threads/{thread_id}", "Sessions.Threads", "Get"},
	{"getSkill", "GET", "/v1/skills/{skill_id}", "Skills", "Get"},
	{"getSkillVersion", "GET", "/v1/skills/{skill_id}/versions/{version}", "Skills.Versions", "Get"},
	{"getVault", "GET", "/v1/vaults/{vault_id}", "Vaults", "Get"},
	{"getVaultCredential", "GET", "/v1/vaults/{vault_id}/credentials/{credential_id}", "Vaults.Credentials", "Get"},
	{"getWebhook", "GET", "/v1/webhooks/{webhook_id}", "Webhooks", "Get"},
	{"health", "GET", "/healthz", "System", "Health"},
	{"heartbeatEnvironmentWork", "POST", "/v1/environments/{environment_id}/work/{work_id}/heartbeat", "Environments.Work", "Heartbeat"},
	{"listAgentVersions", "GET", "/v1/agents/{agent_id}/versions", "Agents.Versions", "List"},
	{"listAgents", "GET", "/v1/agents", "Agents", "List"},
	{"listDeploymentRuns", "GET", "/v1/deployment_runs", "DeploymentRuns", "List"},
	{"listDeployments", "GET", "/v1/deployments", "Deployments", "List"},
	{"listEnvironmentWork", "GET", "/v1/environments/{environment_id}/work", "Environments.Work", "List"},
	{"listEnvironments", "GET", "/v1/environments", "Environments", "List"},
	{"listFiles", "GET", "/v1/files", "Files", "List"},
	{"listMemories", "GET", "/v1/memory_stores/{store_id}/memories", "MemoryStores.Memories", "List"},
	{"listMemoryStores", "GET", "/v1/memory_stores", "MemoryStores", "List"},
	{"listMemoryVersions", "GET", "/v1/memory_stores/{store_id}/memory_versions", "MemoryStores.Versions", "List"},
	{"listSessionEvents", "GET", "/v1/sessions/{session_id}/events", "Sessions.Events", "List"},
	{"listSessionThreadEvents", "GET", "/v1/sessions/{session_id}/threads/{thread_id}/events", "Sessions.Threads.Events", "List"},
	{"listSessionThreads", "GET", "/v1/sessions/{session_id}/threads", "Sessions.Threads", "List"},
	{"listSessions", "GET", "/v1/sessions", "Sessions", "List"},
	{"listSkillVersions", "GET", "/v1/skills/{skill_id}/versions", "Skills.Versions", "List"},
	{"listSkills", "GET", "/v1/skills", "Skills", "List"},
	{"listVaultCredentials", "GET", "/v1/vaults/{vault_id}/credentials", "Vaults.Credentials", "List"},
	{"listVaults", "GET", "/v1/vaults", "Vaults", "List"},
	{"listWebhooks", "GET", "/v1/webhooks", "Webhooks", "List"},
	{"openAPI", "GET", "/openapi.yaml", "System", "OpenAPI"},
	{"pauseDeployment", "POST", "/v1/deployments/{deployment_id}/pause", "Deployments", "Pause"},
	{"pollEnvironmentWork", "GET", "/v1/environments/{environment_id}/work/poll", "Environments.Work", "Poll"},
	{"readiness", "GET", "/readyz", "System", "Readiness"},
	{"redactMemoryVersion", "POST", "/v1/memory_stores/{store_id}/memory_versions/{version_id}/redact", "MemoryStores.Versions", "Redact"},
	{"regenerateWebhookSigningSecret", "POST", "/v1/webhooks/{webhook_id}/regenerate_signing_secret", "Webhooks", "RegenerateSigningSecret"},
	{"runDeployment", "POST", "/v1/deployments/{deployment_id}/run", "Deployments", "Run"},
	{"sendSessionEvents", "POST", "/v1/sessions/{session_id}/events", "Sessions.Events", "Send"},
	{"stopEnvironmentWork", "POST", "/v1/environments/{environment_id}/work/{work_id}/stop", "Environments.Work", "Stop"},
	{"streamSessionEvents", "GET", "/v1/sessions/{session_id}/events/stream", "Sessions.Events", "Stream"},
	{"streamSessionThreadEvents", "GET", "/v1/sessions/{session_id}/threads/{thread_id}/stream", "Sessions.Threads.Events", "Stream"},
	{"unpauseDeployment", "POST", "/v1/deployments/{deployment_id}/unpause", "Deployments", "Unpause"},
	{"updateAgent", "POST", "/v1/agents/{agent_id}", "Agents", "Update"},
	{"updateDeployment", "POST", "/v1/deployments/{deployment_id}", "Deployments", "Update"},
	{"updateEnvironment", "POST", "/v1/environments/{environment_id}", "Environments", "Update"},
	{"updateEnvironmentWork", "POST", "/v1/environments/{environment_id}/work/{work_id}", "Environments.Work", "Update"},
	{"updateMemory", "POST", "/v1/memory_stores/{store_id}/memories/{memory_id}", "MemoryStores.Memories", "Update"},
	{"updateMemoryStore", "POST", "/v1/memory_stores/{store_id}", "MemoryStores", "Update"},
	{"updateSession", "POST", "/v1/sessions/{session_id}", "Sessions", "Update"},
	{"updateVault", "POST", "/v1/vaults/{vault_id}", "Vaults", "Update"},
	{"updateVaultCredential", "POST", "/v1/vaults/{vault_id}/credentials/{credential_id}", "Vaults.Credentials", "Update"},
	{"updateWebhook", "POST", "/v1/webhooks/{webhook_id}", "Webhooks", "Update"},
	{"uploadFile", "POST", "/v1/files", "Files", "Upload"},
	{"validateVaultCredentialMCPOAuth", "POST", "/v1/vaults/{vault_id}/credentials/{credential_id}/mcp_oauth_validate", "Vaults.Credentials", "ValidateMCPOAuth"},
}

// Ack Acknowledge a polled Work item and transition it to starting (POST /v1/environments/{environment_id}/work/{work_id}/ack).
func (c *EnvironmentsWorkService) Ack(ctx context.Context, environment_id string, work_id string) (EnvironmentWork, error) {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + "/work/" + escapePath(work_id) + "/ack"
	var result EnvironmentWork
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Archive Archive an Agent (POST /v1/agents/{agent_id}/archive).
func (c *AgentsService) Archive(ctx context.Context, agent_id string) (Agent, error) {
	query := make(url.Values)
	path := "/v1/agents/" + escapePath(agent_id) + "/archive"
	var result Agent
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Archive Archive a Deployment (POST /v1/deployments/{deployment_id}/archive).
func (c *DeploymentsService) Archive(ctx context.Context, deployment_id string) (Deployment, error) {
	query := make(url.Values)
	path := "/v1/deployments/" + escapePath(deployment_id) + "/archive"
	var result Deployment
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Archive Archive an Environment (POST /v1/environments/{environment_id}/archive).
func (c *EnvironmentsService) Archive(ctx context.Context, environment_id string) (Environment, error) {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + "/archive"
	var result Environment
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Archive Archive a Memory Store (POST /v1/memory_stores/{store_id}/archive).
func (c *MemoryStoresService) Archive(ctx context.Context, store_id string) (MemoryStore, error) {
	query := make(url.Values)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/archive"
	var result MemoryStore
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Archive Archive a non-running Session (POST /v1/sessions/{session_id}/archive).
func (c *SessionsService) Archive(ctx context.Context, session_id string) (Session, error) {
	query := make(url.Values)
	path := "/v1/sessions/" + escapePath(session_id) + "/archive"
	var result Session
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Archive Archive a non-running Session Thread (POST /v1/sessions/{session_id}/threads/{thread_id}/archive).
func (c *SessionsThreadsService) Archive(ctx context.Context, session_id string, thread_id string) (SessionThread, error) {
	query := make(url.Values)
	path := "/v1/sessions/" + escapePath(session_id) + "/threads/" + escapePath(thread_id) + "/archive"
	var result SessionThread
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Archive Archive a Vault, archive its Credentials, and purge their encrypted payloads (POST /v1/vaults/{vault_id}/archive).
func (c *VaultsService) Archive(ctx context.Context, vault_id string) (Vault, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + "/archive"
	var result Vault
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Archive Archive a Credential and purge its encrypted payload (POST /v1/vaults/{vault_id}/credentials/{credential_id}/archive).
func (c *VaultsCredentialsService) Archive(ctx context.Context, vault_id string, credential_id string) (VaultCredential, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + "/credentials/" + escapePath(credential_id) + "/archive"
	var result VaultCredential
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// New Create an Agent (POST /v1/agents).
func (c *AgentsService) New(ctx context.Context, body AgentCreateRequest) (Agent, error) {
	query := make(url.Values)
	path := "/v1/agents"
	var result Agent
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// New Create a Deployment (POST /v1/deployments).
func (c *DeploymentsService) New(ctx context.Context, body DeploymentCreateRequest) (Deployment, error) {
	query := make(url.Values)
	path := "/v1/deployments"
	var result Deployment
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// New Create an Environment (POST /v1/environments).
func (c *EnvironmentsService) New(ctx context.Context, body EnvironmentCreateRequest) (Environment, error) {
	query := make(url.Values)
	path := "/v1/environments"
	var result Environment
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// New Create a Memory (POST /v1/memory_stores/{store_id}/memories).
func (c *MemoryStoresMemoriesService) New(ctx context.Context, store_id string, params CreateMemoryParams, body MemoryCreateRequest) (Memory, error) {
	query := make(url.Values)
	addQuery(query, "view", params.View)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/memories"
	var result Memory
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// New Create a Memory Store (POST /v1/memory_stores).
func (c *MemoryStoresService) New(ctx context.Context, body MemoryStoreCreateRequest) (MemoryStore, error) {
	query := make(url.Values)
	path := "/v1/memory_stores"
	var result MemoryStore
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// New Create a Session (POST /v1/sessions).
func (c *SessionsService) New(ctx context.Context, body SessionCreateRequest) (Session, error) {
	query := make(url.Values)
	path := "/v1/sessions"
	var result Session
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// New Create a custom Skill and its first immutable Version (POST /v1/skills).
func (c *SkillsService) New(ctx context.Context, body SkillUploadRequest) (SkillResource, error) {
	query := make(url.Values)
	path := "/v1/skills"
	var result SkillResource
	var parts []multipartPart
	if value, ok := body.DisplayTitle.Get(); ok {
		parts = append(parts, multipartPart{name: "display_title", value: value})
	}
	for i := range body.Files {
		parts = append(parts, multipartPart{name: "files", upload: &body.Files[i]})
	}
	err := c.client.doMultipart(ctx, "POST", path, query, parts, &result, true)
	return result, err
}

// New Create an immutable Skill Version (POST /v1/skills/{skill_id}/versions).
func (c *SkillsVersionsService) New(ctx context.Context, skill_id string, body SkillVersionUploadRequest) (SkillVersion, error) {
	query := make(url.Values)
	path := "/v1/skills/" + escapePath(skill_id) + "/versions"
	var result SkillVersion
	var parts []multipartPart
	for i := range body.Files {
		parts = append(parts, multipartPart{name: "files", upload: &body.Files[i]})
	}
	err := c.client.doMultipart(ctx, "POST", path, query, parts, &result, true)
	return result, err
}

// New Create a Vault (POST /v1/vaults).
func (c *VaultsService) New(ctx context.Context, body VaultCreateRequest) (Vault, error) {
	query := make(url.Values)
	path := "/v1/vaults"
	var result Vault
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// New Create an encrypted Credential (POST /v1/vaults/{vault_id}/credentials).
func (c *VaultsCredentialsService) New(ctx context.Context, vault_id string, body VaultCredentialCreateRequest) (VaultCredential, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + "/credentials"
	var result VaultCredential
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// New Create a Webhook endpoint (POST /v1/webhooks).
func (c *WebhooksService) New(ctx context.Context, body WebhookCreateRequest) (WebhookWithSigningSecret, error) {
	query := make(url.Values)
	path := "/v1/webhooks"
	var result WebhookWithSigningSecret
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Delete Delete an unreferenced Environment (DELETE /v1/environments/{environment_id}).
func (c *EnvironmentsService) Delete(ctx context.Context, environment_id string) (EnvironmentDeleted, error) {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + ""
	var result EnvironmentDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a File (DELETE /v1/files/{file_id}).
func (c *FilesService) Delete(ctx context.Context, file_id string) (FileDeleted, error) {
	query := make(url.Values)
	path := "/v1/files/" + escapePath(file_id) + ""
	var result FileDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a Memory with an optional SHA-256 precondition (DELETE /v1/memory_stores/{store_id}/memories/{memory_id}).
func (c *MemoryStoresMemoriesService) Delete(ctx context.Context, store_id string, memory_id string, params DeleteMemoryParams) (MemoryDeleted, error) {
	query := make(url.Values)
	addQuery(query, "expected_content_sha256", params.ExpectedContentSHA256)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/memories/" + escapePath(memory_id) + ""
	var result MemoryDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a Memory Store (DELETE /v1/memory_stores/{store_id}).
func (c *MemoryStoresService) Delete(ctx context.Context, store_id string) (MemoryStoreDeleted, error) {
	query := make(url.Values)
	path := "/v1/memory_stores/" + escapePath(store_id) + ""
	var result MemoryStoreDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a non-running Session and its event history (DELETE /v1/sessions/{session_id}).
func (c *SessionsService) Delete(ctx context.Context, session_id string) (SessionDeleted, error) {
	query := make(url.Values)
	path := "/v1/sessions/" + escapePath(session_id) + ""
	var result SessionDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a Skill after all of its Versions have been deleted (DELETE /v1/skills/{skill_id}).
func (c *SkillsService) Delete(ctx context.Context, skill_id string) (SkillDeleted, error) {
	query := make(url.Values)
	path := "/v1/skills/" + escapePath(skill_id) + ""
	var result SkillDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a Skill Version and its archived contents (DELETE /v1/skills/{skill_id}/versions/{version}).
func (c *SkillsVersionsService) Delete(ctx context.Context, skill_id string, version string) (SkillVersionDeleted, error) {
	query := make(url.Values)
	path := "/v1/skills/" + escapePath(skill_id) + "/versions/" + escapePath(version) + ""
	var result SkillVersionDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a Vault and all of its Credentials (DELETE /v1/vaults/{vault_id}).
func (c *VaultsService) Delete(ctx context.Context, vault_id string) (VaultDeleted, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + ""
	var result VaultDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a Credential (DELETE /v1/vaults/{vault_id}/credentials/{credential_id}).
func (c *VaultsCredentialsService) Delete(ctx context.Context, vault_id string, credential_id string) (VaultCredentialDeleted, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + "/credentials/" + escapePath(credential_id) + ""
	var result VaultCredentialDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Delete Delete a Webhook endpoint and its pending deliveries (DELETE /v1/webhooks/{webhook_id}).
func (c *WebhooksService) Delete(ctx context.Context, webhook_id string) (WebhookDeleted, error) {
	query := make(url.Values)
	path := "/v1/webhooks/" + escapePath(webhook_id) + ""
	var result WebhookDeleted
	err := c.client.doJSON(ctx, "DELETE", path, query, nil, &result, true)
	return result, err
}

// Download Download an immutable File in the authenticated Workspace (GET /v1/files/{file_id}/content).
func (c *FilesService) Download(ctx context.Context, file_id string) (*Download, error) {
	query := make(url.Values)
	path := "/v1/files/" + escapePath(file_id) + "/content"
	return c.client.download(ctx, "GET", path, query, "application/binary", true)
}

// Download Download a Skill Version as a zip archive (GET /v1/skills/{skill_id}/versions/{version}/content).
func (c *SkillsVersionsService) Download(ctx context.Context, skill_id string, version string) (*Download, error) {
	query := make(url.Values)
	path := "/v1/skills/" + escapePath(skill_id) + "/versions/" + escapePath(version) + "/content"
	return c.client.download(ctx, "GET", path, query, "application/zip", true)
}

// Fail Terminate a Session whose immutable worker inputs are invalid (POST /v1/environments/{environment_id}/work/{work_id}/fail).
func (c *EnvironmentsWorkService) Fail(ctx context.Context, environment_id string, work_id string, body EnvironmentWorkFailureRequest) error {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + "/work/" + escapePath(work_id) + "/fail"
	return c.client.doJSON(ctx, "POST", path, query, body, nil, true)
}

// Get Get an Agent (GET /v1/agents/{agent_id}).
func (c *AgentsService) Get(ctx context.Context, agent_id string) (Agent, error) {
	query := make(url.Values)
	path := "/v1/agents/" + escapePath(agent_id) + ""
	var result Agent
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Deployment (GET /v1/deployments/{deployment_id}).
func (c *DeploymentsService) Get(ctx context.Context, deployment_id string) (Deployment, error) {
	query := make(url.Values)
	path := "/v1/deployments/" + escapePath(deployment_id) + ""
	var result Deployment
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Deployment Run (GET /v1/deployment_runs/{deployment_run_id}).
func (c *DeploymentRunsService) Get(ctx context.Context, deployment_run_id string) (DeploymentRun, error) {
	query := make(url.Values)
	path := "/v1/deployment_runs/" + escapePath(deployment_run_id) + ""
	var result DeploymentRun
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get an Environment (GET /v1/environments/{environment_id}).
func (c *EnvironmentsService) Get(ctx context.Context, environment_id string) (Environment, error) {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + ""
	var result Environment
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get an Environment Work item (GET /v1/environments/{environment_id}/work/{work_id}).
func (c *EnvironmentsWorkService) Get(ctx context.Context, environment_id string, work_id string) (EnvironmentWork, error) {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + "/work/" + escapePath(work_id) + ""
	var result EnvironmentWork
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Stats Get Environment Work queue statistics (GET /v1/environments/{environment_id}/work/stats).
func (c *EnvironmentsWorkService) Stats(ctx context.Context, environment_id string) (EnvironmentWorkQueueStats, error) {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + "/work/stats"
	var result EnvironmentWorkQueueStats
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get File metadata (GET /v1/files/{file_id}).
func (c *FilesService) Get(ctx context.Context, file_id string) (File, error) {
	query := make(url.Values)
	path := "/v1/files/" + escapePath(file_id) + ""
	var result File
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Memory (GET /v1/memory_stores/{store_id}/memories/{memory_id}).
func (c *MemoryStoresMemoriesService) Get(ctx context.Context, store_id string, memory_id string, params GetMemoryParams) (Memory, error) {
	query := make(url.Values)
	addQuery(query, "view", params.View)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/memories/" + escapePath(memory_id) + ""
	var result Memory
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Memory Store (GET /v1/memory_stores/{store_id}).
func (c *MemoryStoresService) Get(ctx context.Context, store_id string) (MemoryStore, error) {
	query := make(url.Values)
	path := "/v1/memory_stores/" + escapePath(store_id) + ""
	var result MemoryStore
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get an immutable Memory Version (GET /v1/memory_stores/{store_id}/memory_versions/{version_id}).
func (c *MemoryStoresVersionsService) Get(ctx context.Context, store_id string, version_id string, params GetMemoryVersionParams) (MemoryVersion, error) {
	query := make(url.Values)
	addQuery(query, "view", params.View)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/memory_versions/" + escapePath(version_id) + ""
	var result MemoryVersion
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Session (GET /v1/sessions/{session_id}).
func (c *SessionsService) Get(ctx context.Context, session_id string) (Session, error) {
	query := make(url.Values)
	path := "/v1/sessions/" + escapePath(session_id) + ""
	var result Session
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Session Thread (GET /v1/sessions/{session_id}/threads/{thread_id}).
func (c *SessionsThreadsService) Get(ctx context.Context, session_id string, thread_id string) (SessionThread, error) {
	query := make(url.Values)
	path := "/v1/sessions/" + escapePath(session_id) + "/threads/" + escapePath(thread_id) + ""
	var result SessionThread
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Skill (GET /v1/skills/{skill_id}).
func (c *SkillsService) Get(ctx context.Context, skill_id string) (SkillResource, error) {
	query := make(url.Values)
	path := "/v1/skills/" + escapePath(skill_id) + ""
	var result SkillResource
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Skill Version (GET /v1/skills/{skill_id}/versions/{version}).
func (c *SkillsVersionsService) Get(ctx context.Context, skill_id string, version string) (SkillVersion, error) {
	query := make(url.Values)
	path := "/v1/skills/" + escapePath(skill_id) + "/versions/" + escapePath(version) + ""
	var result SkillVersion
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Vault (GET /v1/vaults/{vault_id}).
func (c *VaultsService) Get(ctx context.Context, vault_id string) (Vault, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + ""
	var result Vault
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Credential without sensitive fields (GET /v1/vaults/{vault_id}/credentials/{credential_id}).
func (c *VaultsCredentialsService) Get(ctx context.Context, vault_id string, credential_id string) (VaultCredential, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + "/credentials/" + escapePath(credential_id) + ""
	var result VaultCredential
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Get Get a Webhook endpoint without its signing secret (GET /v1/webhooks/{webhook_id}).
func (c *WebhooksService) Get(ctx context.Context, webhook_id string) (Webhook, error) {
	query := make(url.Values)
	path := "/v1/webhooks/" + escapePath(webhook_id) + ""
	var result Webhook
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Health Liveness probe (GET /healthz).
func (c *SystemService) Health(ctx context.Context) error {
	query := make(url.Values)
	path := "/healthz"
	return c.client.doJSON(ctx, "GET", path, query, nil, nil, false)
}

// Heartbeat Record a conditional heartbeat and extend the Work lease (POST /v1/environments/{environment_id}/work/{work_id}/heartbeat).
func (c *EnvironmentsWorkService) Heartbeat(ctx context.Context, environment_id string, work_id string, params HeartbeatEnvironmentWorkParams) (EnvironmentWorkHeartbeat, error) {
	query := make(url.Values)
	addQuery(query, "expected_last_heartbeat", params.ExpectedLastHeartbeat)
	addQuery(query, "desired_ttl_seconds", params.DesiredTTLSeconds)
	path := "/v1/environments/" + escapePath(environment_id) + "/work/" + escapePath(work_id) + "/heartbeat"
	var result EnvironmentWorkHeartbeat
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// List List Agent versions (GET /v1/agents/{agent_id}/versions).
func (c *AgentsVersionsService) List(ctx context.Context, agent_id string, params ListAgentVersionsParams) (AgentList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	path := "/v1/agents/" + escapePath(agent_id) + "/versions"
	var result AgentList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *AgentsVersionsService) ListAutoPaging(ctx context.Context, agent_id string, params ListAgentVersionsParams) *PageIterator[Agent] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[Agent], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, agent_id, params)
		if err != nil {
			return Page[Agent]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[Agent]{Data: result.Data, Next: next}, nil
	})
}

// List List Agents (GET /v1/agents).
func (c *AgentsService) List(ctx context.Context, params ListAgentsParams) (AgentList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "include_archived", params.IncludeArchived)
	addQuery(query, "created_at[gte]", params.CreatedAtGte)
	addQuery(query, "created_at[lte]", params.CreatedAtLte)
	path := "/v1/agents"
	var result AgentList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *AgentsService) ListAutoPaging(ctx context.Context, params ListAgentsParams) *PageIterator[Agent] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[Agent], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[Agent]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[Agent]{Data: result.Data, Next: next}, nil
	})
}

// List List Deployment Runs (GET /v1/deployment_runs).
func (c *DeploymentRunsService) List(ctx context.Context, params ListDeploymentRunsParams) (DeploymentRunList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "created_at[gt]", params.CreatedAtGt)
	addQuery(query, "created_at[gte]", params.CreatedAtGte)
	addQuery(query, "created_at[lt]", params.CreatedAtLt)
	addQuery(query, "created_at[lte]", params.CreatedAtLte)
	addQuery(query, "deployment_id", params.DeploymentID)
	addQuery(query, "has_error", params.HasError)
	addQuery(query, "trigger_type", params.TriggerType)
	path := "/v1/deployment_runs"
	var result DeploymentRunList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *DeploymentRunsService) ListAutoPaging(ctx context.Context, params ListDeploymentRunsParams) *PageIterator[DeploymentRun] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[DeploymentRun], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[DeploymentRun]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[DeploymentRun]{Data: result.Data, Next: next}, nil
	})
}

// List List Deployments (GET /v1/deployments).
func (c *DeploymentsService) List(ctx context.Context, params ListDeploymentsParams) (DeploymentList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "agent_id", params.AgentID)
	addQuery(query, "created_at[gte]", params.CreatedAtGte)
	addQuery(query, "created_at[lte]", params.CreatedAtLte)
	addQuery(query, "include_archived", params.IncludeArchived)
	addQuery(query, "status", params.Status)
	path := "/v1/deployments"
	var result DeploymentList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *DeploymentsService) ListAutoPaging(ctx context.Context, params ListDeploymentsParams) *PageIterator[Deployment] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[Deployment], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[Deployment]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[Deployment]{Data: result.Data, Next: next}, nil
	})
}

// List List self-hosted Environment Work items (GET /v1/environments/{environment_id}/work).
func (c *EnvironmentsWorkService) List(ctx context.Context, environment_id string, params ListEnvironmentWorkParams) (EnvironmentWorkList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	path := "/v1/environments/" + escapePath(environment_id) + "/work"
	var result EnvironmentWorkList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *EnvironmentsWorkService) ListAutoPaging(ctx context.Context, environment_id string, params ListEnvironmentWorkParams) *PageIterator[EnvironmentWork] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[EnvironmentWork], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, environment_id, params)
		if err != nil {
			return Page[EnvironmentWork]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[EnvironmentWork]{Data: result.Data, Next: next}, nil
	})
}

// List List Environments (GET /v1/environments).
func (c *EnvironmentsService) List(ctx context.Context, params ListEnvironmentsParams) (EnvironmentList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "include_archived", params.IncludeArchived)
	path := "/v1/environments"
	var result EnvironmentList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *EnvironmentsService) ListAutoPaging(ctx context.Context, params ListEnvironmentsParams) *PageIterator[Environment] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[Environment], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[Environment]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[Environment]{Data: result.Data, Next: next}, nil
	})
}

// List List Files (GET /v1/files).
func (c *FilesService) List(ctx context.Context, params ListFilesParams) (FileList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "after_id", params.AfterID)
	addQuery(query, "before_id", params.BeforeID)
	path := "/v1/files"
	var result FileList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging follows Files cursors, preserving before_id direction.
func (c *FilesService) ListAutoPaging(ctx context.Context, params ListFilesParams) *PageIterator[File] {
	first, _ := params.AfterID.Get()
	before, reverse := params.BeforeID.Get()
	if reverse {
		first = before
	}
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[File], error) {
		if cursor != "" {
			if reverse {
				params.BeforeID = Some(cursor)
			} else {
				params.AfterID = Some(cursor)
			}
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[File]{}, err
		}
		next := ""
		if result.HasMore {
			id := result.LastID
			if reverse {
				id = result.FirstID
			}
			if id == nil || *id == "" {
				return Page[File]{}, errors.New("mango: Files has_more without a cursor")
			}
			next = *id
		}
		return Page[File]{Data: result.Data, Next: next}, nil
	})
}

// List List Memories and optional depth-one path prefixes (GET /v1/memory_stores/{store_id}/memories).
func (c *MemoryStoresMemoriesService) List(ctx context.Context, store_id string, params ListMemoriesParams) (MemoryList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "view", params.View)
	addQuery(query, "path_prefix", params.PathPrefix)
	addQuery(query, "depth", params.Depth)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/memories"
	var result MemoryList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *MemoryStoresMemoriesService) ListAutoPaging(ctx context.Context, store_id string, params ListMemoriesParams) *PageIterator[MemoryListItem] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[MemoryListItem], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, store_id, params)
		if err != nil {
			return Page[MemoryListItem]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[MemoryListItem]{Data: result.Data, Next: next}, nil
	})
}

// List List Memory Stores (GET /v1/memory_stores).
func (c *MemoryStoresService) List(ctx context.Context, params ListMemoryStoresParams) (MemoryStoreList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "include_archived", params.IncludeArchived)
	addQuery(query, "created_at[gte]", params.CreatedAtGte)
	addQuery(query, "created_at[lte]", params.CreatedAtLte)
	path := "/v1/memory_stores"
	var result MemoryStoreList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *MemoryStoresService) ListAutoPaging(ctx context.Context, params ListMemoryStoresParams) *PageIterator[MemoryStore] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[MemoryStore], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[MemoryStore]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[MemoryStore]{Data: result.Data, Next: next}, nil
	})
}

// List List immutable Memory Versions (GET /v1/memory_stores/{store_id}/memory_versions).
func (c *MemoryStoresVersionsService) List(ctx context.Context, store_id string, params ListMemoryVersionsParams) (MemoryVersionList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "view", params.View)
	addQuery(query, "api_key_id", params.APIKeyID)
	addQuery(query, "session_id", params.SessionID)
	addQuery(query, "memory_id", params.MemoryID)
	addQuery(query, "operation", params.Operation)
	addQuery(query, "created_at[gte]", params.CreatedAtGte)
	addQuery(query, "created_at[lte]", params.CreatedAtLte)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/memory_versions"
	var result MemoryVersionList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *MemoryStoresVersionsService) ListAutoPaging(ctx context.Context, store_id string, params ListMemoryVersionsParams) *PageIterator[MemoryVersion] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[MemoryVersion], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, store_id, params)
		if err != nil {
			return Page[MemoryVersion]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[MemoryVersion]{Data: result.Data, Next: next}, nil
	})
}

// List List Session event history (GET /v1/sessions/{session_id}/events).
func (c *SessionsEventsService) List(ctx context.Context, session_id string, params ListSessionEventsParams) (SessionEventList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "order", params.Order)
	addQuery(query, "page", params.Page)
	addQueryArray(query, "types[]", params.Types)
	addQuery(query, "created_at[gt]", params.CreatedAtGt)
	addQuery(query, "created_at[gte]", params.CreatedAtGte)
	addQuery(query, "created_at[lt]", params.CreatedAtLt)
	addQuery(query, "created_at[lte]", params.CreatedAtLte)
	path := "/v1/sessions/" + escapePath(session_id) + "/events"
	var result SessionEventList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *SessionsEventsService) ListAutoPaging(ctx context.Context, session_id string, params ListSessionEventsParams) *PageIterator[SessionEvent] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[SessionEvent], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, session_id, params)
		if err != nil {
			return Page[SessionEvent]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[SessionEvent]{Data: result.Data, Next: next}, nil
	})
}

// List List persisted events for one Session Thread (GET /v1/sessions/{session_id}/threads/{thread_id}/events).
func (c *SessionsThreadsEventsService) List(ctx context.Context, session_id string, thread_id string, params ListSessionThreadEventsParams) (SessionEventList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	path := "/v1/sessions/" + escapePath(session_id) + "/threads/" + escapePath(thread_id) + "/events"
	var result SessionEventList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *SessionsThreadsEventsService) ListAutoPaging(ctx context.Context, session_id string, thread_id string, params ListSessionThreadEventsParams) *PageIterator[SessionEvent] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[SessionEvent], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, session_id, thread_id, params)
		if err != nil {
			return Page[SessionEvent]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[SessionEvent]{Data: result.Data, Next: next}, nil
	})
}

// List List Session Threads, primary first (GET /v1/sessions/{session_id}/threads).
func (c *SessionsThreadsService) List(ctx context.Context, session_id string, params ListSessionThreadsParams) (SessionThreadList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	path := "/v1/sessions/" + escapePath(session_id) + "/threads"
	var result SessionThreadList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *SessionsThreadsService) ListAutoPaging(ctx context.Context, session_id string, params ListSessionThreadsParams) *PageIterator[SessionThread] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[SessionThread], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, session_id, params)
		if err != nil {
			return Page[SessionThread]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[SessionThread]{Data: result.Data, Next: next}, nil
	})
}

// List List Sessions (GET /v1/sessions).
func (c *SessionsService) List(ctx context.Context, params ListSessionsParams) (SessionList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "order", params.Order)
	addQuery(query, "agent_id", params.AgentID)
	addQuery(query, "agent_version", params.AgentVersion)
	addQueryArray(query, "statuses[]", params.Statuses)
	addQuery(query, "include_archived", params.IncludeArchived)
	addQuery(query, "created_at[gt]", params.CreatedAtGt)
	addQuery(query, "created_at[gte]", params.CreatedAtGte)
	addQuery(query, "created_at[lt]", params.CreatedAtLt)
	addQuery(query, "created_at[lte]", params.CreatedAtLte)
	addQuery(query, "deployment_id", params.DeploymentID)
	addQuery(query, "memory_store_id", params.MemoryStoreID)
	path := "/v1/sessions"
	var result SessionList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *SessionsService) ListAutoPaging(ctx context.Context, params ListSessionsParams) *PageIterator[Session] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[Session], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[Session]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[Session]{Data: result.Data, Next: next}, nil
	})
}

// List List immutable Skill Versions (GET /v1/skills/{skill_id}/versions).
func (c *SkillsVersionsService) List(ctx context.Context, skill_id string, params ListSkillVersionsParams) (SkillVersionList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	path := "/v1/skills/" + escapePath(skill_id) + "/versions"
	var result SkillVersionList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *SkillsVersionsService) ListAutoPaging(ctx context.Context, skill_id string, params ListSkillVersionsParams) *PageIterator[SkillVersion] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[SkillVersion], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, skill_id, params)
		if err != nil {
			return Page[SkillVersion]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[SkillVersion]{Data: result.Data, Next: next}, nil
	})
}

// List List Skills (GET /v1/skills).
func (c *SkillsService) List(ctx context.Context, params ListSkillsParams) (SkillList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "source", params.Source)
	path := "/v1/skills"
	var result SkillList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *SkillsService) ListAutoPaging(ctx context.Context, params ListSkillsParams) *PageIterator[SkillResource] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[SkillResource], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[SkillResource]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[SkillResource]{Data: result.Data, Next: next}, nil
	})
}

// List List Credentials in a Vault (GET /v1/vaults/{vault_id}/credentials).
func (c *VaultsCredentialsService) List(ctx context.Context, vault_id string, params ListVaultCredentialsParams) (VaultCredentialList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "include_archived", params.IncludeArchived)
	path := "/v1/vaults/" + escapePath(vault_id) + "/credentials"
	var result VaultCredentialList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *VaultsCredentialsService) ListAutoPaging(ctx context.Context, vault_id string, params ListVaultCredentialsParams) *PageIterator[VaultCredential] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[VaultCredential], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, vault_id, params)
		if err != nil {
			return Page[VaultCredential]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[VaultCredential]{Data: result.Data, Next: next}, nil
	})
}

// List List Vaults (GET /v1/vaults).
func (c *VaultsService) List(ctx context.Context, params ListVaultsParams) (VaultList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	addQuery(query, "include_archived", params.IncludeArchived)
	path := "/v1/vaults"
	var result VaultList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *VaultsService) ListAutoPaging(ctx context.Context, params ListVaultsParams) *PageIterator[Vault] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[Vault], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[Vault]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[Vault]{Data: result.Data, Next: next}, nil
	})
}

// List List Webhook endpoints (GET /v1/webhooks).
func (c *WebhooksService) List(ctx context.Context, params ListWebhooksParams) (WebhookList, error) {
	query := make(url.Values)
	addQuery(query, "limit", params.Limit)
	addQuery(query, "page", params.Page)
	path := "/v1/webhooks"
	var result WebhookList
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// ListAutoPaging iterates every result, preserving the initial filters.
func (c *WebhooksService) ListAutoPaging(ctx context.Context, params ListWebhooksParams) *PageIterator[Webhook] {
	first, _ := params.Page.Get()
	return NewPageIterator(ctx, first, func(ctx context.Context, cursor string) (Page[Webhook], error) {
		if cursor != "" {
			params.Page = Some(cursor)
		}
		result, err := c.List(ctx, params)
		if err != nil {
			return Page[Webhook]{}, err
		}
		next := ""
		if result.NextPage != nil {
			next = *result.NextPage
		}
		return Page[Webhook]{Data: result.Data, Next: next}, nil
	})
}

// OpenAPI Get the Mango OpenAPI document (GET /openapi.yaml).
func (c *SystemService) OpenAPI(ctx context.Context) (*Download, error) {
	query := make(url.Values)
	path := "/openapi.yaml"
	return c.client.download(ctx, "GET", path, query, "application/yaml", false)
}

// Pause Pause scheduled triggers (POST /v1/deployments/{deployment_id}/pause).
func (c *DeploymentsService) Pause(ctx context.Context, deployment_id string) (Deployment, error) {
	query := make(url.Values)
	path := "/v1/deployments/" + escapePath(deployment_id) + "/pause"
	var result Deployment
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Poll Poll and tentatively claim the oldest available Work item (GET /v1/environments/{environment_id}/work/poll).
func (c *EnvironmentsWorkService) Poll(ctx context.Context, environment_id string, params PollEnvironmentWorkParams) (PollEnvironmentWorkResponse, error) {
	query := make(url.Values)
	addQuery(query, "block_ms", params.BlockMs)
	addQuery(query, "reclaim_older_than_ms", params.ReclaimOlderThanMs)
	addQuery(query, "worker_id", params.WorkerID)
	path := "/v1/environments/" + escapePath(environment_id) + "/work/poll"
	var result PollEnvironmentWorkResponse
	err := c.client.doJSON(ctx, "GET", path, query, nil, &result, true)
	return result, err
}

// Readiness Readiness probe (GET /readyz).
func (c *SystemService) Readiness(ctx context.Context) error {
	query := make(url.Values)
	path := "/readyz"
	return c.client.doJSON(ctx, "GET", path, query, nil, nil, false)
}

// Redact Permanently redact the content of an historical Memory Version (POST /v1/memory_stores/{store_id}/memory_versions/{version_id}/redact).
func (c *MemoryStoresVersionsService) Redact(ctx context.Context, store_id string, version_id string) (MemoryVersion, error) {
	query := make(url.Values)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/memory_versions/" + escapePath(version_id) + "/redact"
	var result MemoryVersion
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// RegenerateSigningSecret Replace and reveal a Webhook signing secret (POST /v1/webhooks/{webhook_id}/regenerate_signing_secret).
func (c *WebhooksService) RegenerateSigningSecret(ctx context.Context, webhook_id string) (WebhookWithSigningSecret, error) {
	query := make(url.Values)
	path := "/v1/webhooks/" + escapePath(webhook_id) + "/regenerate_signing_secret"
	var result WebhookWithSigningSecret
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Run Run a Deployment immediately (POST /v1/deployments/{deployment_id}/run).
func (c *DeploymentsService) Run(ctx context.Context, deployment_id string) (DeploymentRun, error) {
	query := make(url.Values)
	path := "/v1/deployments/" + escapePath(deployment_id) + "/run"
	var result DeploymentRun
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Send Send Session events (POST /v1/sessions/{session_id}/events).
func (c *SessionsEventsService) Send(ctx context.Context, session_id string, body SendSessionEventsRequest) (SessionEventBatch, error) {
	query := make(url.Values)
	path := "/v1/sessions/" + escapePath(session_id) + "/events"
	var result SessionEventBatch
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Stop Request graceful or forced Work shutdown (POST /v1/environments/{environment_id}/work/{work_id}/stop).
func (c *EnvironmentsWorkService) Stop(ctx context.Context, environment_id string, work_id string, body EnvironmentWorkStopRequest) error {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + "/work/" + escapePath(work_id) + "/stop"
	return c.client.doJSON(ctx, "POST", path, query, body, nil, true)
}

// Stream Stream live Session events over SSE (GET /v1/sessions/{session_id}/events/stream).
func (c *SessionsEventsService) Stream(ctx context.Context, session_id string, params StreamSessionEventsParams) (*EventStream, error) {
	query := make(url.Values)
	addQueryArray(query, "event_deltas[]", params.EventDeltas)
	path := "/v1/sessions/" + escapePath(session_id) + "/events/stream"
	return c.client.stream(ctx, "GET", path, query, true)
}

// Stream Stream live events for one Session Thread over SSE (GET /v1/sessions/{session_id}/threads/{thread_id}/stream).
func (c *SessionsThreadsEventsService) Stream(ctx context.Context, session_id string, thread_id string, params StreamSessionThreadEventsParams) (*EventStream, error) {
	query := make(url.Values)
	addQueryArray(query, "event_deltas[]", params.EventDeltas)
	path := "/v1/sessions/" + escapePath(session_id) + "/threads/" + escapePath(thread_id) + "/stream"
	return c.client.stream(ctx, "GET", path, query, true)
}

// Unpause Resume scheduled triggers without backfilling missed occurrences (POST /v1/deployments/{deployment_id}/unpause).
func (c *DeploymentsService) Unpause(ctx context.Context, deployment_id string) (Deployment, error) {
	query := make(url.Values)
	path := "/v1/deployments/" + escapePath(deployment_id) + "/unpause"
	var result Deployment
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}

// Update Update an Agent and create a new version when fields change (POST /v1/agents/{agent_id}).
func (c *AgentsService) Update(ctx context.Context, agent_id string, body AgentUpdateRequest) (Agent, error) {
	query := make(url.Values)
	path := "/v1/agents/" + escapePath(agent_id) + ""
	var result Agent
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Update a Deployment (POST /v1/deployments/{deployment_id}).
func (c *DeploymentsService) Update(ctx context.Context, deployment_id string, body DeploymentUpdateRequest) (Deployment, error) {
	query := make(url.Values)
	path := "/v1/deployments/" + escapePath(deployment_id) + ""
	var result Deployment
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Update an Environment (POST /v1/environments/{environment_id}).
func (c *EnvironmentsService) Update(ctx context.Context, environment_id string, body EnvironmentUpdateRequest) (Environment, error) {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + ""
	var result Environment
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Merge metadata into an Environment Work item (POST /v1/environments/{environment_id}/work/{work_id}).
func (c *EnvironmentsWorkService) Update(ctx context.Context, environment_id string, work_id string, body EnvironmentWorkUpdateRequest) (EnvironmentWork, error) {
	query := make(url.Values)
	path := "/v1/environments/" + escapePath(environment_id) + "/work/" + escapePath(work_id) + ""
	var result EnvironmentWork
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Update a Memory with an optional SHA-256 precondition (POST /v1/memory_stores/{store_id}/memories/{memory_id}).
func (c *MemoryStoresMemoriesService) Update(ctx context.Context, store_id string, memory_id string, params UpdateMemoryParams, body MemoryUpdateRequest) (Memory, error) {
	query := make(url.Values)
	addQuery(query, "view", params.View)
	path := "/v1/memory_stores/" + escapePath(store_id) + "/memories/" + escapePath(memory_id) + ""
	var result Memory
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Update a Memory Store (POST /v1/memory_stores/{store_id}).
func (c *MemoryStoresService) Update(ctx context.Context, store_id string, body MemoryStoreUpdateRequest) (MemoryStore, error) {
	query := make(url.Values)
	path := "/v1/memory_stores/" + escapePath(store_id) + ""
	var result MemoryStore
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Update Session metadata, title, or the next-turn tool configuration (POST /v1/sessions/{session_id}).
func (c *SessionsService) Update(ctx context.Context, session_id string, body SessionUpdateRequest) (Session, error) {
	query := make(url.Values)
	path := "/v1/sessions/" + escapePath(session_id) + ""
	var result Session
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Update a Vault (POST /v1/vaults/{vault_id}).
func (c *VaultsService) Update(ctx context.Context, vault_id string, body VaultUpdateRequest) (Vault, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + ""
	var result Vault
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Update a Credential (POST /v1/vaults/{vault_id}/credentials/{credential_id}).
func (c *VaultsCredentialsService) Update(ctx context.Context, vault_id string, credential_id string, body VaultCredentialUpdateRequest) (VaultCredential, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + "/credentials/" + escapePath(credential_id) + ""
	var result VaultCredential
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Update Update a Webhook endpoint (POST /v1/webhooks/{webhook_id}).
func (c *WebhooksService) Update(ctx context.Context, webhook_id string, body WebhookUpdateRequest) (Webhook, error) {
	query := make(url.Values)
	path := "/v1/webhooks/" + escapePath(webhook_id) + ""
	var result Webhook
	err := c.client.doJSON(ctx, "POST", path, query, body, &result, true)
	return result, err
}

// Upload Upload a File (POST /v1/files).
func (c *FilesService) Upload(ctx context.Context, body FileUploadRequest) (File, error) {
	query := make(url.Values)
	path := "/v1/files"
	var result File
	var parts []multipartPart
	parts = append(parts, multipartPart{name: "file", upload: &body.File})
	err := c.client.doMultipart(ctx, "POST", path, query, parts, &result, true)
	return result, err
}

// ValidateMCPOAuth Live-probe and, when needed, refresh an MCP OAuth Credential (POST /v1/vaults/{vault_id}/credentials/{credential_id}/mcp_oauth_validate).
func (c *VaultsCredentialsService) ValidateMCPOAuth(ctx context.Context, vault_id string, credential_id string) (VaultCredentialValidation, error) {
	query := make(url.Values)
	path := "/v1/vaults/" + escapePath(vault_id) + "/credentials/" + escapePath(credential_id) + "/mcp_oauth_validate"
	var result VaultCredentialValidation
	err := c.client.doJSON(ctx, "POST", path, query, nil, &result, true)
	return result, err
}
