// Code generated by python3 sdk/go/generate.py; DO NOT EDIT.

package mango

type resourceServices struct {
	Agents         AgentsService
	DeploymentRuns DeploymentRunsService
	Deployments    DeploymentsService
	Environments   EnvironmentsService
	Files          FilesService
	MemoryStores   MemoryStoresService
	Sessions       SessionsService
	Skills         SkillsService
	System         SystemService
	Vaults         VaultsService
	Webhooks       WebhooksService
}

// AgentsService operates on agents resources.
type AgentsService struct {
	client   *Client
	Versions AgentsVersionsService
}

// AgentsVersionsService operates on agents.versions resources.
type AgentsVersionsService struct {
	client *Client
}

// DeploymentRunsService operates on deployment_runs resources.
type DeploymentRunsService struct {
	client *Client
}

// DeploymentsService operates on deployments resources.
type DeploymentsService struct {
	client *Client
}

// EnvironmentsService operates on environments resources.
type EnvironmentsService struct {
	client *Client
	Work   EnvironmentsWorkService
}

// EnvironmentsWorkService operates on environments.work resources.
type EnvironmentsWorkService struct {
	client *Client
}

// FilesService operates on files resources.
type FilesService struct {
	client *Client
}

// MemoryStoresService operates on memory_stores resources.
type MemoryStoresService struct {
	client   *Client
	Memories MemoryStoresMemoriesService
	Versions MemoryStoresVersionsService
}

// MemoryStoresMemoriesService operates on memory_stores.memories resources.
type MemoryStoresMemoriesService struct {
	client *Client
}

// MemoryStoresVersionsService operates on memory_stores.versions resources.
type MemoryStoresVersionsService struct {
	client *Client
}

// SessionsService operates on sessions resources.
type SessionsService struct {
	client  *Client
	Events  SessionsEventsService
	Threads SessionsThreadsService
}

// SessionsEventsService operates on sessions.events resources.
type SessionsEventsService struct {
	client *Client
}

// SessionsThreadsService operates on sessions.threads resources.
type SessionsThreadsService struct {
	client *Client
	Events SessionsThreadsEventsService
}

// SessionsThreadsEventsService operates on sessions.threads.events resources.
type SessionsThreadsEventsService struct {
	client *Client
}

// SkillsService operates on skills resources.
type SkillsService struct {
	client   *Client
	Versions SkillsVersionsService
}

// SkillsVersionsService operates on skills.versions resources.
type SkillsVersionsService struct {
	client *Client
}

// SystemService operates on system resources.
type SystemService struct {
	client *Client
}

// VaultsService operates on vaults resources.
type VaultsService struct {
	client      *Client
	Credentials VaultsCredentialsService
}

// VaultsCredentialsService operates on vaults.credentials resources.
type VaultsCredentialsService struct {
	client *Client
}

// WebhooksService operates on webhooks resources.
type WebhooksService struct {
	client *Client
}

func (c *Client) initServices() {
	c.resourceServices = resourceServices{
		Agents:         AgentsService{client: c, Versions: AgentsVersionsService{client: c}},
		DeploymentRuns: DeploymentRunsService{client: c},
		Deployments:    DeploymentsService{client: c},
		Environments:   EnvironmentsService{client: c, Work: EnvironmentsWorkService{client: c}},
		Files:          FilesService{client: c},
		MemoryStores:   MemoryStoresService{client: c, Memories: MemoryStoresMemoriesService{client: c}, Versions: MemoryStoresVersionsService{client: c}},
		Sessions:       SessionsService{client: c, Events: SessionsEventsService{client: c}, Threads: SessionsThreadsService{client: c, Events: SessionsThreadsEventsService{client: c}}},
		Skills:         SkillsService{client: c, Versions: SkillsVersionsService{client: c}},
		System:         SystemService{client: c},
		Vaults:         VaultsService{client: c, Credentials: VaultsCredentialsService{client: c}},
		Webhooks:       WebhooksService{client: c},
	}
}
