// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          string
	Version     int32
	Name        string
	Body        []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
	WorkspaceID string
}

type AgentSkillVersion struct {
	AgentID      string
	AgentVersion int32
	Position     int32
	SkillID      string
	SkillVersion string
}

type ApiKey struct {
	ID          string
	WorkspaceID string
	SecretHash  []byte
	Label       string
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
}

type Deployment struct {
	ID                string
	AgentID           string
	AgentVersion      int32
	EnvironmentID     string
	Status            string
	Body              []byte
	NextRunAt         pgtype.Timestamptz
	ScheduleClaimedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ArchivedAt        pgtype.Timestamptz
	WorkspaceID       string
}

type DeploymentRun struct {
	ID           string
	DeploymentID string
	SessionID    *string
	ErrorType    *string
	TriggerType  string
	ScheduledAt  pgtype.Timestamptz
	Body         []byte
	CreatedAt    pgtype.Timestamptz
}

type Environment struct {
	ID          string
	Name        string
	ConfigType  string
	Body        []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
	WorkspaceID string
}

type EnvironmentWork struct {
	ID                string
	EnvironmentID     string
	SessionID         string
	ActivationSeq     int64
	State             string
	Metadata          []byte
	CreatedAt         pgtype.Timestamptz
	AcknowledgedAt    pgtype.Timestamptz
	StartedAt         pgtype.Timestamptz
	LatestHeartbeatAt pgtype.Timestamptz
	TtlSeconds        int64
	StopRequestedAt   pgtype.Timestamptz
	StoppedAt         pgtype.Timestamptz
	PolledAt          pgtype.Timestamptz
	PollWorkerID      *string
}

type EnvironmentWorkPoller struct {
	EnvironmentID string
	WorkerID      string
	PolledAt      pgtype.Timestamptz
}

type Event struct {
	ID          string
	SessionID   string
	Seq         int64
	Type        string
	Payload     []byte
	TurnEventID *string
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	// Owning Session Thread ledger; Session-wide seq remains the total-order cursor
	ThreadID string
}

type File struct {
	ID             string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Filename       string
	MimeType       string
	SizeBytes      int64
	Downloadable   bool
	ScopeID        *string
	ScopeType      *string
	BlobKey        string
	ChecksumSha256 string
	State          string
	WorkspaceID    string
	OutputPath     *string
	InternalUse    bool
}

type McpDiscoverySnapshot struct {
	SessionID  string
	ServerName string
	ServerUrl  string
	Tools      []byte
	CreatedAt  pgtype.Timestamptz
	ThreadID   string
}

type Memory struct {
	ID               string
	MemoryStoreID    string
	MemoryVersionID  string
	Path             string
	Content          string
	ContentSizeBytes int64
	ContentSha256    string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type MemoryStore struct {
	ID          string
	Name        string
	Description string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
	WorkspaceID string
}

type MemoryVersion struct {
	ID               string
	MemoryStoreID    string
	MemoryID         string
	Operation        string
	Path             *string
	Content          *string
	ContentSizeBytes *int64
	ContentSha256    *string
	CreatedAt        pgtype.Timestamptz
	CreatedByType    string
	CreatedByID      string
	RedactedAt       pgtype.Timestamptz
	RedactedByType   *string
	RedactedByID     *string
}

type ModelRequestUsage struct {
	SessionID       string
	ThreadID        string
	RequestEventID  string
	ModelID         string
	StopReason      string
	Usage           []byte
	ListCostNanoUsd *int64
	CreatedAt       pgtype.Timestamptz
}

type OrchestrationOutbox struct {
	SessionID     string
	MaxEventSeq   int64
	EnqueuedAt    pgtype.Timestamptz
	Attempts      int32
	LastAttemptAt pgtype.Timestamptz
	LastError     *string
}

type PendingAction struct {
	ID                  string
	SessionID           string
	ActionEventID       string
	Kind                string
	ResolvingEventID    *string
	CreatedAt           pgtype.Timestamptz
	ResolvedAt          pgtype.Timestamptz
	ThreadID            string
	ClientActionEventID string
}

type ProviderTranscriptTurn struct {
	SessionID           string
	TriggerEventID      string
	TurnOrdinal         *int64
	CommittedThroughSeq int64
	RepresentedEventIds []byte
	Messages            []byte
	ToolUseMappings     []byte
	CreatedAt           pgtype.Timestamptz
}

type SandboxProvisioningIntent struct {
	SessionID string
	Provider  string
	Spec      []byte
	SpecHash  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID            string
	Status        string
	Body          []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	AgentID       *string
	AgentVersion  *int32
	EnvironmentID *string
	ArchivedAt    pgtype.Timestamptz
	DeletingAt    pgtype.Timestamptz
	DeploymentID  *string
	WorkspaceID   string
}

type SessionResource struct {
	ID                       string
	SessionID                string
	ResourceType             string
	SourceFileID             *string
	FileID                   *string
	MountPath                string
	State                    string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	MemoryStoreID            *string
	MemoryAccess             *string
	MemoryInstructions       *string
	MemoryStoreName          *string
	MemoryStoreDescription   *string
	RepositoryUrl            *string
	RepositoryCheckoutType   *string
	RepositoryCheckoutValue  *string
	RepositoryResolvedCommit *string
}

type SessionSandbox struct {
	SessionID  string
	Provider   string
	ExternalID string
	SpecHash   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type SessionSkillVersion struct {
	SessionID    string
	Position     int32
	SkillID      string
	SkillVersion string
	AgentID      string
	AgentVersion int32
}

type SessionThread struct {
	ID             string
	SessionID      string
	ParentThreadID *string
	// primary and persistent child Workflows, plus automatically terminating advisor consultations
	Kind      string
	CreatedAt pgtype.Timestamptz
	// Independent Thread archive time; primary archive currently follows Session archive
	ArchivedAt pgtype.Timestamptz
	Status     string
	// Authoritative per-Thread agent, usage, and timing projection
	Body      []byte
	UpdatedAt pgtype.Timestamptz
}

type SessionVault struct {
	SessionID string
	Position  int32
	VaultID   string
}

type Skill struct {
	ID                   string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DisplayTitle         string
	LatestVersion        *string
	Source               string
	DisplayTitleExplicit bool
	Ready                bool
	WorkspaceID          string
}

type SkillVersion struct {
	SkillID               string
	Version               string
	CreatedAt             pgtype.Timestamptz
	Description           string
	Directory             string
	Name                  string
	BlobKey               string
	SizeBytes             int64
	ChecksumSha256        string
	State                 string
	Initial               bool
	UncompressedSizeBytes int64
}

// Private immutable compacted message projections; never a public Session resource
type ThreadContextSnapshot struct {
	ID                        string
	SessionID                 string
	ThreadID                  string
	TriggerEventID            string
	ParentSnapshotID          *string
	SnapshotOrdinal           *int64
	TranscriptTriggerEventIds []byte
	Messages                  []byte
	Projection                []byte
	ContextPolicyVersion      int32
	CreatedAt                 pgtype.Timestamptz
}

type ThreadOrchestrationOutbox struct {
	SessionID     string
	ThreadID      string
	MaxEventSeq   int64
	EnqueuedAt    pgtype.Timestamptz
	Attempts      int32
	LastAttemptAt pgtype.Timestamptz
	LastError     *string
	Intent        string
}

type ToolStep struct {
	ID             string
	AttemptID      string
	Ordinal        int32
	ToolUseEventID string
	ToolName       string
	Input          []byte
	State          string
	Result         []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

type TurnAttempt struct {
	ID             string
	SessionID      string
	TriggerEventID string
	AttemptNo      int32
	State          string
	Error          *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

type Vault struct {
	ID          string
	DisplayName string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
	WorkspaceID string
}

type VaultCredential struct {
	ID               string
	VaultID          string
	DisplayName      *string
	Metadata         []byte
	AuthType         string
	CredentialKey    string
	PublicAuth       []byte
	SecretVersion    *int32
	SecretAlgorithm  *string
	SecretKeyID      *string
	SecretNonce      []byte
	SecretCiphertext []byte
	Version          int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
}

type Webhook struct {
	ID               string
	WorkspaceID      string
	Url              string
	EventTypes       []string
	Status           string
	DisabledReason   *string
	SecretVersion    int32
	SecretAlgorithm  string
	SecretKeyID      string
	SecretNonce      []byte
	SecretCiphertext []byte
	FailureStartedAt pgtype.Timestamptz
	LastSuccessAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type WebhookDelivery struct {
	WebhookID      string
	EventID        string
	State          string
	AttemptCount   int32
	NextAttemptAt  pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	ClaimID        *string
	LastAttemptAt  pgtype.Timestamptz
	DeliveredAt    pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	ResponseStatus *int32
	LastError      *string
	CreatedAt      pgtype.Timestamptz
}

type WebhookEvent struct {
	ID          string
	WorkspaceID string
	EventType   string
	ResourceID  string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

type Workspace struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
