// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveExternalPendingAction = `-- name: ApproveExternalPendingAction :execrows
UPDATE pending_actions
SET kind = 'tool_result', approval_event_id = $1
WHERE session_id = $2 AND id = $3
  AND kind = 'tool_confirmation'
  AND approval_event_id IS NULL
  AND resolving_event_id IS NULL AND resolved_at IS NULL
`

type ApproveExternalPendingActionParams struct {
	ApprovalEventID *string
	SessionID       string
	ID              string
}

func (q *Queries) ApproveExternalPendingAction(ctx context.Context, arg ApproveExternalPendingActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveExternalPendingAction, arg.ApprovalEventID, arg.SessionID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimPendingAction = `-- name: ClaimPendingAction :execrows
UPDATE pending_actions
SET resolving_event_id = $1
WHERE session_id = $2
  AND id = $3
  AND resolving_event_id IS NULL
  AND resolved_at IS NULL
`

type ClaimPendingActionParams struct {
	ResolvingEventID *string
	SessionID        string
	ID               string
}

func (q *Queries) ClaimPendingAction(ctx context.Context, arg ClaimPendingActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimPendingAction, arg.ResolvingEventID, arg.SessionID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingActionForUpdate = `-- name: GetPendingActionForUpdate :one
SELECT id, session_id, thread_id, action_event_id, client_action_event_id,
       kind, approval_event_id, resolving_event_id, created_at, resolved_at
FROM pending_actions
WHERE session_id = $1
  AND (
      action_event_id = $2
      OR client_action_event_id = $2
  )
FOR UPDATE
`

type GetPendingActionForUpdateParams struct {
	SessionID         string
	ReferencedEventID string
}

type GetPendingActionForUpdateRow struct {
	ID                  string
	SessionID           string
	ThreadID            string
	ActionEventID       string
	ClientActionEventID string
	Kind                string
	ApprovalEventID     *string
	ResolvingEventID    *string
	CreatedAt           pgtype.Timestamptz
	ResolvedAt          pgtype.Timestamptz
}

func (q *Queries) GetPendingActionForUpdate(ctx context.Context, arg GetPendingActionForUpdateParams) (GetPendingActionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPendingActionForUpdate, arg.SessionID, arg.ReferencedEventID)
	var i GetPendingActionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ThreadID,
		&i.ActionEventID,
		&i.ClientActionEventID,
		&i.Kind,
		&i.ApprovalEventID,
		&i.ResolvingEventID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const hasUnclaimedPendingActions = `-- name: HasUnclaimedPendingActions :one
SELECT EXISTS(
    SELECT 1
    FROM pending_actions
    WHERE session_id = $1
      AND thread_id = $2
      AND resolved_at IS NULL
      AND resolving_event_id IS NULL
) AS unclaimed
`

type HasUnclaimedPendingActionsParams struct {
	SessionID string
	ThreadID  string
}

func (q *Queries) HasUnclaimedPendingActions(ctx context.Context, arg HasUnclaimedPendingActionsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnclaimedPendingActions, arg.SessionID, arg.ThreadID)
	var unclaimed bool
	err := row.Scan(&unclaimed)
	return unclaimed, err
}

const hasUnresolvedPendingActions = `-- name: HasUnresolvedPendingActions :one
SELECT EXISTS(
    SELECT 1
    FROM pending_actions
    WHERE session_id = $1
      AND thread_id = $2
      AND resolved_at IS NULL
) AS unresolved
`

type HasUnresolvedPendingActionsParams struct {
	SessionID string
	ThreadID  string
}

func (q *Queries) HasUnresolvedPendingActions(ctx context.Context, arg HasUnresolvedPendingActionsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnresolvedPendingActions, arg.SessionID, arg.ThreadID)
	var unresolved bool
	err := row.Scan(&unresolved)
	return unresolved, err
}

const insertPendingAction = `-- name: InsertPendingAction :exec

INSERT INTO pending_actions (
    id, session_id, thread_id, action_event_id, client_action_event_id,
    kind, resolving_event_id, created_at, resolved_at
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, NULL, $7, NULL
)
`

type InsertPendingActionParams struct {
	ID                  string
	SessionID           string
	ThreadID            string
	ActionEventID       string
	ClientActionEventID string
	Kind                string
	CreatedAt           pgtype.Timestamptz
}

// Typed queries for durable client-action gates on the Temporal/PostgreSQL
// path. Callers hold the session row lock, so park, admission claim, and resume
// completion serialize with the public event ledger and session projection.
func (q *Queries) InsertPendingAction(ctx context.Context, arg InsertPendingActionParams) error {
	_, err := q.db.Exec(ctx, insertPendingAction,
		arg.ID,
		arg.SessionID,
		arg.ThreadID,
		arg.ActionEventID,
		arg.ClientActionEventID,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const isUnresolvedPendingResolution = `-- name: IsUnresolvedPendingResolution :one
SELECT EXISTS(
    SELECT 1
    FROM pending_actions
    WHERE session_id = $1
      AND thread_id = $2
      AND resolving_event_id = $3
      AND resolved_at IS NULL
) AS pending_resume
`

type IsUnresolvedPendingResolutionParams struct {
	SessionID        string
	ThreadID         string
	ResolvingEventID *string
}

// IsUnresolvedPendingResolution distinguishes a processed-on-receipt client
// result that still has to drive its resume turn from an already completed
// trigger. user.custom_tool_result carries processed_at at admission by public
// contract, so processed_at alone cannot be the turn-completion idempotency key.
func (q *Queries) IsUnresolvedPendingResolution(ctx context.Context, arg IsUnresolvedPendingResolutionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUnresolvedPendingResolution, arg.SessionID, arg.ThreadID, arg.ResolvingEventID)
	var pending_resume bool
	err := row.Scan(&pending_resume)
	return pending_resume, err
}

const listUnresolvedPendingActions = `-- name: ListUnresolvedPendingActions :many
SELECT id, session_id, thread_id, action_event_id, client_action_event_id,
       kind, approval_event_id, resolving_event_id, created_at, resolved_at
FROM pending_actions
WHERE session_id = $1
  AND thread_id = $2
  AND resolved_at IS NULL
ORDER BY created_at, id
`

type ListUnresolvedPendingActionsParams struct {
	SessionID string
	ThreadID  string
}

type ListUnresolvedPendingActionsRow struct {
	ID                  string
	SessionID           string
	ThreadID            string
	ActionEventID       string
	ClientActionEventID string
	Kind                string
	ApprovalEventID     *string
	ResolvingEventID    *string
	CreatedAt           pgtype.Timestamptz
	ResolvedAt          pgtype.Timestamptz
}

func (q *Queries) ListUnresolvedPendingActions(ctx context.Context, arg ListUnresolvedPendingActionsParams) ([]ListUnresolvedPendingActionsRow, error) {
	rows, err := q.db.Query(ctx, listUnresolvedPendingActions, arg.SessionID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnresolvedPendingActionsRow{}
	for rows.Next() {
		var i ListUnresolvedPendingActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ThreadID,
			&i.ActionEventID,
			&i.ClientActionEventID,
			&i.Kind,
			&i.ApprovalEventID,
			&i.ResolvingEventID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePendingActionsForEvents = `-- name: ResolvePendingActionsForEvents :execrows
UPDATE pending_actions
SET resolved_at = $1
WHERE session_id = $2
  AND thread_id = $3
  AND resolving_event_id = ANY($4::text[])
  AND resolved_at IS NULL
`

type ResolvePendingActionsForEventsParams struct {
	ResolvedAt        pgtype.Timestamptz
	SessionID         string
	ThreadID          string
	ResolvingEventIds []string
}

// ResolvePendingActionsForEvents closes one complete client-action barrier.
// The caller validates that the supplied ids exactly match every unresolved
// row before executing this update under the session lock.
func (q *Queries) ResolvePendingActionsForEvents(ctx context.Context, arg ResolvePendingActionsForEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolvePendingActionsForEvents,
		arg.ResolvedAt,
		arg.SessionID,
		arg.ThreadID,
		arg.ResolvingEventIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolvePendingActionsForTrigger = `-- name: ResolvePendingActionsForTrigger :execrows
UPDATE pending_actions
SET resolved_at = $1
WHERE session_id = $2
  AND resolving_event_id = $3
  AND resolved_at IS NULL
`

type ResolvePendingActionsForTriggerParams struct {
	ResolvedAt       pgtype.Timestamptz
	SessionID        string
	ResolvingEventID *string
}

func (q *Queries) ResolvePendingActionsForTrigger(ctx context.Context, arg ResolvePendingActionsForTriggerParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolvePendingActionsForTrigger, arg.ResolvedAt, arg.SessionID, arg.ResolvingEventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionPendingClientActionEventIDs = `-- name: SessionPendingClientActionEventIDs :many
SELECT client_action_event_id
FROM pending_actions
WHERE session_id = $1 AND resolved_at IS NULL
ORDER BY created_at, id
`

// SessionPendingClientActionEventIDs projects the unresolved action ids a
// client can answer from the primary stream. Child rows expose their cross-post
// ids; primary rows use the same id for both columns.
func (q *Queries) SessionPendingClientActionEventIDs(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.Query(ctx, sessionPendingClientActionEventIDs, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var client_action_event_id string
		if err := rows.Scan(&client_action_event_id); err != nil {
			return nil, err
		}
		items = append(items, client_action_event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
