// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnprocessedThreadMessages = `-- name: CountUnprocessedThreadMessages :one
SELECT COUNT(*)::int AS n
FROM events AS event
WHERE event.session_id = $1
  AND event.thread_id = $2
  AND event.type = 'agent.thread_message_received'
  AND event.processed_at IS NULL
  AND event.id <> $3
`

type CountUnprocessedThreadMessagesParams struct {
	SessionID string
	ThreadID  string
	ExcludeID string
}

func (q *Queries) CountUnprocessedThreadMessages(ctx context.Context, arg CountUnprocessedThreadMessagesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnprocessedThreadMessages, arg.SessionID, arg.ThreadID, arg.ExcludeID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countUnprocessedUserMessages = `-- name: CountUnprocessedUserMessages :one
SELECT COUNT(*)::int AS n
FROM events AS event
WHERE event.session_id = $1
  AND event.thread_id = (
      SELECT thread.id FROM session_threads AS thread
      WHERE thread.session_id = $1 AND thread.kind = 'primary'
  )
  AND event.type IN ('user.message', 'agent.thread_message_received')
  AND event.processed_at IS NULL
  AND event.id <> $2
`

type CountUnprocessedUserMessagesParams struct {
	SessionID string
	ExcludeID string
}

// CountUnprocessedUserMessages counts primary model triggers still awaiting a turn,
// excluding one id (the trigger just processed in the same transaction). It lets
// CompleteTurn decide whether this turn is the last: only then does the session
// go idle; otherwise it stays running with no intermediate idle event.
func (q *Queries) CountUnprocessedUserMessages(ctx context.Context, arg CountUnprocessedUserMessagesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnprocessedUserMessages, arg.SessionID, arg.ExcludeID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const deleteOutboxIfSeq = `-- name: DeleteOutboxIfSeq :execrows
DELETE FROM orchestration_outbox
WHERE session_id = $1 AND max_event_seq = $2
`

type DeleteOutboxIfSeqParams struct {
	SessionID   string
	MaxEventSeq int64
}

// DeleteOutboxIfSeq removes a delivered wakeup, but only if no later admission
// raised its sequence since it was read. A mismatch means new work coalesced
// into the row after the relay signaled, so the row is left for the next cycle
// and re-delivered with the higher sequence (a harmless duplicate wakeup).
func (q *Queries) DeleteOutboxIfSeq(ctx context.Context, arg DeleteOutboxIfSeqParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOutboxIfSeq, arg.SessionID, arg.MaxEventSeq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteThreadOutboxIfUnchanged = `-- name: DeleteThreadOutboxIfUnchanged :execrows
DELETE FROM thread_orchestration_outbox
WHERE session_id = $1
  AND thread_id = $2
  AND max_event_seq = $3
  AND intent = $4
`

type DeleteThreadOutboxIfUnchangedParams struct {
	SessionID   string
	ThreadID    string
	MaxEventSeq int64
	Intent      string
}

func (q *Queries) DeleteThreadOutboxIfUnchanged(ctx context.Context, arg DeleteThreadOutboxIfUnchangedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteThreadOutboxIfUnchanged,
		arg.SessionID,
		arg.ThreadID,
		arg.MaxEventSeq,
		arg.Intent,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueEnvironmentWork = `-- name: EnqueueEnvironmentWork :exec
INSERT INTO environment_work (
    id, environment_id, session_id, activation_seq, state, metadata, created_at
)
VALUES ($1, $2, $3, $4, 'queued', '{}'::jsonb, $5)
ON CONFLICT (session_id) WHERE state IN ('queued', 'starting', 'active') DO NOTHING
`

type EnqueueEnvironmentWorkParams struct {
	ID            string
	EnvironmentID string
	SessionID     string
	ActivationSeq int64
	CreatedAt     pgtype.Timestamptz
}

// EnqueueEnvironmentWork writes the self-hosted worker activation in the same
// transaction as event admission and the Temporal wakeup. The partial unique
// index coalesces admissions while a worker already owns the Session.
func (q *Queries) EnqueueEnvironmentWork(ctx context.Context, arg EnqueueEnvironmentWorkParams) error {
	_, err := q.db.Exec(ctx, enqueueEnvironmentWork,
		arg.ID,
		arg.EnvironmentID,
		arg.SessionID,
		arg.ActivationSeq,
		arg.CreatedAt,
	)
	return err
}

const enqueueWebhookEvent = `-- name: EnqueueWebhookEvent :exec
WITH subscribers AS (
    SELECT id
    FROM webhooks
    WHERE webhooks.workspace_id = $1
      AND webhooks.status = 'enabled'
      AND $2::text = ANY(webhooks.event_types)
    ORDER BY webhooks.id
    FOR UPDATE
), inserted_event AS (
    INSERT INTO webhook_events (
        id, workspace_id, event_type, resource_id, payload, created_at
    )
    SELECT $3, $1, $2,
           $4, $5, $6
    WHERE EXISTS (SELECT 1 FROM subscribers)
    RETURNING id, created_at
)
INSERT INTO webhook_deliveries (
    webhook_id, event_id, next_attempt_at, created_at
)
SELECT subscribers.id, inserted_event.id,
       inserted_event.created_at, inserted_event.created_at
FROM subscribers CROSS JOIN inserted_event
`

type EnqueueWebhookEventParams struct {
	WorkspaceID string
	EventType   string
	ID          string
	ResourceID  string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

// EnqueueWebhookEvent snapshots the enabled subscriptions in the same
// transaction as the source lifecycle change. No event row is retained when
// no endpoint is subscribed, and later subscriptions never backfill it.
func (q *Queries) EnqueueWebhookEvent(ctx context.Context, arg EnqueueWebhookEventParams) error {
	_, err := q.db.Exec(ctx, enqueueWebhookEvent,
		arg.WorkspaceID,
		arg.EventType,
		arg.ID,
		arg.ResourceID,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const firstUnprocessedInterruptAfter = `-- name: FirstUnprocessedInterruptAfter :one
SELECT event.id, event.session_id, event.seq, event.type, event.payload, event.turn_event_id, event.created_at, event.processed_at, event.thread_id
FROM events AS event
WHERE event.session_id = $1
  AND event.thread_id = (
      SELECT thread.id FROM session_threads AS thread
      WHERE thread.session_id = $1 AND thread.kind = 'primary'
  )
  AND event.seq > $2
  AND event.type = 'user.interrupt'
  AND event.processed_at IS NULL
ORDER BY event.seq
LIMIT 1
`

type FirstUnprocessedInterruptAfterParams struct {
	SessionID string
	AfterSeq  int64
}

// FirstUnprocessedInterruptAfter finds the earliest durable interrupt that can
// race the named turn. The caller holds the session row lock, so an empty result
// means turn completion linearized before any later interrupt admission.
func (q *Queries) FirstUnprocessedInterruptAfter(ctx context.Context, arg FirstUnprocessedInterruptAfterParams) (Event, error) {
	row := q.db.QueryRow(ctx, firstUnprocessedInterruptAfter, arg.SessionID, arg.AfterSeq)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.TurnEventID,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ThreadID,
	)
	return i, err
}

const firstUnprocessedThreadInterruptAfter = `-- name: FirstUnprocessedThreadInterruptAfter :one
SELECT event.id, event.session_id, event.seq, event.type, event.payload, event.turn_event_id, event.created_at, event.processed_at, event.thread_id
FROM events AS event
WHERE event.session_id = $1
  AND event.thread_id = $2
  AND event.seq > $3
  AND event.type = 'user.interrupt'
  AND event.processed_at IS NULL
ORDER BY event.seq
LIMIT 1
`

type FirstUnprocessedThreadInterruptAfterParams struct {
	SessionID string
	ThreadID  string
	AfterSeq  int64
}

// FirstUnprocessedThreadInterruptAfter is the child-Thread counterpart of the
// primary query above. Global interrupts are fanned out into each active child
// ledger during admission, so every Workflow owns an independently processable
// interrupt receipt.
func (q *Queries) FirstUnprocessedThreadInterruptAfter(ctx context.Context, arg FirstUnprocessedThreadInterruptAfterParams) (Event, error) {
	row := q.db.QueryRow(ctx, firstUnprocessedThreadInterruptAfter, arg.SessionID, arg.ThreadID, arg.AfterSeq)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.TurnEventID,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ThreadID,
	)
	return i, err
}

const flushQueuedThreadMessages = `-- name: FlushQueuedThreadMessages :exec
UPDATE events
SET processed_at = COALESCE(processed_at, $1)
WHERE session_id = $2
  AND thread_id = $3
  AND type = 'agent.thread_message_received'
  AND processed_at IS NULL
  AND id <> $4
`

type FlushQueuedThreadMessagesParams struct {
	ProcessedAt pgtype.Timestamptz
	SessionID   string
	ThreadID    string
	ExcludeID   string
}

// FlushQueuedThreadMessages stamps follow-up messages that must not execute
// after a child turn exhausts its retry budget.
func (q *Queries) FlushQueuedThreadMessages(ctx context.Context, arg FlushQueuedThreadMessagesParams) error {
	_, err := q.db.Exec(ctx, flushQueuedThreadMessages,
		arg.ProcessedAt,
		arg.SessionID,
		arg.ThreadID,
		arg.ExcludeID,
	)
	return err
}

const flushQueuedUserMessages = `-- name: FlushQueuedUserMessages :exec
WITH queued AS (
    SELECT queued_event.id,
           queued_event.payload->>'__companion_system_event_id' AS companion_id
    FROM events AS queued_event
    WHERE queued_event.session_id = $2
      AND queued_event.thread_id = (
          SELECT thread.id FROM session_threads AS thread
          WHERE thread.session_id = $2 AND thread.kind = 'primary'
      )
      AND queued_event.type IN ('user.message', 'agent.thread_message_received')
      AND queued_event.processed_at IS NULL
      AND queued_event.id <> $3
), flushed_ids AS (
    SELECT id FROM queued
    UNION
    SELECT companion_id FROM queued WHERE companion_id IS NOT NULL
)
UPDATE events AS target
SET processed_at = COALESCE(target.processed_at, $1)
WHERE target.session_id = $2
  AND target.id IN (SELECT id FROM flushed_ids)
`

type FlushQueuedUserMessagesParams struct {
	ProcessedAt pgtype.Timestamptz
	SessionID   string
	ExcludeID   string
}

// FlushQueuedUserMessages stamps every other queued user.message, plus its
// optional companion system.message, when the active turn exhausts its retry
// budget. The events remain in the ledger but can no longer start model work.
func (q *Queries) FlushQueuedUserMessages(ctx context.Context, arg FlushQueuedUserMessagesParams) error {
	_, err := q.db.Exec(ctx, flushQueuedUserMessages, arg.ProcessedAt, arg.SessionID, arg.ExcludeID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT events.id, events.session_id, events.seq, events.type, events.payload, events.turn_event_id, events.created_at, events.processed_at, events.thread_id
FROM events
WHERE session_id = $1 AND id = $2
`

type GetEventParams struct {
	SessionID string
	ID        string
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.SessionID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.TurnEventID,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ThreadID,
	)
	return i, err
}

const getOutbox = `-- name: GetOutbox :one
SELECT session_id, max_event_seq, enqueued_at, attempts, last_attempt_at, last_error
FROM orchestration_outbox
WHERE session_id = $1
`

func (q *Queries) GetOutbox(ctx context.Context, sessionID string) (OrchestrationOutbox, error) {
	row := q.db.QueryRow(ctx, getOutbox, sessionID)
	var i OrchestrationOutbox
	err := row.Scan(
		&i.SessionID,
		&i.MaxEventSeq,
		&i.EnqueuedAt,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.LastError,
	)
	return i, err
}

const getPrimarySessionThreadID = `-- name: GetPrimarySessionThreadID :one
SELECT id
FROM session_threads
WHERE session_id = $1 AND kind = 'primary'
`

func (q *Queries) GetPrimarySessionThreadID(ctx context.Context, sessionID string) (string, error) {
	row := q.db.QueryRow(ctx, getPrimarySessionThreadID, sessionID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getPrimarySessionThreadProjection = `-- name: GetPrimarySessionThreadProjection :one
SELECT body
FROM session_threads
WHERE session_id = $1 AND kind = 'primary'
`

// The primary Thread has an independent projection even while the current
// single-thread runtime updates it alongside the Session aggregate.
func (q *Queries) GetPrimarySessionThreadProjection(ctx context.Context, sessionID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPrimarySessionThreadProjection, sessionID)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const getSession = `-- name: GetSession :one
SELECT id, status, body, created_at, updated_at, workspace_id
FROM sessions
WHERE id = $1
`

type GetSessionRow struct {
	ID          string
	Status      string
	Body        []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	WorkspaceID string
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getSessionWorkspaceID = `-- name: GetSessionWorkspaceID :one
SELECT workspace_id FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSessionWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const hasActiveChildThreads = `-- name: HasActiveChildThreads :one
SELECT EXISTS(
    SELECT 1
    FROM session_threads
    WHERE session_id = $1
      AND kind = 'child'
      AND archived_at IS NULL
      AND status IN ('running', 'rescheduling')
) AS active
`

// HasActiveChildThreads lets primary completion preserve the aggregate Session
// running state while one or more independently executing children are active.
func (q *Queries) HasActiveChildThreads(ctx context.Context, sessionID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveChildThreads, sessionID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id, session_id, thread_id, seq, type, payload,
    turn_event_id, created_at, processed_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
`

type InsertEventParams struct {
	ID          string
	SessionID   string
	ThreadID    string
	Seq         int64
	Type        string
	Payload     []byte
	TurnEventID *string
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.SessionID,
		arg.ThreadID,
		arg.Seq,
		arg.Type,
		arg.Payload,
		arg.TurnEventID,
		arg.CreatedAt,
		arg.ProcessedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO sessions (
    id, status, body, created_at, updated_at,
    agent_id, agent_version, environment_id, deployment_id, archived_at,
    workspace_id
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11
)
`

type InsertSessionParams struct {
	ID            string
	Status        string
	Body          []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	AgentID       *string
	AgentVersion  *int32
	EnvironmentID *string
	DeploymentID  *string
	ArchivedAt    pgtype.Timestamptz
	WorkspaceID   string
}

// Typed queries for the Temporal/PostgreSQL session path, compiled by sqlc into
// internal/pg/pgstore. Transactions are kept explicit in Go; these are the
// individual statements the admission, completion, cursor, and relay operations
// compose under a single tx.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.Status,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AgentID,
		arg.AgentVersion,
		arg.EnvironmentID,
		arg.DeploymentID,
		arg.ArchivedAt,
		arg.WorkspaceID,
	)
	return err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT event.id, event.session_id, event.seq, event.type, event.payload, event.turn_event_id, event.created_at, event.processed_at, event.thread_id
FROM events AS event
WHERE event.session_id = $1
  AND event.thread_id = (
      SELECT thread.id FROM session_threads AS thread
      WHERE thread.session_id = $1 AND thread.kind = 'primary'
  )
  AND event.seq > $2
ORDER BY event.seq
LIMIT $3
`

type ListEventsAfterParams struct {
	SessionID string
	AfterSeq  int64
	RowLimit  int32
}

// ListEventsAfter returns events with seq strictly greater than a cursor, in
// ascending receipt order. This is how the SessionWorkflow consumes the ledger
// after its durable cursor; the limit bounds one wakeup's batch.
func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.SessionID, arg.AfterSeq, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.TurnEventID,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTurn = `-- name: ListEventsByTurn :many
SELECT events.id, events.session_id, events.seq, events.type, events.payload, events.turn_event_id, events.created_at, events.processed_at, events.thread_id
FROM events
WHERE session_id = $1 AND turn_event_id = $2
ORDER BY seq
`

type ListEventsByTurnParams struct {
	SessionID   string
	TurnEventID *string
}

// ListEventsByTurn returns the output events a completed turn committed,
// identified by the trigger event id that caused them, in receipt order. The
// idempotent completion path replays these when a turn is already processed.
func (q *Queries) ListEventsByTurn(ctx context.Context, arg ListEventsByTurnParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByTurn, arg.SessionID, arg.TurnEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.TurnEventID,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrchestrationWakeups = `-- name: ListOrchestrationWakeups :many
SELECT session_id, ''::text AS thread_id, max_event_seq, enqueued_at, attempts,
       'wake'::text AS intent
FROM orchestration_outbox
UNION ALL
SELECT session_id, thread_id, max_event_seq, enqueued_at, attempts, intent
FROM thread_orchestration_outbox
ORDER BY enqueued_at
LIMIT $1
`

type ListOrchestrationWakeupsRow struct {
	SessionID   string
	ThreadID    string
	MaxEventSeq int64
	EnqueuedAt  pgtype.Timestamptz
	Attempts    int32
	Intent      string
}

// ListOrchestrationWakeups merges primary and child delivery queues without
// changing either queue's idempotency key.
func (q *Queries) ListOrchestrationWakeups(ctx context.Context, rowLimit int32) ([]ListOrchestrationWakeupsRow, error) {
	rows, err := q.db.Query(ctx, listOrchestrationWakeups, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrchestrationWakeupsRow{}
	for rows.Next() {
		var i ListOrchestrationWakeupsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ThreadID,
			&i.MaxEventSeq,
			&i.EnqueuedAt,
			&i.Attempts,
			&i.Intent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxBatch = `-- name: ListOutboxBatch :many
SELECT session_id, max_event_seq, enqueued_at, attempts, last_attempt_at, last_error
FROM orchestration_outbox
ORDER BY enqueued_at
LIMIT $1
`

// ListOutboxBatch reads the oldest pending wakeups for delivery, oldest first.
// This is a plain read, not a lease/claim: delivery to Temporal happens outside
// any transaction, so two relay instances can read the same row and both send a
// Signal. That is deliberately harmless — delivery is at-least-once and the
// SessionWorkflow deduplicates by receipt sequence (a wakeup at or below its
// cursor is a no-op). A delivered row is removed only by DeleteOutboxIfSeq, which
// is itself guarded by the sequence.
func (q *Queries) ListOutboxBatch(ctx context.Context, rowLimit int32) ([]OrchestrationOutbox, error) {
	rows, err := q.db.Query(ctx, listOutboxBatch, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrchestrationOutbox{}
	for rows.Next() {
		var i OrchestrationOutbox
		if err := rows.Scan(
			&i.SessionID,
			&i.MaxEventSeq,
			&i.EnqueuedAt,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSession = `-- name: LockSession :one
SELECT id, status, body, created_at, updated_at, deleting_at, workspace_id
FROM sessions
WHERE id = $1
FOR UPDATE
`

type LockSessionRow struct {
	ID          string
	Status      string
	Body        []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletingAt  pgtype.Timestamptz
	WorkspaceID string
}

// LockSession takes the per-session admission lock. Every admission and
// completion for a session serializes on this row, which is what makes receipt
// sequence assignment and the coalescing outbox upsert race-free.
func (q *Queries) LockSession(ctx context.Context, id string) (LockSessionRow, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	var i LockSessionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletingAt,
		&i.WorkspaceID,
	)
	return i, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE events
SET processed_at = COALESCE(processed_at, $1)
WHERE session_id = $2 AND id = $3
`

type MarkEventProcessedParams struct {
	ProcessedAt pgtype.Timestamptz
	SessionID   string
	ID          string
}

// MarkEventProcessed stamps a trigger event processed, but only once
// (COALESCE keeps the first timestamp). Returns the row so the caller can tell a
// first processing from a repeat.
func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.ProcessedAt, arg.SessionID, arg.ID)
	return err
}

const markOutboxAttempt = `-- name: MarkOutboxAttempt :exec
UPDATE orchestration_outbox
SET attempts = attempts + 1, last_attempt_at = $1, last_error = $2
WHERE session_id = $3
`

type MarkOutboxAttemptParams struct {
	LastAttemptAt pgtype.Timestamptz
	LastError     *string
	SessionID     string
}

// MarkOutboxAttempt records a failed delivery attempt for backoff and
// observability without removing the wakeup.
func (q *Queries) MarkOutboxAttempt(ctx context.Context, arg MarkOutboxAttemptParams) error {
	_, err := q.db.Exec(ctx, markOutboxAttempt, arg.LastAttemptAt, arg.LastError, arg.SessionID)
	return err
}

const markThreadOutboxAttempt = `-- name: MarkThreadOutboxAttempt :exec
UPDATE thread_orchestration_outbox
SET attempts = attempts + 1,
    last_attempt_at = $1,
    last_error = $2
WHERE session_id = $3 AND thread_id = $4
`

type MarkThreadOutboxAttemptParams struct {
	LastAttemptAt pgtype.Timestamptz
	LastError     *string
	SessionID     string
	ThreadID      string
}

func (q *Queries) MarkThreadOutboxAttempt(ctx context.Context, arg MarkThreadOutboxAttemptParams) error {
	_, err := q.db.Exec(ctx, markThreadOutboxAttempt,
		arg.LastAttemptAt,
		arg.LastError,
		arg.SessionID,
		arg.ThreadID,
	)
	return err
}

const maxEventSeq = `-- name: MaxEventSeq :one
SELECT COALESCE(MAX(seq), 0)::bigint AS max_seq
FROM events
WHERE session_id = $1
`

// MaxEventSeq returns the current highest receipt sequence for a session, or 0
// when the session has no events yet. Called while holding the admission lock.
func (q *Queries) MaxEventSeq(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, maxEventSeq, sessionID)
	var max_seq int64
	err := row.Scan(&max_seq)
	return max_seq, err
}

const priorProcessedModelTriggers = `-- name: PriorProcessedModelTriggers :many
SELECT event.id, event.session_id, event.seq, event.type, event.payload, event.turn_event_id, event.created_at, event.processed_at, event.thread_id
FROM events AS event
WHERE event.session_id = $1
  AND event.thread_id = (
      SELECT thread.id FROM session_threads AS thread
      WHERE thread.session_id = $1 AND thread.kind = 'primary'
  )
  AND event.type IN ('user.message', 'user.custom_tool_result', 'user.tool_confirmation')
  AND event.processed_at IS NOT NULL
  AND event.seq < $2
ORDER BY event.seq
`

type PriorProcessedModelTriggersParams struct {
	SessionID string
	BeforeSeq int64
}

// PriorProcessedModelTriggers returns processed events that can drive a model
// turn before a given sequence, in receipt order. Resolution events are included
// because a completed custom-tool/confirmation resume may itself have committed
// model output that later turns must replay.
func (q *Queries) PriorProcessedModelTriggers(ctx context.Context, arg PriorProcessedModelTriggersParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, priorProcessedModelTriggers, arg.SessionID, arg.BeforeSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.TurnEventID,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrimarySessionThreadProjection = `-- name: UpdatePrimarySessionThreadProjection :exec
UPDATE session_threads
SET status = $1,
    body = $2,
    updated_at = $3,
    archived_at = $4
WHERE session_id = $5 AND kind = 'primary'
`

type UpdatePrimarySessionThreadProjectionParams struct {
	Status     string
	Body       []byte
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
	SessionID  string
}

func (q *Queries) UpdatePrimarySessionThreadProjection(ctx context.Context, arg UpdatePrimarySessionThreadProjectionParams) error {
	_, err := q.db.Exec(ctx, updatePrimarySessionThreadProjection,
		arg.Status,
		arg.Body,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.SessionID,
	)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET status = $1, body = $2, updated_at = $3
WHERE id = $4
`

type UpdateSessionStatusParams struct {
	Status    string
	Body      []byte
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus,
		arg.Status,
		arg.Body,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertOutbox = `-- name: UpsertOutbox :exec
INSERT INTO orchestration_outbox (session_id, max_event_seq, enqueued_at)
VALUES ($1, $2, $3)
ON CONFLICT (session_id) DO UPDATE
SET max_event_seq = GREATEST(orchestration_outbox.max_event_seq, EXCLUDED.max_event_seq),
    enqueued_at   = EXCLUDED.enqueued_at
`

type UpsertOutboxParams struct {
	SessionID   string
	MaxEventSeq int64
	EnqueuedAt  pgtype.Timestamptz
}

// UpsertOutbox writes or coalesces the pending wakeup for a session. When a
// wakeup is already pending, it keeps the newer enqueue time and raises
// max_event_seq to the highest known receipt sequence rather than adding a row.
func (q *Queries) UpsertOutbox(ctx context.Context, arg UpsertOutboxParams) error {
	_, err := q.db.Exec(ctx, upsertOutbox, arg.SessionID, arg.MaxEventSeq, arg.EnqueuedAt)
	return err
}

const upsertThreadOutbox = `-- name: UpsertThreadOutbox :exec
INSERT INTO thread_orchestration_outbox (
    session_id, thread_id, max_event_seq, enqueued_at, intent
)
VALUES ($1, $2, $3, $4, 'wake')
ON CONFLICT (session_id, thread_id) DO UPDATE
SET max_event_seq = GREATEST(
        thread_orchestration_outbox.max_event_seq,
        EXCLUDED.max_event_seq
    ),
    enqueued_at = EXCLUDED.enqueued_at,
    intent = CASE
        WHEN thread_orchestration_outbox.intent = 'terminate' THEN 'terminate'
        ELSE EXCLUDED.intent
    END
`

type UpsertThreadOutboxParams struct {
	SessionID   string
	ThreadID    string
	MaxEventSeq int64
	EnqueuedAt  pgtype.Timestamptz
}

// UpsertThreadOutbox is the independent coalescible wakeup for one child
// Thread Workflow. Session-wide sequence numbers still preserve causal order.
func (q *Queries) UpsertThreadOutbox(ctx context.Context, arg UpsertThreadOutboxParams) error {
	_, err := q.db.Exec(ctx, upsertThreadOutbox,
		arg.SessionID,
		arg.ThreadID,
		arg.MaxEventSeq,
		arg.EnqueuedAt,
	)
	return err
}

const upsertThreadTermination = `-- name: UpsertThreadTermination :exec
INSERT INTO thread_orchestration_outbox (
    session_id, thread_id, max_event_seq, enqueued_at, intent
)
VALUES ($1, $2, $3, $4, 'terminate')
ON CONFLICT (session_id, thread_id) DO UPDATE
SET max_event_seq = GREATEST(
        thread_orchestration_outbox.max_event_seq,
        EXCLUDED.max_event_seq
    ),
    enqueued_at = EXCLUDED.enqueued_at,
    intent = 'terminate'
`

type UpsertThreadTerminationParams struct {
	SessionID   string
	ThreadID    string
	MaxEventSeq int64
	EnqueuedAt  pgtype.Timestamptz
}

// UpsertThreadTermination permanently upgrades one child orchestration key to
// shutdown. A later stale wake may raise the observed sequence but cannot
// downgrade the intent.
func (q *Queries) UpsertThreadTermination(ctx context.Context, arg UpsertThreadTerminationParams) error {
	_, err := q.db.Exec(ctx, upsertThreadTermination,
		arg.SessionID,
		arg.ThreadID,
		arg.MaxEventSeq,
		arg.EnqueuedAt,
	)
	return err
}
