#!/usr/bin/env python3
"""Generate the full typed client from Mango's shared, JSON OpenAPI snapshot.

This generator uses only the Python standard library. ``--check`` is read-only.
The transport is handwritten; schema and operation coverage are generated.
"""

from __future__ import annotations

import argparse
import json
import keyword
import pprint
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
SHARED = ROOT.parent
PACKAGE = ROOT / "src" / "mango_sdk"
HEADER = '# Generated by sdk/python/generate.py; do not edit.\n# ruff: noqa: F401\n'


def snake(name: str) -> str:
    name = name.replace("MCPOAuth", "McpOauth")
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    name = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()
    return name + "_" if keyword.iskeyword(name) else name


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^a-zA-Z0-9]", name) if part)


class Generator:
    def __init__(self, spec: dict[str, Any], operations: list[dict[str, Any]]) -> None:
        self.spec = spec
        self.schemas = dict(spec["components"]["schemas"])
        self.operations = operations

    def resolve(self, value: dict[str, Any]) -> dict[str, Any]:
        if "$ref" not in value:
            return value
        current: Any = self.spec
        for part in value["$ref"].removeprefix("#/").split("/"):
            current = current[part.replace("~1", "/").replace("~0", "~")]
        return current

    def flatten(self, schema: dict[str, Any]) -> dict[str, Any]:
        if "allOf" not in schema:
            return schema
        result: dict[str, Any] = {"type": "object", "properties": {}, "required": []}
        for part in schema["allOf"]:
            child = self.flatten(self.resolve(part))
            if child.get("type") not in (None, "object"):
                raise ValueError("Non-object allOf requires an explicit generator implementation")
            result["properties"].update(child.get("properties", {}))
            result["required"].extend(child.get("required", []))
        result["properties"].update(schema.get("properties", {}))
        result["required"].extend(schema.get("required", []))
        return result

    def named(self, schema: dict[str, Any], name: str) -> str:
        if "$ref" in schema:
            return schema["$ref"].rsplit("/", 1)[1]
        if name in self.schemas and self.schemas[name] != schema:
            raise ValueError(f"Generated type name collision: {name}")
        self.schemas[name] = schema
        return name

    def expression(self, schema: dict[str, Any], context: str, inline: bool = False) -> str:
        if "$ref" in schema:
            return repr(schema["$ref"].rsplit("/", 1)[1])
        schema = self.flatten(schema)
        if "const" in schema:
            return f"Literal[{schema['const']!r}]" if schema["const"] is not None else "None"
        if "enum" in schema:
            return "Literal[" + ", ".join(repr(item) for item in schema["enum"]) + "]"
        for union in ("oneOf", "anyOf"):
            if union in schema:
                items = [
                    self.expression(part, context + "Variant" + str(index + 1))
                    for index, part in enumerate(schema[union])
                ]
                return "Union[" + ", ".join(items) + "]"
        kind = schema.get("type")
        if isinstance(kind, list):
            return "Union[" + ", ".join(
                self.expression({**schema, "type": item}, context + pascal(item)) for item in kind
            ) + "]"
        if kind == "array":
            return "List[" + self.expression(schema.get("items", {}), context + "Item") + "]"
        if kind == "object" or "properties" in schema:
            # Python 3.11 TypedDict cannot describe arbitrary extra keys. JSON
            # Schemas (notably custom-tool input_schema) must remain open maps,
            # otherwise legal properties/required/$defs are rejected by mypy.
            if schema.get("additionalProperties") is True:
                return "Dict[str, Any]"
            if schema.get("properties"):
                if inline:
                    raise ValueError("TypedDict objects are emitted as declarations")
                return repr(self.named(schema, context))
            additional = schema.get("additionalProperties", {})
            value = self.expression(additional, context + "Value") if isinstance(additional, dict) else "Any"
            return "Dict[str, " + value + "]"
        if kind == "string" and schema.get("format") == "binary":
            return "Upload"
        return {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "null": "None"}.get(kind, "Any")

    def model_source(self) -> str:
        lines = [HEADER, '"""All Mango OpenAPI schemas, including request and tagged-union event types.\n\n'
                 'TypedDict preserves wire dictionaries: omitted keys and explicit None differ.\n'
                 'These are static types, not runtime validators; the server validates requests.\n"""\n',
                 "from __future__ import annotations\n\n",
                 "from typing import Any, Dict, List, Literal, Required, TypeAlias, TypedDict, Union\n",
                 "from ._types import Upload\n\n"]
        done: set[str] = set()
        while len(done) < len(self.schemas):
            for name in list(self.schemas):
                if name in done:
                    continue
                done.add(name)
                original = self.schemas[name]
                schema = self.flatten(original)
                if (schema.get("properties") and schema.get("additionalProperties") is not True
                        and not any(key in schema for key in ("oneOf", "anyOf"))):
                    lines.append(f"class {name}(TypedDict, total=False):\n")
                    required = set(schema.get("required", []))
                    for field, value in schema["properties"].items():
                        if not field.isidentifier() or keyword.iskeyword(field):
                            raise ValueError(f"Nonidentifier TypedDict field: {name}.{field}")
                        annotation = self.expression(value, name + pascal(field))
                        if field in required:
                            annotation = "Required[" + annotation + "]"
                        lines.append(f"    {field}: {annotation}\n")
                    lines.append("\n\n")
                else:
                    lines.append(f"{name}: TypeAlias = {self.expression(schema, name, inline=True)}\n\n\n")
        lines.append("__all__ = " + pprint.pformat(sorted(done), width=100) + "\n")
        return "".join(lines)

    def prepare(self) -> list[dict[str, Any]]:
        output = []
        for operation in self.operations:
            item = dict(operation)
            item["name"] = snake(item["id"])
            context = pascal(item["id"])
            parameters = []
            for parameter in item.get("parameters") or []:
                parameter = dict(parameter)
                parameter["pyname"] = snake(parameter["name"])
                name = self.named(parameter.get("schema", {}), context + pascal(parameter["pyname"]) + "Parameter")
                parameter["annotation"] = "models." + name
                parameters.append(parameter)
            item["parameters"] = parameters
            request_schema = item["request_schema"]
            if request_schema is not None:
                item["body_type"] = "models." + self.named(request_schema, context + "RequestBody")
            response_schema = item["response_schema"]
            accept = item["response_content_type"]
            mode = "json"
            response = "None"
            if accept == "text/event-stream":
                mode = "sse"
            elif response_schema is None:
                mode = "empty"
            elif response_schema.get("format") == "binary":
                mode = "binary"
            elif accept != "application/json":
                mode = "text"
                response = "str"
            else:
                response = "models." + self.named(response_schema, context + "Response")
            item["response_type"] = response
            item["metadata"] = {
                "id": item["id"], "method": item["method"], "path": item["path"],
                "mode": mode, "public": item["public"], "accept": accept or "*/*",
                "request": "multipart" if item["request_content_type"] == "multipart/form-data" else "json",
            }
            resolved = self.flatten(self.resolve(response_schema)) if response_schema else {}
            props = resolved.get("properties", {})
            if "data" in props and ("next_page" in props or "has_more" in props):
                data = self.resolve(props["data"])
                item["item_type"] = "models." + self.named(data["items"], context + "Item")
            output.append(item)
        return output

    def client_source(self, operations: list[dict[str, Any]]) -> str:
        lines = [HEADER, '"""One named operation per Mango route; sync and async share the same contract."""\n',
                 "from __future__ import annotations\n\n",
                 "from typing import Any, AsyncIterator, Iterator, cast\n",
                 "from . import models\n",
                 "from ._client import BaseClient, AsyncBaseClient\n",
                 "from ._streaming import BinaryStream, AsyncBinaryStream, SSEStream, AsyncSSEStream\n",
                 "from ._types import NOT_GIVEN, NotGiven\n\n",
                 "OPERATIONS: dict[str, dict[str, Any]] = " + pprint.pformat({item["name"]: item["metadata"] for item in operations}, sort_dicts=False, width=100) + "\n\n\n"]
        for async_mode in (False, True):
            client = "AsyncMango" if async_mode else "Mango"
            parent = "AsyncBaseClient" if async_mode else "BaseClient"
            lines.append(f"class {client}({parent}):\n")
            enter = "    async def __aenter__(self)" if async_mode else "    def __enter__(self)"
            lines.append(f"{enter} -> {client}:\n        return self\n\n")
            for item in operations:
                variants = [False, True] if "item_type" in item else [False]
                for pagination in variants:
                    name = item["name"]
                    method_name = ("iter_" + name.removeprefix("list_")) if pagination else name
                    parameters = ["self"]
                    path: dict[str, str] = {}
                    query: dict[str, str] = {}
                    for parameter in item["parameters"]:
                        if parameter["in"] != "path":
                            continue
                        pyname = parameter["pyname"]
                        parameters.append(f"{pyname}: {parameter['annotation']}")
                        path[parameter["name"]] = pyname
                    optional = [parameter for parameter in item["parameters"] if parameter["in"] == "query"]
                    if optional or "body_type" in item:
                        parameters.append("*")
                    if "body_type" in item:
                        suffix = "" if item["request_required"] else " | NotGiven = NOT_GIVEN"
                        parameters.append(f"body: {item['body_type']}" + suffix)
                    for parameter in optional:
                        pyname = parameter["pyname"]
                        suffix = "" if parameter.get("required") else " | NotGiven = NOT_GIVEN"
                        parameters.append(f"{pyname}: {parameter['annotation']}" + suffix)
                        query[parameter["name"]] = pyname
                    mode = item["metadata"]["mode"]
                    prefix = "async " if async_mode and mode not in ("sse", "binary") and not pagination else ""
                    return_type = item["response_type"]
                    if pagination:
                        return_type = ("AsyncIterator" if async_mode else "Iterator") + "[" + item["item_type"] + "]"
                    elif mode in ("sse", "binary"):
                        return_type = ("Async" if async_mode else "") + ("SSEStream" if mode == "sse" else "BinaryStream")
                    lines.append(f"    {prefix}def {method_name}(\n        " + ",\n        ".join(parameters) + f",\n    ) -> {return_type}:\n")
                    lines.append(f'        """{item["method"]} {item["path"]}' + ("; iterate every page." if pagination else ".") + '"""\n')
                    path_expr = "{" + ", ".join(repr(key) + ": " + value for key, value in path.items()) + "}"
                    query_expr = "{" + ", ".join(repr(key) + ": " + value for key, value in query.items()) + "}"
                    arguments = f"OPERATIONS[{name!r}], {path_expr}, {query_expr}"
                    if pagination:
                        lines.append(f"        return cast({return_type}, self._paginate({arguments}))\n\n")
                    elif mode in ("sse", "binary"):
                        helper = "_stream" if mode == "sse" else "_binary"
                        lines.append(f"        return self.{helper}({arguments})\n\n")
                    else:
                        if "body_type" in item:
                            arguments += ", body"
                        awaited = "await " if async_mode else ""
                        lines.append(f"        return cast({return_type}, {awaited}self._request({arguments}))\n\n")
        return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads((SHARED / "openapi.json").read_text())
    manifest = json.loads((SHARED / "operations.json").read_text())
    generator = Generator(spec, manifest["operations"])
    prepared = generator.prepare()
    client = generator.client_source(prepared)
    models = generator.model_source()
    stale = []
    for filename, source in {"models.py": models, "_generated.py": client}.items():
        source = source.rstrip() + "\n"
        path = PACKAGE / filename
        if args.check:
            if not path.exists() or path.read_text() != source:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(source)
    if stale:
        print("Stale Python SDK bindings: " + ", ".join(stale), file=sys.stderr)
        return 1
    print(f"Python SDK: {len(prepared)} operations, {len(spec['components']['schemas'])} component schemas; " + ("checked" if args.check else "generated"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
