# Generated by sdk/python/generate.py; do not edit.
# ruff: noqa: F401
"""All Mango OpenAPI schemas, including request and tagged-union event types.

TypedDict preserves wire dictionaries: omitted keys and explicit None differ.
These are static types, not runtime validators; the server validates requests.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Required, TypeAlias, TypedDict, Union
from ._types import Upload

class Agent(TypedDict, total=False):
    archived_at: Required['NullableTimestamp']
    created_at: Required[str]
    description: Required[Union[str, None]]
    id: Required[str]
    mcp_servers: Required[List['MCPServer']]
    metadata: Required['Metadata']
    model: Required['Model']
    multiagent: Required['Multiagent']
    name: Required[str]
    skills: Required[List['SkillReferenceResponse']]
    system: Required[Union[str, None]]
    tools: Required[List['AgentTool']]
    type: Required[Literal['agent']]
    updated_at: Required[str]
    version: Required[int]


class AgentCreateRequest(TypedDict, total=False):
    description: Union[str, None]
    mcp_servers: List['MCPServer']
    metadata: 'Metadata'
    model: Required['ModelInput']
    multiagent: 'MultiagentInput'
    name: Required[str]
    skills: List['SkillReferenceInput']
    system: Union[str, None]
    tools: List['AgentTool']


class AgentCustomToolUseEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.custom_tool_use']]
    input: Required[Dict[str, Any]]
    name: Required[str]
    session_thread_id: str


class AgentList(TypedDict, total=False):
    data: Required[List['Agent']]
    next_page: Required['Cursor']


class AgentMCPToolResultEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.mcp_tool_result']]
    content: List['ResultContentInput']
    is_error: bool
    mcp_tool_use_id: Required[str]


class AgentMCPToolUseEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.mcp_tool_use']]
    evaluated_permission: 'EvaluatedPermission'
    input: Required[Dict[str, Any]]
    mcp_server_name: Required[str]
    name: Required[str]
    session_thread_id: str


class AgentMessageEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.message']]
    content: Required[List['TextBlockInput']]


class AgentReference(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['agent']]
    version: int


class AgentSnapshot(TypedDict, total=False):
    description: Required[str]
    id: Required[str]
    mcp_servers: Required[List['MCPServer']]
    model: Required['Model']
    multiagent: Required['SessionMultiagent']
    name: Required[str]
    skills: Required[List['SkillReferenceResponse']]
    system: Required[str]
    tools: Required[List['AgentTool']]
    type: Required[Literal['agent']]
    version: Required[int]


class AgentThinkingEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.thinking']]


class AgentThreadContextCompactedEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.thread_context_compacted']]


class AgentThreadMessageReceivedEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.thread_message_received']]
    content: Required[List['MessageContentInput']]
    from_agent_name: Required[str]
    from_session_thread_id: Required[str]


class AgentThreadMessageSentEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.thread_message_sent']]
    content: Required[List['MessageContentInput']]
    to_agent_name: Required[str]
    to_session_thread_id: Required[str]


AgentTool: TypeAlias = Union['BuiltinToolset', 'MCPToolset', 'CustomTool']


class AgentToolResultEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.tool_result']]
    content: List['ResultContentInput']
    is_error: bool
    tool_use_id: Required[str]


class AgentToolUseEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['agent.tool_use']]
    evaluated_permission: 'EvaluatedPermission'
    input: Required[Dict[str, Any]]
    name: Required[str]
    session_thread_id: str


class AgentUpdateRequest(TypedDict, total=False):
    description: Union[str, None]
    mcp_servers: Union[List['MCPServer'], None]
    metadata: 'MetadataPatch'
    model: 'ModelInput'
    multiagent: 'MultiagentInput'
    name: str
    skills: Union[List['SkillReferenceInput'], None]
    system: Union[str, None]
    tools: Union[List['AgentTool'], None]
    version: int


class AgentWithOverrides(TypedDict, total=False):
    id: Required[str]
    mcp_servers: Union[List['MCPServer'], None]
    model: 'ModelInput'
    skills: Union[List['SkillReferenceInput'], None]
    system: Union[str, None]
    tools: Union[List['AgentTool'], None]
    type: Required[Literal['agent_with_overrides']]
    version: int


class AnthropicSkillReferenceInput(TypedDict, total=False):
    skill_id: Required[str]
    type: Required[Literal['anthropic']]
    version: str


class Base64DocumentSourceInput(TypedDict, total=False):
    data: Required[str]
    media_type: Required[str]
    type: Required[Literal['base64']]


class Base64ImageSourceInput(TypedDict, total=False):
    data: Required[str]
    media_type: Required[str]
    type: Required[Literal['base64']]


class BuiltinToolset(TypedDict, total=False):
    configs: List['BuiltinToolsetConfigsItem']
    default_config: 'ToolDefaultConfig'
    type: Required[Literal['agent_toolset_20260401']]


ClientPersistedSessionEvent: TypeAlias = Union['PersistedUserMessageEvent', 'PersistedUserInterruptEvent', 'PersistedUserToolConfirmationEvent', 'PersistedUserCustomToolResultEvent', 'PersistedUserDefineOutcomeEvent', 'PersistedUserToolResultEvent', 'PersistedSystemMessageEvent']


ClientSessionEventInput: TypeAlias = Union['UserMessageEventInput', 'UserInterruptEventInput', 'UserToolConfirmationEventInput', 'UserCustomToolResultEventInput', 'UserDefineOutcomeEventInput', 'UserToolResultEventInput', 'SystemMessageEventInput']


class CloudEnvironmentConfig(TypedDict, total=False):
    networking: Required['NetworkPolicy']
    packages: Required['Packages']
    type: Required[Literal['cloud']]


class CloudEnvironmentConfigInput(TypedDict, total=False):
    networking: 'NetworkPolicyInput'
    packages: 'PackagesInput'
    type: Required[Literal['cloud']]


CoreSessionEventType: TypeAlias = Literal['user.message', 'user.interrupt', 'user.tool_confirmation', 'user.custom_tool_result', 'user.tool_result', 'user.define_outcome', 'system.message', 'agent.message', 'agent.thinking', 'agent.custom_tool_use', 'agent.tool_use', 'agent.tool_result', 'agent.mcp_tool_use', 'agent.mcp_tool_result', 'session.status_idle', 'session.status_running', 'session.status_terminated', 'session.status_rescheduled', 'session.usage', 'session.error', 'session.updated', 'session.deleted', 'session.thread_created', 'session.thread_status_idle', 'session.thread_status_running', 'session.thread_status_rescheduled', 'session.thread_status_terminated', 'agent.thread_message_received', 'agent.thread_message_sent', 'agent.thread_context_compacted', 'span.outcome_evaluation_start', 'span.outcome_evaluation_ongoing', 'span.outcome_evaluation_end', 'span.model_request_start', 'span.model_request_end']


Cursor: TypeAlias = Union[str, None]


class CustomSkillReferenceInput(TypedDict, total=False):
    skill_id: Required[str]
    type: Required[Literal['custom']]
    version: str


class CustomTool(TypedDict, total=False):
    description: Required[str]
    input_schema: Required[Dict[str, Any]]
    name: Required[str]
    type: Required[Literal['custom']]


class DefineOutcomeInitialEvent(TypedDict, total=False):
    description: Required[str]
    max_iterations: int
    rubric: Required['OutcomeRubric']
    type: Required[Literal['user.define_outcome']]


class Deployment(TypedDict, total=False):
    agent: Required['AgentReference']
    archived_at: Required['NullableTimestamp']
    budget: Required['NullableSessionBudget']
    created_at: Required[str]
    description: Required[str]
    environment_id: Required[str]
    id: Required[str]
    initial_events: Required[List['DeploymentInitialEvent']]
    metadata: Required['DeploymentMetadata']
    name: Required[str]
    paused_reason: Required[Union['DeploymentPausedReason', None]]
    resources: Required[List['DeploymentResource']]
    schedule: Required[Union['DeploymentSchedule', None]]
    status: Required[Literal['active', 'paused']]
    type: Required[Literal['deployment']]
    updated_at: Required[str]
    vault_ids: Required[List[str]]


DeploymentAgentInput: TypeAlias = Union[str, 'AgentReference']


class DeploymentCreateRequest(TypedDict, total=False):
    agent: Required['DeploymentAgentInput']
    budget: 'NullableSessionBudget'
    description: Union[str, None]
    environment_id: Required[str]
    initial_events: Required[List['DeploymentInitialEvent']]
    metadata: 'DeploymentMetadata'
    name: Required[str]
    resources: List['DeploymentResourceInput']
    schedule: Union['DeploymentScheduleInput', None]
    vault_ids: List[str]


DeploymentInitialEvent: TypeAlias = Union['UserMessageEventInput', 'UserDefineOutcomeEventInput', 'SystemMessageEventInput']


class DeploymentList(TypedDict, total=False):
    data: Required[List['Deployment']]
    next_page: Required['Cursor']


DeploymentMetadata: TypeAlias = Dict[str, str]


class DeploymentPausedReason(TypedDict, total=False):
    error: 'DeploymentPausedReasonError'
    type: Required[Literal['manual', 'error']]


DeploymentResource: TypeAlias = Union['DeploymentResourceVariant1', 'DeploymentResourceVariant2', 'GitRepositoryDeploymentResource']


DeploymentResourceInput: TypeAlias = Union['FileSessionResourceInput', 'MemoryStoreSessionResourceInput', 'GitRepositorySessionResourceInput']


class DeploymentRun(TypedDict, total=False):
    agent: Required['AgentReference']
    created_at: Required[str]
    deployment_id: Required[str]
    error: Required[Union['DeploymentRunError', None]]
    id: Required[str]
    session_id: Required[Union[str, None]]
    trigger_context: Required['DeploymentRunTriggerContext']
    type: Required[Literal['deployment_run']]


class DeploymentRunError(TypedDict, total=False):
    message: Required[str]
    type: Required[Literal['environment_archived_error', 'agent_archived_error', 'environment_not_found_error', 'vault_not_found_error', 'vault_archived_error', 'file_not_found_error', 'memory_store_archived_error', 'skill_not_found_error', 'session_resource_not_found_error', 'workspace_archived_error', 'organization_disabled_error', 'session_rate_limited_error', 'session_creation_rejected_error', 'unknown_error', 'self_hosted_resources_unsupported_error', 'mcp_egress_blocked_error']]


class DeploymentRunList(TypedDict, total=False):
    data: Required[List['DeploymentRun']]
    next_page: Required['Cursor']


DeploymentRunTriggerContext: TypeAlias = Union['DeploymentRunTriggerContextVariant1', 'DeploymentRunTriggerContextVariant2']


class DeploymentSchedule(TypedDict, total=False):
    expression: Required[str]
    timezone: Required[str]
    type: Required[Literal['cron']]
    last_run_at: Required['NullableTimestamp']
    upcoming_runs_at: Required[List[str]]


class DeploymentScheduleInput(TypedDict, total=False):
    expression: Required[str]
    timezone: Required[str]
    type: Required[Literal['cron']]


class DeploymentUpdateRequest(TypedDict, total=False):
    agent: 'DeploymentAgentInput'
    budget: 'NullableSessionBudget'
    description: Union[str, None]
    environment_id: str
    initial_events: List['DeploymentInitialEvent']
    metadata: Union[Dict[str, Union[str, None]], None]
    name: str
    resources: Union[List['DeploymentResourceInput'], None]
    schedule: Union['DeploymentScheduleInput', None]
    vault_ids: Union[List[str], None]


class DocumentBlockInput(TypedDict, total=False):
    context: str
    source: Required['DocumentSourceInput']
    title: str
    type: Required[Literal['document']]


DocumentSourceInput: TypeAlias = Union['Base64DocumentSourceInput', 'TextDocumentSourceInput', 'URLDocumentSourceInput', 'FileDocumentSourceInput']


class Environment(TypedDict, total=False):
    archived_at: Required['NullableTimestamp']
    config: Required['EnvironmentConfig']
    created_at: Required[str]
    description: Required[str]
    id: Required[str]
    metadata: Required['Metadata']
    name: Required[str]
    scope: Literal['organization', 'account']
    type: Required[Literal['environment']]
    updated_at: Required[str]


EnvironmentConfig: TypeAlias = Union['CloudEnvironmentConfig', 'SelfHostedEnvironmentConfig']


EnvironmentConfigInput: TypeAlias = Union['CloudEnvironmentConfigInput', 'SelfHostedEnvironmentConfig']


class EnvironmentCreateRequest(TypedDict, total=False):
    config: 'EnvironmentConfigInput'
    description: str
    metadata: 'Metadata'
    name: Required[str]
    scope: Literal['organization', 'account']


EnvironmentCredentialNetworking: TypeAlias = Union['EnvironmentCredentialNetworkingVariant1', 'EnvironmentCredentialNetworkingVariant2']


class EnvironmentDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['environment_deleted']]


class EnvironmentList(TypedDict, total=False):
    data: Required[List['Environment']]
    next_page: Required['Cursor']


class EnvironmentUpdateRequest(TypedDict, total=False):
    config: 'EnvironmentConfigInput'
    description: str
    metadata: 'MetadataPatch'
    name: str
    scope: Literal['organization', 'account']


class EnvironmentVariableCredentialCreate(TypedDict, total=False):
    injection_location: 'EnvironmentVariableCredentialCreateInjectionLocation'
    networking: Required['EnvironmentCredentialNetworking']
    secret_name: Required[str]
    secret_value: Required[str]
    type: Required[Literal['environment_variable']]


class EnvironmentVariableCredentialUpdate(TypedDict, total=False):
    injection_location: 'EnvironmentVariableCredentialUpdateInjectionLocation'
    networking: 'EnvironmentCredentialNetworking'
    secret_value: str
    type: Required[Literal['environment_variable']]


class EnvironmentWork(TypedDict, total=False):
    acknowledged_at: Required['NullableTimestamp']
    created_at: Required[str]
    data: Required['EnvironmentWorkData']
    environment_id: Required[str]
    id: Required[str]
    latest_heartbeat_at: Required['NullableTimestamp']
    metadata: Required[Dict[str, str]]
    secret: Required[Union[str, None]]
    started_at: Required['NullableTimestamp']
    state: Required['EnvironmentWorkState']
    stop_requested_at: Required['NullableTimestamp']
    stopped_at: Required['NullableTimestamp']
    type: Required[Literal['work']]


class EnvironmentWorkData(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['session']]


class EnvironmentWorkHeartbeat(TypedDict, total=False):
    last_heartbeat: Required[str]
    lease_extended: Required[bool]
    state: Required['EnvironmentWorkState']
    ttl_seconds: Required[int]
    type: Required[Literal['work_heartbeat']]


class EnvironmentWorkList(TypedDict, total=False):
    data: Required[List['EnvironmentWork']]
    next_page: Required['Cursor']


class EnvironmentWorkQueueStats(TypedDict, total=False):
    depth: Required[int]
    oldest_queued_at: Required['NullableTimestamp']
    pending: Required[int]
    type: Required[Literal['work_queue_stats']]
    workers_polling: Required[int]


EnvironmentWorkState: TypeAlias = Literal['queued', 'starting', 'active', 'stopping', 'stopped']


class EnvironmentWorkStopRequest(TypedDict, total=False):
    force: bool


class EnvironmentWorkUpdateRequest(TypedDict, total=False):
    metadata: Required[Dict[str, Union[str, None]]]


class ErrorResponse(TypedDict, total=False):
    error: Required['ErrorResponseError']
    request_id: Required[str]
    type: Required[Literal['error']]


EvaluatedPermission: TypeAlias = Literal['allow', 'ask', 'deny']


class EventDelta(TypedDict, total=False):
    delta: Required['EventDeltaContent']
    event_id: Required[str]
    type: Required[Literal['event_delta']]


class EventDeltaContent(TypedDict, total=False):
    content: Required['TextBlockInput']
    index: Required[int]
    type: Required[Literal['content_delta']]


class EventStart(TypedDict, total=False):
    event: Required['EventStartPreview']
    type: Required[Literal['event_start']]


class EventStartPreview(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['agent.message', 'agent.thinking']]


EventStreamFrame: TypeAlias = Union['SessionEvent', 'EventStart', 'EventDelta']


class File(TypedDict, total=False):
    created_at: Required[str]
    downloadable: Required[bool]
    filename: Required[str]
    id: Required[str]
    mime_type: Required[str]
    scope: Required[Union['FileScope', None]]
    size_bytes: Required[int]
    type: Required[Literal['file']]


class FileDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['file_deleted']]


class FileDocumentSourceInput(TypedDict, total=False):
    file_id: Required[str]
    type: Required[Literal['file']]


class FileImageSourceInput(TypedDict, total=False):
    file_id: Required[str]
    type: Required[Literal['file']]


class FileList(TypedDict, total=False):
    data: Required[List['File']]
    first_id: Required[Union[str, None]]
    has_more: Required[bool]
    last_id: Required[Union[str, None]]


class FileRubric(TypedDict, total=False):
    file_id: Required[str]
    type: Required[Literal['file']]


class FileScope(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['session']]


class FileSessionResource(TypedDict, total=False):
    created_at: Required[str]
    file_id: Required[str]
    id: Required[str]
    mount_path: Required[str]
    type: Required[Literal['file']]
    updated_at: Required[str]


class FileSessionResourceInput(TypedDict, total=False):
    file_id: Required[str]
    mount_path: str
    type: Required[Literal['file']]


class FileUploadRequest(TypedDict, total=False):
    file: Required[Upload]


class GitRepositoryBranchCheckout(TypedDict, total=False):
    name: Required[str]
    type: Required[Literal['branch']]


GitRepositoryCheckout: TypeAlias = Union['GitRepositoryBranchCheckout', 'GitRepositoryCommitCheckout']


class GitRepositoryCommitCheckout(TypedDict, total=False):
    sha: Required[str]
    type: Required[Literal['commit']]


class GitRepositoryDeploymentResource(TypedDict, total=False):
    checkout: Required[Union['GitRepositoryCheckout', None]]
    mount_path: Required[Union[str, None]]
    type: Required[Literal['git_repository']]
    url: Required[str]


class GitRepositorySessionResource(TypedDict, total=False):
    checkout: Required[Union['GitRepositoryCheckout', None]]
    created_at: Required[str]
    id: Required[str]
    mount_path: Required[str]
    resolved_commit: Required[str]
    type: Required[Literal['git_repository']]
    updated_at: Required[str]
    url: Required[str]


class GitRepositorySessionResourceInput(TypedDict, total=False):
    checkout: 'GitRepositoryCheckout'
    mount_path: str
    type: Required[Literal['git_repository']]
    url: Required[str]


class ImageBlockInput(TypedDict, total=False):
    source: Required['ImageSourceInput']
    type: Required[Literal['image']]


ImageSourceInput: TypeAlias = Union['Base64ImageSourceInput', 'URLImageSourceInput', 'FileImageSourceInput']


InitialEvent: TypeAlias = Union['UserMessageInitialEvent', 'DefineOutcomeInitialEvent']


LegacyMultiagent: TypeAlias = Dict[str, Any]


LegacySkillReference: TypeAlias = Any


class LimitedNetwork(TypedDict, total=False):
    allow_mcp_servers: Required[bool]
    allow_package_managers: Required[bool]
    allowed_hosts: Required[List[str]]
    type: Required[Literal['limited']]


class LimitedNetworkInput(TypedDict, total=False):
    allow_mcp_servers: bool
    allow_package_managers: bool
    allowed_hosts: List[str]
    type: Required[Literal['limited']]


class MCPOAuthCredentialAuth(TypedDict, total=False):
    expires_at: Required[Union[str, None]]
    mcp_server_url: Required[str]
    refresh: Required[Union['OAuthRefreshResponse', None]]
    type: Required[Literal['mcp_oauth']]


class MCPOAuthCredentialCreate(TypedDict, total=False):
    access_token: Required[str]
    expires_at: Union[str, None]
    mcp_server_url: Required[str]
    refresh: Union['OAuthRefreshCreate', None]
    type: Required[Literal['mcp_oauth']]


class MCPOAuthCredentialUpdate(TypedDict, total=False):
    access_token: Union[str, None]
    expires_at: Union[str, None]
    refresh: Union['OAuthRefreshUpdate', None]
    type: Required[Literal['mcp_oauth']]


class MCPServer(TypedDict, total=False):
    name: Required[str]
    type: Required[Literal['url']]
    url: Required[str]


class MCPToolset(TypedDict, total=False):
    configs: List['ToolConfig']
    default_config: 'ToolDefaultConfig'
    mcp_server_name: Required[str]
    type: Required[Literal['mcp_toolset']]


class ManagedAgentThreadAgent(TypedDict, total=False):
    description: Required[str]
    id: Required[str]
    mcp_servers: Required[List['MCPServer']]
    model: Required['Model']
    name: Required[str]
    skills: Required[List['SkillReferenceResponse']]
    system: Required[str]
    tools: Required[List['AgentTool']]
    type: Required[Literal['agent']]
    version: Required[int]


class Memory(TypedDict, total=False):
    content: Required[Union[str, None]]
    content_sha256: Required['MemoryContentSHA256']
    content_size_bytes: Required[int]
    created_at: Required[str]
    id: Required[str]
    memory_store_id: Required[str]
    memory_version_id: Required[str]
    path: Required['MemoryPath']
    type: Required[Literal['memory']]
    updated_at: Required[str]


class MemoryAPIActor(TypedDict, total=False):
    api_key_id: Required[str]
    type: Required[Literal['api_actor']]


MemoryActor: TypeAlias = Union['MemoryAPIActor', 'MemorySessionActor', 'MemoryUserActor']


MemoryContentSHA256: TypeAlias = str


class MemoryCreateRequest(TypedDict, total=False):
    content: Required[str]
    path: Required['MemoryPath']


class MemoryDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['memory_deleted']]


class MemoryList(TypedDict, total=False):
    data: Required[List['MemoryListItem']]
    has_more: Required[bool]
    next_page: Required['Cursor']


MemoryListItem: TypeAlias = Union['Memory', 'MemoryPrefix']


MemoryMetadata: TypeAlias = Dict[str, str]


MemoryMetadataPatch: TypeAlias = Dict[str, Union[str, None]]


MemoryPath: TypeAlias = str


class MemoryPrecondition(TypedDict, total=False):
    content_sha256: Required['MemoryContentSHA256']
    type: Required[Literal['content_sha256']]


class MemoryPrefix(TypedDict, total=False):
    path: Required[str]
    type: Required[Literal['memory_prefix']]


class MemorySessionActor(TypedDict, total=False):
    session_id: Required[str]
    type: Required[Literal['session_actor']]


class MemoryStore(TypedDict, total=False):
    archived_at: Required['NullableTimestamp']
    created_at: Required[str]
    description: Required[str]
    id: Required[str]
    metadata: Required['MemoryMetadata']
    name: Required[str]
    type: Required[Literal['memory_store']]
    updated_at: Required[str]


class MemoryStoreCreateRequest(TypedDict, total=False):
    description: str
    metadata: 'MemoryMetadata'
    name: Required[str]


class MemoryStoreDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['memory_store_deleted']]


class MemoryStoreList(TypedDict, total=False):
    data: Required[List['MemoryStore']]
    has_more: Required[bool]
    next_page: Required['Cursor']


class MemoryStoreSessionResource(TypedDict, total=False):
    access: Required[Literal['read_write', 'read_only']]
    description: Required[str]
    instructions: Required[Union[str, None]]
    memory_store_id: Required[str]
    mount_path: Required[str]
    name: Required[str]
    type: Required[Literal['memory_store']]


class MemoryStoreSessionResourceInput(TypedDict, total=False):
    access: Literal['read_write', 'read_only']
    instructions: str
    memory_store_id: Required[str]
    type: Required[Literal['memory_store']]


class MemoryStoreUpdateRequest(TypedDict, total=False):
    description: str
    metadata: 'MemoryMetadataPatch'
    name: str


class MemoryUpdateRequest(TypedDict, total=False):
    content: str
    path: 'MemoryPath'
    precondition: 'MemoryPrecondition'


class MemoryUserActor(TypedDict, total=False):
    type: Required[Literal['user_actor']]
    user_id: Required[str]


class MemoryVersion(TypedDict, total=False):
    content: Required[Union[str, None]]
    content_sha256: Required[Union['MemoryContentSHA256', None]]
    content_size_bytes: Required[Union[int, None]]
    created_at: Required[str]
    created_by: Required['MemoryActor']
    id: Required[str]
    memory_id: Required[str]
    memory_store_id: Required[str]
    operation: Required[Literal['created', 'modified', 'deleted']]
    path: Required[Union['MemoryPath', None]]
    redacted_at: Required['NullableTimestamp']
    redacted_by: Required[Union['MemoryActor', None]]
    type: Required[Literal['memory_version']]


class MemoryVersionList(TypedDict, total=False):
    data: Required[List['MemoryVersion']]
    has_more: Required[bool]
    next_page: Required['Cursor']


MessageContentInput: TypeAlias = Union['TextBlockInput', 'ImageBlockInput', 'DocumentBlockInput']


Metadata: TypeAlias = Dict[str, str]


MetadataPatch: TypeAlias = Dict[str, Union[str, None]]


class Model(TypedDict, total=False):
    effort: Required['ModelEffort']
    id: Required[str]
    speed: Required[Literal['standard', 'fast']]


class ModelEffort(TypedDict, total=False):
    type: Required['ModelEffortLevel']


ModelEffortLevel: TypeAlias = Literal['low', 'medium', 'high', 'xhigh', 'max']


ModelInput: TypeAlias = Union[str, 'ModelInputVariant2']


class MonetaryAmount(TypedDict, total=False):
    amount: Required[str]
    currency: Required[Literal['USD']]


Multiagent: TypeAlias = Union['ResolvedMultiagent', 'LegacyMultiagent', None]


class MultiagentAdvisor(TypedDict, total=False):
    model: Required[str]
    type: Required[Literal['advisor']]


class MultiagentAgentReferenceInput(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['agent']]
    version: int


class MultiagentInput(TypedDict, total=False):
    agents: Required[List['MultiagentRosterEntryInput']]
    type: Required[Literal['coordinator']]


MultiagentRosterEntryInput: TypeAlias = Union[str, 'MultiagentAgentReferenceInput', 'MultiagentSelfReferenceInput', 'MultiagentAdvisor']


class MultiagentSelfReferenceInput(TypedDict, total=False):
    type: Required[Literal['self']]


NetworkPolicy: TypeAlias = Union['UnrestrictedNetwork', 'LimitedNetwork']


NetworkPolicyInput: TypeAlias = Union['UnrestrictedNetwork', 'LimitedNetworkInput']


NullableSessionBudget: TypeAlias = Union['SessionBudgetLimit', None]


NullableTimestamp: TypeAlias = Union[str, None]


class OAuthRefreshCreate(TypedDict, total=False):
    client_id: Required[str]
    refresh_token: Required[str]
    resource: Union[str, None]
    scope: Union[str, None]
    token_endpoint: Required[str]
    token_endpoint_auth: Required['OAuthTokenEndpointAuthCreate']


class OAuthRefreshResponse(TypedDict, total=False):
    client_id: Required[str]
    resource: Required[Union[str, None]]
    scope: Required[Union[str, None]]
    token_endpoint: Required[str]
    token_endpoint_auth: Required['OAuthTokenEndpointAuthResponse']


class OAuthRefreshUpdate(TypedDict, total=False):
    refresh_token: Union[str, None]
    scope: Union[str, None]
    token_endpoint_auth: 'OAuthTokenEndpointAuthUpdate'


OAuthTokenEndpointAuthCreate: TypeAlias = Union['OAuthTokenEndpointAuthNoneCreate', 'OAuthTokenEndpointAuthSecretCreate']


class OAuthTokenEndpointAuthNoneCreate(TypedDict, total=False):
    type: Required[Literal['none']]


class OAuthTokenEndpointAuthResponse(TypedDict, total=False):
    type: Required[Literal['none', 'client_secret_basic', 'client_secret_post']]


class OAuthTokenEndpointAuthSecretCreate(TypedDict, total=False):
    client_secret: Required[str]
    type: Required[Literal['client_secret_basic', 'client_secret_post']]


class OAuthTokenEndpointAuthUpdate(TypedDict, total=False):
    client_secret: Union[str, None]
    type: Required[Literal['client_secret_basic', 'client_secret_post']]


class OutcomeEvaluation(TypedDict, total=False):
    completed_at: Required['NullableTimestamp']
    description: Required[str]
    explanation: Required[Union[str, None]]
    iteration: Required[int]
    outcome_id: Required[str]
    result: Required[str]
    type: Required[Literal['outcome_evaluation']]


OutcomeRubric: TypeAlias = Union['TextRubric', 'FileRubric']


class Packages(TypedDict, total=False):
    apt: Required[List[str]]
    cargo: Required[List[str]]
    gem: Required[List[str]]
    go: Required[List[str]]
    npm: Required[List[str]]
    pip: Required[List[str]]
    type: Required[Literal['packages']]


class PackagesInput(TypedDict, total=False):
    apt: List[str]
    cargo: List[str]
    gem: List[str]
    go: List[str]
    npm: List[str]
    pip: List[str]
    type: Literal['packages']


class PermissionPolicy(TypedDict, total=False):
    type: Required[Literal['always_allow', 'always_ask']]


class PersistedSessionEventBase(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required['CoreSessionEventType']


class PersistedSystemMessageEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['system.message']]
    content: Required[List['TextBlockInput']]


class PersistedUserCustomToolResultEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['user.custom_tool_result']]
    content: List['ResultContentInput']
    custom_tool_use_id: Required[str]
    is_error: bool
    session_thread_id: str


class PersistedUserDefineOutcomeEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['user.define_outcome']]
    description: Required[str]
    max_iterations: Required[int]
    outcome_id: Required[str]
    rubric: Required['OutcomeRubric']


class PersistedUserInterruptEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['user.interrupt']]
    session_thread_id: str


class PersistedUserMessageEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['user.message']]
    content: Required[List['MessageContentInput']]


class PersistedUserToolConfirmationEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['user.tool_confirmation']]
    deny_message: str
    result: Required[Literal['allow', 'deny']]
    session_thread_id: str
    tool_use_id: Required[str]


class PersistedUserToolResultEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['user.tool_result']]
    content: List['ResultContentInput']
    is_error: bool
    session_thread_id: str
    tool_use_id: Required[str]


class ResolvedAgentReference(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['agent']]
    version: Required[int]


class ResolvedMultiagent(TypedDict, total=False):
    agents: Required[List[Union['ResolvedAgentReference', 'MultiagentAdvisor']]]
    type: Required[Literal['coordinator']]


class ResolvedSkillReference(TypedDict, total=False):
    skill_id: Required[str]
    type: Required[Literal['custom']]
    version: Required[str]


ResultContentInput: TypeAlias = Union['TextBlockInput', 'ImageBlockInput', 'DocumentBlockInput', 'SearchResultBlock']


class SearchResultBlock(TypedDict, total=False):
    citations: Required['SearchResultBlockCitations']
    content: Required[List['TextBlockInput']]
    source: Required[str]
    title: Required[str]
    type: Required[Literal['search_result']]


class SelfHostedEnvironmentConfig(TypedDict, total=False):
    type: Required[Literal['self_hosted']]


class SendSessionEventsRequest(TypedDict, total=False):
    events: Required[List['ClientSessionEventInput']]


class Session(TypedDict, total=False):
    agent: Required['AgentSnapshot']
    archived_at: Required['NullableTimestamp']
    budget: Required['NullableSessionBudget']
    created_at: Required[str]
    deployment_id: Required[None]
    environment_id: Required[str]
    id: Required[str]
    metadata: Required['Metadata']
    outcome_evaluations: Required[List['OutcomeEvaluation']]
    resources: Required[List['SessionResource']]
    stats: Required['SessionStats']
    status: Required['SessionStatus']
    title: Required[str]
    type: Required[Literal['session']]
    updated_at: Required[str]
    usage: Required['SessionUsage']
    vault_ids: Required[List[str]]


SessionAgentInput: TypeAlias = Union[str, 'AgentReference', 'AgentWithOverrides']


class SessionAgentUpdate(TypedDict, total=False):
    mcp_servers: Union[List['MCPServer'], None]
    tools: Union[List['AgentTool'], None]


class SessionBudgetLimit(TypedDict, total=False):
    max_list_cost: Required['MonetaryAmount']
    type: Required[Literal['limit']]


class SessionBudgetReached(TypedDict, total=False):
    type: Required[Literal['budget_reached']]


class SessionCreateRequest(TypedDict, total=False):
    agent: Required['SessionAgentInput']
    budget: 'NullableSessionBudget'
    environment_id: Required[str]
    initial_events: List['InitialEvent']
    metadata: 'Metadata'
    resources: List['SessionResourceInput']
    title: str
    vault_ids: List[str]


class SessionDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['session_deleted']]


class SessionDeletedEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.deleted']]


class SessionEndTurn(TypedDict, total=False):
    type: Required[Literal['end_turn']]


class SessionErrorEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.error']]
    error: Required['SessionExecutionError']


SessionEvent: TypeAlias = Union['PersistedUserMessageEvent', 'PersistedUserInterruptEvent', 'PersistedUserToolConfirmationEvent', 'PersistedUserCustomToolResultEvent', 'PersistedUserToolResultEvent', 'PersistedUserDefineOutcomeEvent', 'PersistedSystemMessageEvent', 'AgentMessageEvent', 'AgentThinkingEvent', 'AgentCustomToolUseEvent', 'AgentToolUseEvent', 'AgentToolResultEvent', 'AgentMCPToolUseEvent', 'AgentMCPToolResultEvent', 'SessionStatusIdleEvent', 'SessionStatusRunningEvent', 'SessionStatusTerminatedEvent', 'SessionStatusRescheduledEvent', 'SessionUsageEvent', 'SessionErrorEvent', 'SessionUpdatedEvent', 'SessionDeletedEvent', 'SessionThreadCreatedEvent', 'SessionThreadStatusIdleEvent', 'SessionThreadStatusRunningEvent', 'SessionThreadStatusRescheduledEvent', 'SessionThreadStatusTerminatedEvent', 'AgentThreadMessageReceivedEvent', 'AgentThreadMessageSentEvent', 'AgentThreadContextCompactedEvent', 'SpanOutcomeEvaluationStartEvent', 'SpanOutcomeEvaluationOngoingEvent', 'SpanOutcomeEvaluationEndEvent', 'SpanModelRequestStartEvent', 'SpanModelRequestEndEvent']


class SessionEventBatch(TypedDict, total=False):
    data: Required[List['ClientPersistedSessionEvent']]


class SessionEventList(TypedDict, total=False):
    data: Required[List['SessionEvent']]
    next_page: Required['Cursor']


class SessionExecutionError(TypedDict, total=False):
    credential_id: str
    mcp_server_name: str
    message: Required[str]
    retry_status: 'SessionExecutionErrorRetryStatus'
    type: Required[Literal['unknown_error', 'model_overloaded_error', 'model_rate_limited_error', 'model_request_failed_error', 'mcp_connection_failed_error', 'mcp_authentication_failed_error', 'billing_error', 'credential_host_unreachable_error', 'api_error']]
    vault_id: str


class SessionList(TypedDict, total=False):
    data: Required[List['Session']]
    next_page: Required['Cursor']
    prev_page: Required['Cursor']


SessionMultiagent: TypeAlias = Union['SessionResolvedMultiagent', 'ResolvedMultiagent', 'LegacyMultiagent', None]


class SessionRequiresAction(TypedDict, total=False):
    event_ids: Required[List[str]]
    type: Required[Literal['requires_action']]


class SessionResolvedMultiagent(TypedDict, total=False):
    agents: Required[List['SessionThreadAgent']]
    type: Required[Literal['coordinator']]


SessionResource: TypeAlias = Union['FileSessionResource', 'MemoryStoreSessionResource', 'GitRepositorySessionResource']


class SessionResourceDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['session_resource_deleted']]


SessionResourceInput: TypeAlias = Union['FileSessionResourceInput', 'MemoryStoreSessionResourceInput', 'GitRepositorySessionResourceInput']


class SessionResourceList(TypedDict, total=False):
    data: Required[List['SessionResource']]
    has_more: Required[bool]
    next_page: Required['Cursor']


class SessionRetriesExhausted(TypedDict, total=False):
    type: Required[Literal['retries_exhausted']]


class SessionStats(TypedDict, total=False):
    active_seconds: Required[float]
    duration_seconds: Required[float]


SessionStatus: TypeAlias = Literal['idle', 'running', 'rescheduling', 'terminated']


class SessionStatusIdleEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.status_idle']]
    stop_reason: Required['SessionStopReason']


class SessionStatusRescheduledEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.status_rescheduled']]


class SessionStatusRunningEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.status_running']]


class SessionStatusTerminatedEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.status_terminated']]


SessionStopReason: TypeAlias = Union['SessionEndTurn', 'SessionRequiresAction', 'SessionRetriesExhausted', 'SessionBudgetReached']


class SessionThread(TypedDict, total=False):
    agent: Required['SessionThreadAgent']
    archived_at: Required['NullableTimestamp']
    created_at: Required[str]
    id: Required[str]
    parent_thread_id: Required[Union[str, None]]
    session_id: Required[str]
    stats: Required['SessionThreadStats']
    status: Required['SessionStatus']
    type: Required[Literal['session_thread']]
    updated_at: Required[str]
    usage: Required['SessionUsage']


SessionThreadAgent: TypeAlias = Union['ManagedAgentThreadAgent', 'MultiagentAdvisor']


class SessionThreadCreatedEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.thread_created']]
    agent_name: Required[str]
    session_thread_id: Required[str]


class SessionThreadList(TypedDict, total=False):
    data: Required[List['SessionThread']]
    next_page: Required['Cursor']


class SessionThreadStats(TypedDict, total=False):
    active_seconds: Required[float]
    duration_seconds: Required[float]
    startup_seconds: Required[float]


class SessionThreadStatusIdleEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.thread_status_idle']]
    agent_name: Required[str]
    session_thread_id: Required[str]
    stop_reason: Required['SessionStopReason']


class SessionThreadStatusRescheduledEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.thread_status_rescheduled']]
    agent_name: Required[str]
    session_thread_id: Required[str]


class SessionThreadStatusRunningEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.thread_status_running']]
    agent_name: Required[str]
    session_thread_id: Required[str]


class SessionThreadStatusTerminatedEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.thread_status_terminated']]
    agent_name: Required[str]
    session_thread_id: Required[str]


class SessionUpdateRequest(TypedDict, total=False):
    agent: 'SessionAgentUpdate'
    budget: 'NullableSessionBudget'
    metadata: 'MetadataPatch'
    title: str
    vault_ids: List[str]


class SessionUpdatedEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.updated']]
    agent: 'AgentSnapshot'
    budget: 'NullableSessionBudget'
    metadata: 'Metadata'
    title: str


class SessionUsage(TypedDict, total=False):
    active_seconds: Required[float]
    cache_creation: Required['SessionUsageCacheCreation']
    cache_read_input_tokens: Required[int]
    input_tokens: Required[int]
    list_cost: Required[Union['MonetaryAmount', None]]
    output_tokens: Required[int]
    server_tool_use: Required['SessionUsageServerToolUse']


class SessionUsageEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['session.usage']]
    budget: Required['NullableSessionBudget']
    usage: Required['SessionUsageSnapshot']


class SessionUsageSnapshot(TypedDict, total=False):
    active_seconds: Required[float]
    cache_creation: Required['SessionUsageSnapshotCacheCreation']
    cache_read_input_tokens: Required[int]
    input_tokens: Required[int]
    list_cost: Required['MonetaryAmount']
    output_tokens: Required[int]
    server_tool_use: Required['SessionUsageSnapshotServerToolUse']


class SkillDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['skill_deleted']]


class SkillList(TypedDict, total=False):
    data: Required[List['SkillResource']]
    has_more: Required[bool]
    next_page: Required[Union[str, None]]


SkillReferenceInput: TypeAlias = Union['CustomSkillReferenceInput', 'AnthropicSkillReferenceInput']


SkillReferenceResponse: TypeAlias = Union['ResolvedSkillReference', 'LegacySkillReference']


class SkillResource(TypedDict, total=False):
    created_at: Required[str]
    display_title: Required[str]
    id: Required[str]
    latest_version: Required[Union[str, None]]
    source: Required[Literal['custom']]
    type: Required[Literal['skill']]
    updated_at: Required[str]


class SkillUploadRequest(TypedDict, total=False):
    display_title: str
    files: Required[List[Upload]]


class SkillVersion(TypedDict, total=False):
    created_at: Required[str]
    description: Required[str]
    directory: Required[str]
    id: Required[str]
    name: Required[str]
    skill_id: Required[str]
    type: Required[Literal['skill_version']]
    version: Required[str]


class SkillVersionDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['skill_version_deleted']]


class SkillVersionList(TypedDict, total=False):
    data: Required[List['SkillVersion']]
    has_more: Required[bool]
    next_page: Required[Union[str, None]]


class SkillVersionUploadRequest(TypedDict, total=False):
    files: Required[List[Upload]]


class SpanModelRequestEndEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['span.model_request_end']]
    is_error: Required[bool]
    model_request_start_id: Required[str]
    model_usage: Required['SpanModelUsage']


class SpanModelRequestStartEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['span.model_request_start']]


class SpanModelUsage(TypedDict, total=False):
    cache_creation_input_tokens: Required[int]
    cache_read_input_tokens: Required[int]
    input_tokens: Required[int]
    output_tokens: Required[int]
    speed: Required[Literal['standard', 'fast', None]]


class SpanOutcomeEvaluationEndEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['span.outcome_evaluation_end']]
    explanation: Required[str]
    iteration: Required[int]
    outcome_evaluation_start_id: Required[str]
    outcome_id: Required[str]
    result: Required[Literal['satisfied', 'needs_revision', 'max_iterations_reached', 'failed', 'interrupted']]
    usage: Required['SpanModelUsage']


class SpanOutcomeEvaluationOngoingEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['span.outcome_evaluation_ongoing']]
    iteration: Required[int]
    outcome_id: Required[str]


class SpanOutcomeEvaluationStartEvent(TypedDict, total=False):
    id: Required[str]
    processed_at: Required['NullableTimestamp']
    type: Required[Literal['span.outcome_evaluation_start']]
    iteration: Required[int]
    outcome_id: Required[str]


class StaticBearerCredentialAuth(TypedDict, total=False):
    mcp_server_url: Required[str]
    type: Required[Literal['static_bearer']]


class StaticBearerCredentialCreate(TypedDict, total=False):
    mcp_server_url: Required[str]
    token: Required[str]
    type: Required[Literal['static_bearer']]


class StaticBearerCredentialUpdate(TypedDict, total=False):
    token: Union[str, None]
    type: Required[Literal['static_bearer']]


class SystemMessageEventInput(TypedDict, total=False):
    content: Required[List['TextBlockInput']]
    type: Required[Literal['system.message']]


class TextBlockInput(TypedDict, total=False):
    text: Required[str]
    type: Required[Literal['text']]


class TextDocumentSourceInput(TypedDict, total=False):
    data: Required[str]
    media_type: Required[Literal['text/plain']]
    type: Required[Literal['text']]


class TextRubric(TypedDict, total=False):
    content: Required[str]
    type: Required[Literal['text']]


class ToolConfig(TypedDict, total=False):
    enabled: bool
    name: Required[str]
    permission_policy: 'PermissionPolicy'


class ToolDefaultConfig(TypedDict, total=False):
    enabled: bool
    permission_policy: 'PermissionPolicy'


class URLDocumentSourceInput(TypedDict, total=False):
    type: Required[Literal['url']]
    url: Required[str]


class URLImageSourceInput(TypedDict, total=False):
    type: Required[Literal['url']]
    url: Required[str]


class UnrestrictedNetwork(TypedDict, total=False):
    type: Required[Literal['unrestricted']]


class UserCustomToolResultEventInput(TypedDict, total=False):
    content: List['ResultContentInput']
    custom_tool_use_id: Required[str]
    is_error: bool
    session_thread_id: str
    type: Required[Literal['user.custom_tool_result']]


class UserDefineOutcomeEventInput(TypedDict, total=False):
    description: Required[str]
    max_iterations: int
    rubric: Required['OutcomeRubric']
    type: Required[Literal['user.define_outcome']]


class UserInterruptEventInput(TypedDict, total=False):
    session_thread_id: str
    type: Required[Literal['user.interrupt']]


class UserMessageEventInput(TypedDict, total=False):
    content: Required[List['MessageContentInput']]
    type: Required[Literal['user.message']]


class UserMessageInitialEvent(TypedDict, total=False):
    content: Required[List['MessageContentInput']]
    type: Required[Literal['user.message']]


class UserToolConfirmationEventInput(TypedDict, total=False):
    deny_message: str
    result: Required[Literal['allow', 'deny']]
    session_thread_id: str
    tool_use_id: Required[str]
    type: Required[Literal['user.tool_confirmation']]


class UserToolResultEventInput(TypedDict, total=False):
    content: List['ResultContentInput']
    is_error: bool
    session_thread_id: str
    tool_use_id: Required[str]
    type: Required[Literal['user.tool_result']]


class Vault(TypedDict, total=False):
    archived_at: Required['NullableTimestamp']
    created_at: Required[str]
    display_name: Required[str]
    id: Required[str]
    metadata: Required['VaultMetadata']
    type: Required[Literal['vault']]
    updated_at: Required[str]


class VaultCreateRequest(TypedDict, total=False):
    display_name: Required[str]
    metadata: 'VaultMetadata'


class VaultCredential(TypedDict, total=False):
    archived_at: Required['NullableTimestamp']
    auth: Required['VaultCredentialAuth']
    created_at: Required[str]
    display_name: Required[Union[str, None]]
    id: Required[str]
    metadata: Required['VaultMetadata']
    type: Required[Literal['vault_credential']]
    updated_at: Required[str]
    vault_id: Required[str]


VaultCredentialAuth: TypeAlias = Union['StaticBearerCredentialAuth', 'MCPOAuthCredentialAuth']


VaultCredentialCreateAuth: TypeAlias = Union['StaticBearerCredentialCreate', 'MCPOAuthCredentialCreate', 'EnvironmentVariableCredentialCreate']


class VaultCredentialCreateRequest(TypedDict, total=False):
    auth: Required['VaultCredentialCreateAuth']
    display_name: Union[str, None]
    metadata: 'VaultMetadata'


class VaultCredentialDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['vault_credential_deleted']]


class VaultCredentialList(TypedDict, total=False):
    data: Required[List['VaultCredential']]
    next_page: Required['Cursor']


class VaultCredentialMCPProbe(TypedDict, total=False):
    http_response: Required[Union['VaultCredentialValidationHTTPResponse', None]]
    method: Required[str]


class VaultCredentialRefreshValidation(TypedDict, total=False):
    http_response: Required[Union['VaultCredentialValidationHTTPResponse', None]]
    status: Required[Literal['succeeded', 'failed', 'connect_error', 'no_refresh_token']]


VaultCredentialUpdateAuth: TypeAlias = Union['StaticBearerCredentialUpdate', 'MCPOAuthCredentialUpdate', 'EnvironmentVariableCredentialUpdate']


class VaultCredentialUpdateRequest(TypedDict, total=False):
    auth: 'VaultCredentialUpdateAuth'
    display_name: Union[str, None]
    metadata: Union['VaultMetadataPatch', None]


class VaultCredentialValidation(TypedDict, total=False):
    credential_id: Required[str]
    has_refresh_token: Required[bool]
    mcp_probe: Required[Union['VaultCredentialMCPProbe', None]]
    refresh: Required[Union['VaultCredentialRefreshValidation', None]]
    status: Required[Literal['valid', 'invalid', 'unknown']]
    type: Required[Literal['vault_credential_validation']]
    validated_at: Required[str]
    vault_id: Required[str]


class VaultCredentialValidationHTTPResponse(TypedDict, total=False):
    body: Required[str]
    body_truncated: Required[bool]
    content_type: Required[str]
    status_code: Required[int]


class VaultDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['vault_deleted']]


class VaultList(TypedDict, total=False):
    data: Required[List['Vault']]
    next_page: Required['Cursor']


VaultMetadata: TypeAlias = Dict[str, str]


VaultMetadataPatch: TypeAlias = Dict[str, Union[str, None]]


class VaultUpdateRequest(TypedDict, total=False):
    display_name: Union[str, None]
    metadata: Union['VaultMetadataPatch', None]


class Webhook(TypedDict, total=False):
    created_at: Required[str]
    disabled_reason: Required[Union[str, None]]
    event_types: Required[List['WebhookEventType']]
    id: Required[str]
    status: Required[Literal['enabled', 'disabled']]
    type: Required[Literal['webhook']]
    updated_at: Required[str]
    url: Required[str]


class WebhookCreateRequest(TypedDict, total=False):
    event_types: Required[List['WebhookEventType']]
    url: Required[str]


class WebhookDeleted(TypedDict, total=False):
    id: Required[str]
    type: Required[Literal['webhook_deleted']]


WebhookEventType: TypeAlias = Literal['session.status_scheduled', 'session.status_run_started', 'session.status_idled', 'session.status_rescheduled', 'session.status_terminated', 'session.budget_reached', 'session.thread_created', 'session.thread_idled', 'session.thread_terminated', 'session.outcome_evaluation_ended', 'session.updated', 'session.archived', 'session.deleted', 'deployment_run.succeeded', 'deployment_run.failed']


class WebhookList(TypedDict, total=False):
    data: Required[List['Webhook']]
    next_page: Required['Cursor']


class WebhookUpdateRequest(TypedDict, total=False):
    event_types: List['WebhookEventType']
    status: Literal['enabled', 'disabled']
    url: str


class WebhookWithSigningSecret(TypedDict, total=False):
    created_at: Required[str]
    disabled_reason: Required[Union[str, None]]
    event_types: Required[List['WebhookEventType']]
    id: Required[str]
    signing_secret: Required[str]
    status: Required[Literal['enabled', 'disabled']]
    type: Required[Literal['webhook']]
    updated_at: Required[str]
    url: Required[str]


AcknowledgeEnvironmentWorkEnvironmentIdParameter: TypeAlias = str


AcknowledgeEnvironmentWorkWorkIdParameter: TypeAlias = str


AddSessionResourceSessionIdParameter: TypeAlias = str


ArchiveAgentAgentIdParameter: TypeAlias = str


ArchiveDeploymentDeploymentIdParameter: TypeAlias = str


ArchiveEnvironmentEnvironmentIdParameter: TypeAlias = str


ArchiveMemoryStoreStoreIdParameter: TypeAlias = str


ArchiveSessionSessionIdParameter: TypeAlias = str


ArchiveSessionThreadSessionIdParameter: TypeAlias = str


ArchiveSessionThreadThreadIdParameter: TypeAlias = str


ArchiveVaultVaultIdParameter: TypeAlias = str


ArchiveVaultCredentialVaultIdParameter: TypeAlias = str


ArchiveVaultCredentialCredentialIdParameter: TypeAlias = str


CreateMemoryStoreIdParameter: TypeAlias = str


CreateMemoryViewParameter: TypeAlias = Literal['basic', 'full']


CreateSkillVersionSkillIdParameter: TypeAlias = str


CreateVaultCredentialVaultIdParameter: TypeAlias = str


DeleteEnvironmentEnvironmentIdParameter: TypeAlias = str


DeleteFileFileIdParameter: TypeAlias = str


DeleteMemoryStoreIdParameter: TypeAlias = str


DeleteMemoryMemoryIdParameter: TypeAlias = str


DeleteMemoryExpectedContentSha256Parameter: TypeAlias = str


DeleteMemoryStoreStoreIdParameter: TypeAlias = str


DeleteSessionSessionIdParameter: TypeAlias = str


DeleteSessionResourceSessionIdParameter: TypeAlias = str


DeleteSessionResourceResourceIdParameter: TypeAlias = str


DeleteSkillSkillIdParameter: TypeAlias = str


DeleteSkillVersionSkillIdParameter: TypeAlias = str


DeleteSkillVersionVersionParameter: TypeAlias = str


DeleteVaultVaultIdParameter: TypeAlias = str


DeleteVaultCredentialVaultIdParameter: TypeAlias = str


DeleteVaultCredentialCredentialIdParameter: TypeAlias = str


DeleteWebhookWebhookIdParameter: TypeAlias = str


DownloadFileFileIdParameter: TypeAlias = str


DownloadSkillVersionSkillIdParameter: TypeAlias = str


DownloadSkillVersionVersionParameter: TypeAlias = str


GetAgentAgentIdParameter: TypeAlias = str


GetDeploymentDeploymentIdParameter: TypeAlias = str


GetDeploymentRunDeploymentRunIdParameter: TypeAlias = str


GetEnvironmentEnvironmentIdParameter: TypeAlias = str


GetEnvironmentWorkEnvironmentIdParameter: TypeAlias = str


GetEnvironmentWorkWorkIdParameter: TypeAlias = str


GetEnvironmentWorkStatsEnvironmentIdParameter: TypeAlias = str


GetFileMetadataFileIdParameter: TypeAlias = str


GetMemoryStoreIdParameter: TypeAlias = str


GetMemoryMemoryIdParameter: TypeAlias = str


GetMemoryViewParameter: TypeAlias = Literal['basic', 'full']


GetMemoryStoreStoreIdParameter: TypeAlias = str


GetMemoryVersionStoreIdParameter: TypeAlias = str


GetMemoryVersionVersionIdParameter: TypeAlias = str


GetMemoryVersionViewParameter: TypeAlias = Literal['basic', 'full']


GetSessionSessionIdParameter: TypeAlias = str


GetSessionResourceSessionIdParameter: TypeAlias = str


GetSessionResourceResourceIdParameter: TypeAlias = str


GetSessionThreadSessionIdParameter: TypeAlias = str


GetSessionThreadThreadIdParameter: TypeAlias = str


GetSkillSkillIdParameter: TypeAlias = str


GetSkillVersionSkillIdParameter: TypeAlias = str


GetSkillVersionVersionParameter: TypeAlias = str


GetVaultVaultIdParameter: TypeAlias = str


GetVaultCredentialVaultIdParameter: TypeAlias = str


GetVaultCredentialCredentialIdParameter: TypeAlias = str


GetWebhookWebhookIdParameter: TypeAlias = str


HeartbeatEnvironmentWorkEnvironmentIdParameter: TypeAlias = str


HeartbeatEnvironmentWorkWorkIdParameter: TypeAlias = str


HeartbeatEnvironmentWorkExpectedLastHeartbeatParameter: TypeAlias = str


HeartbeatEnvironmentWorkDesiredTtlSecondsParameter: TypeAlias = int


ListAgentVersionsAgentIdParameter: TypeAlias = str


ListAgentVersionsLimitParameter: TypeAlias = int


ListAgentVersionsPageParameter: TypeAlias = str


ListAgentsLimitParameter: TypeAlias = int


ListAgentsPageParameter: TypeAlias = str


ListAgentsIncludeArchivedParameter: TypeAlias = bool


ListAgentsCreatedAtGteParameter: TypeAlias = str


ListAgentsCreatedAtLteParameter: TypeAlias = str


ListDeploymentRunsLimitParameter: TypeAlias = int


ListDeploymentRunsPageParameter: TypeAlias = str


ListDeploymentRunsCreatedAtGtParameter: TypeAlias = str


ListDeploymentRunsCreatedAtGteParameter: TypeAlias = str


ListDeploymentRunsCreatedAtLtParameter: TypeAlias = str


ListDeploymentRunsCreatedAtLteParameter: TypeAlias = str


ListDeploymentRunsDeploymentIdParameter: TypeAlias = str


ListDeploymentRunsHasErrorParameter: TypeAlias = bool


ListDeploymentRunsTriggerTypeParameter: TypeAlias = Literal['schedule', 'manual']


ListDeploymentsLimitParameter: TypeAlias = int


ListDeploymentsPageParameter: TypeAlias = str


ListDeploymentsAgentIdParameter: TypeAlias = str


ListDeploymentsCreatedAtGteParameter: TypeAlias = str


ListDeploymentsCreatedAtLteParameter: TypeAlias = str


ListDeploymentsIncludeArchivedParameter: TypeAlias = bool


ListDeploymentsStatusParameter: TypeAlias = Literal['active', 'paused']


ListEnvironmentWorkEnvironmentIdParameter: TypeAlias = str


ListEnvironmentWorkLimitParameter: TypeAlias = int


ListEnvironmentWorkPageParameter: TypeAlias = str


ListEnvironmentsLimitParameter: TypeAlias = int


ListEnvironmentsPageParameter: TypeAlias = str


ListEnvironmentsIncludeArchivedParameter: TypeAlias = bool


ListFilesLimitParameter: TypeAlias = int


ListFilesAfterIdParameter: TypeAlias = str


ListFilesBeforeIdParameter: TypeAlias = str


ListFilesScopeIdParameter: TypeAlias = str


ListMemoriesStoreIdParameter: TypeAlias = str


ListMemoriesLimitParameter: TypeAlias = int


ListMemoriesPageParameter: TypeAlias = str


ListMemoriesViewParameter: TypeAlias = Literal['basic', 'full']


ListMemoriesPathPrefixParameter: TypeAlias = str


ListMemoriesDepthParameter: TypeAlias = Literal[0, 1]


ListMemoryStoresLimitParameter: TypeAlias = int


ListMemoryStoresPageParameter: TypeAlias = str


ListMemoryStoresIncludeArchivedParameter: TypeAlias = bool


ListMemoryStoresCreatedAtGteParameter: TypeAlias = str


ListMemoryStoresCreatedAtLteParameter: TypeAlias = str


ListMemoryVersionsStoreIdParameter: TypeAlias = str


ListMemoryVersionsLimitParameter: TypeAlias = int


ListMemoryVersionsPageParameter: TypeAlias = str


ListMemoryVersionsViewParameter: TypeAlias = Literal['basic', 'full']


ListMemoryVersionsApiKeyIdParameter: TypeAlias = str


ListMemoryVersionsSessionIdParameter: TypeAlias = str


ListMemoryVersionsMemoryIdParameter: TypeAlias = str


ListMemoryVersionsOperationParameter: TypeAlias = Literal['created', 'modified', 'deleted']


ListMemoryVersionsCreatedAtGteParameter: TypeAlias = str


ListMemoryVersionsCreatedAtLteParameter: TypeAlias = str


ListSessionEventsSessionIdParameter: TypeAlias = str


ListSessionEventsLimitParameter: TypeAlias = int


ListSessionEventsOrderParameter: TypeAlias = Literal['asc', 'desc']


ListSessionEventsPageParameter: TypeAlias = str


ListSessionEventsTypesParameter: TypeAlias = List['CoreSessionEventType']


ListSessionEventsCreatedAtGtParameter: TypeAlias = str


ListSessionEventsCreatedAtGteParameter: TypeAlias = str


ListSessionEventsCreatedAtLtParameter: TypeAlias = str


ListSessionEventsCreatedAtLteParameter: TypeAlias = str


ListSessionResourcesSessionIdParameter: TypeAlias = str


ListSessionResourcesLimitParameter: TypeAlias = int


ListSessionResourcesPageParameter: TypeAlias = str


ListSessionThreadEventsSessionIdParameter: TypeAlias = str


ListSessionThreadEventsThreadIdParameter: TypeAlias = str


ListSessionThreadEventsLimitParameter: TypeAlias = int


ListSessionThreadEventsPageParameter: TypeAlias = str


ListSessionThreadsSessionIdParameter: TypeAlias = str


ListSessionThreadsLimitParameter: TypeAlias = int


ListSessionThreadsPageParameter: TypeAlias = str


ListSessionsLimitParameter: TypeAlias = int


ListSessionsPageParameter: TypeAlias = str


ListSessionsOrderParameter: TypeAlias = Literal['asc', 'desc']


ListSessionsAgentIdParameter: TypeAlias = str


ListSessionsAgentVersionParameter: TypeAlias = int


ListSessionsStatusesParameter: TypeAlias = List['SessionStatus']


ListSessionsIncludeArchivedParameter: TypeAlias = bool


ListSessionsCreatedAtGtParameter: TypeAlias = str


ListSessionsCreatedAtGteParameter: TypeAlias = str


ListSessionsCreatedAtLtParameter: TypeAlias = str


ListSessionsCreatedAtLteParameter: TypeAlias = str


ListSessionsDeploymentIdParameter: TypeAlias = str


ListSessionsMemoryStoreIdParameter: TypeAlias = str


ListSkillVersionsSkillIdParameter: TypeAlias = str


ListSkillVersionsLimitParameter: TypeAlias = int


ListSkillVersionsPageParameter: TypeAlias = str


ListSkillsLimitParameter: TypeAlias = int


ListSkillsPageParameter: TypeAlias = str


ListSkillsSourceParameter: TypeAlias = Literal['custom', 'anthropic']


ListVaultCredentialsVaultIdParameter: TypeAlias = str


ListVaultCredentialsLimitParameter: TypeAlias = int


ListVaultCredentialsPageParameter: TypeAlias = str


ListVaultCredentialsIncludeArchivedParameter: TypeAlias = bool


ListVaultsLimitParameter: TypeAlias = int


ListVaultsPageParameter: TypeAlias = str


ListVaultsIncludeArchivedParameter: TypeAlias = bool


ListWebhooksLimitParameter: TypeAlias = int


ListWebhooksPageParameter: TypeAlias = str


PauseDeploymentDeploymentIdParameter: TypeAlias = str


PollEnvironmentWorkEnvironmentIdParameter: TypeAlias = str


PollEnvironmentWorkBlockMsParameter: TypeAlias = int


PollEnvironmentWorkReclaimOlderThanMsParameter: TypeAlias = int


PollEnvironmentWorkWorkerIdParameter: TypeAlias = str


PollEnvironmentWorkResponse: TypeAlias = Union['EnvironmentWork', Dict[str, Any]]


RedactMemoryVersionStoreIdParameter: TypeAlias = str


RedactMemoryVersionVersionIdParameter: TypeAlias = str


RegenerateWebhookSigningSecretWebhookIdParameter: TypeAlias = str


RunDeploymentDeploymentIdParameter: TypeAlias = str


SendSessionEventsSessionIdParameter: TypeAlias = str


StopEnvironmentWorkEnvironmentIdParameter: TypeAlias = str


StopEnvironmentWorkWorkIdParameter: TypeAlias = str


StreamSessionEventsSessionIdParameter: TypeAlias = str


StreamSessionEventsEventDeltasParameter: TypeAlias = List[Literal['agent.message', 'agent.thinking']]


StreamSessionThreadEventsSessionIdParameter: TypeAlias = str


StreamSessionThreadEventsThreadIdParameter: TypeAlias = str


StreamSessionThreadEventsEventDeltasParameter: TypeAlias = List[Literal['agent.message', 'agent.thinking']]


UnpauseDeploymentDeploymentIdParameter: TypeAlias = str


UpdateAgentAgentIdParameter: TypeAlias = str


UpdateDeploymentDeploymentIdParameter: TypeAlias = str


UpdateEnvironmentEnvironmentIdParameter: TypeAlias = str


UpdateEnvironmentWorkEnvironmentIdParameter: TypeAlias = str


UpdateEnvironmentWorkWorkIdParameter: TypeAlias = str


UpdateMemoryStoreIdParameter: TypeAlias = str


UpdateMemoryMemoryIdParameter: TypeAlias = str


UpdateMemoryViewParameter: TypeAlias = Literal['basic', 'full']


UpdateMemoryStoreStoreIdParameter: TypeAlias = str


UpdateSessionSessionIdParameter: TypeAlias = str


UpdateVaultVaultIdParameter: TypeAlias = str


UpdateVaultCredentialVaultIdParameter: TypeAlias = str


UpdateVaultCredentialCredentialIdParameter: TypeAlias = str


UpdateWebhookWebhookIdParameter: TypeAlias = str


ValidateVaultCredentialMCPOAuthVaultIdParameter: TypeAlias = str


ValidateVaultCredentialMCPOAuthCredentialIdParameter: TypeAlias = str


class BuiltinToolsetConfigsItem(TypedDict, total=False):
    enabled: bool
    name: Required[Literal['bash', 'read', 'write', 'edit', 'glob', 'grep', 'web_fetch', 'web_search']]
    permission_policy: 'PermissionPolicy'


class DeploymentPausedReasonError(TypedDict, total=False):
    type: Required[str]


class DeploymentResourceVariant1(TypedDict, total=False):
    file_id: Required[str]
    mount_path: Required[Union[str, None]]
    type: Required[Literal['file']]


class DeploymentResourceVariant2(TypedDict, total=False):
    access: Required[Literal['read_write', 'read_only', None]]
    instructions: Required[Union[str, None]]
    memory_store_id: Required[str]
    type: Required[Literal['memory_store']]


class DeploymentRunTriggerContextVariant1(TypedDict, total=False):
    type: Required[Literal['manual']]


class DeploymentRunTriggerContextVariant2(TypedDict, total=False):
    scheduled_at: Required[str]
    type: Required[Literal['schedule']]


class EnvironmentCredentialNetworkingVariant1(TypedDict, total=False):
    type: Required[Literal['unrestricted']]


class EnvironmentCredentialNetworkingVariant2(TypedDict, total=False):
    allowed_hosts: Required[List[str]]
    type: Required[Literal['limited']]


class EnvironmentVariableCredentialCreateInjectionLocation(TypedDict, total=False):
    body: bool
    header: bool


class EnvironmentVariableCredentialUpdateInjectionLocation(TypedDict, total=False):
    body: bool
    header: bool


class ErrorResponseError(TypedDict, total=False):
    message: Required[str]
    type: Required[Literal['invalid_request_error', 'authentication_error', 'permission_error', 'not_found_error', 'conflict_error', 'precondition_failed_error', 'memory_precondition_failed_error', 'request_too_large', 'api_error']]


class ModelInputVariant2(TypedDict, total=False):
    effort: Union['ModelEffortLevel', 'ModelEffort']
    id: Required[str]
    speed: Literal['standard', 'fast']


class SearchResultBlockCitations(TypedDict, total=False):
    enabled: Required[bool]


class SessionExecutionErrorRetryStatus(TypedDict, total=False):
    type: Required[Literal['retrying', 'exhausted', 'terminal']]


class SessionUsageCacheCreation(TypedDict, total=False):
    ephemeral_1h_input_tokens: Required[int]
    ephemeral_5m_input_tokens: Required[int]


class SessionUsageServerToolUse(TypedDict, total=False):
    web_fetch_requests: Required[int]
    web_search_requests: Required[int]


class SessionUsageSnapshotCacheCreation(TypedDict, total=False):
    ephemeral_1h_input_tokens: Required[int]
    ephemeral_5m_input_tokens: Required[int]


class SessionUsageSnapshotServerToolUse(TypedDict, total=False):
    web_fetch_requests: Required[int]
    web_search_requests: Required[int]


__all__ = ['AcknowledgeEnvironmentWorkEnvironmentIdParameter',
 'AcknowledgeEnvironmentWorkWorkIdParameter',
 'AddSessionResourceSessionIdParameter',
 'Agent',
 'AgentCreateRequest',
 'AgentCustomToolUseEvent',
 'AgentList',
 'AgentMCPToolResultEvent',
 'AgentMCPToolUseEvent',
 'AgentMessageEvent',
 'AgentReference',
 'AgentSnapshot',
 'AgentThinkingEvent',
 'AgentThreadContextCompactedEvent',
 'AgentThreadMessageReceivedEvent',
 'AgentThreadMessageSentEvent',
 'AgentTool',
 'AgentToolResultEvent',
 'AgentToolUseEvent',
 'AgentUpdateRequest',
 'AgentWithOverrides',
 'AnthropicSkillReferenceInput',
 'ArchiveAgentAgentIdParameter',
 'ArchiveDeploymentDeploymentIdParameter',
 'ArchiveEnvironmentEnvironmentIdParameter',
 'ArchiveMemoryStoreStoreIdParameter',
 'ArchiveSessionSessionIdParameter',
 'ArchiveSessionThreadSessionIdParameter',
 'ArchiveSessionThreadThreadIdParameter',
 'ArchiveVaultCredentialCredentialIdParameter',
 'ArchiveVaultCredentialVaultIdParameter',
 'ArchiveVaultVaultIdParameter',
 'Base64DocumentSourceInput',
 'Base64ImageSourceInput',
 'BuiltinToolset',
 'BuiltinToolsetConfigsItem',
 'ClientPersistedSessionEvent',
 'ClientSessionEventInput',
 'CloudEnvironmentConfig',
 'CloudEnvironmentConfigInput',
 'CoreSessionEventType',
 'CreateMemoryStoreIdParameter',
 'CreateMemoryViewParameter',
 'CreateSkillVersionSkillIdParameter',
 'CreateVaultCredentialVaultIdParameter',
 'Cursor',
 'CustomSkillReferenceInput',
 'CustomTool',
 'DefineOutcomeInitialEvent',
 'DeleteEnvironmentEnvironmentIdParameter',
 'DeleteFileFileIdParameter',
 'DeleteMemoryExpectedContentSha256Parameter',
 'DeleteMemoryMemoryIdParameter',
 'DeleteMemoryStoreIdParameter',
 'DeleteMemoryStoreStoreIdParameter',
 'DeleteSessionResourceResourceIdParameter',
 'DeleteSessionResourceSessionIdParameter',
 'DeleteSessionSessionIdParameter',
 'DeleteSkillSkillIdParameter',
 'DeleteSkillVersionSkillIdParameter',
 'DeleteSkillVersionVersionParameter',
 'DeleteVaultCredentialCredentialIdParameter',
 'DeleteVaultCredentialVaultIdParameter',
 'DeleteVaultVaultIdParameter',
 'DeleteWebhookWebhookIdParameter',
 'Deployment',
 'DeploymentAgentInput',
 'DeploymentCreateRequest',
 'DeploymentInitialEvent',
 'DeploymentList',
 'DeploymentMetadata',
 'DeploymentPausedReason',
 'DeploymentPausedReasonError',
 'DeploymentResource',
 'DeploymentResourceInput',
 'DeploymentResourceVariant1',
 'DeploymentResourceVariant2',
 'DeploymentRun',
 'DeploymentRunError',
 'DeploymentRunList',
 'DeploymentRunTriggerContext',
 'DeploymentRunTriggerContextVariant1',
 'DeploymentRunTriggerContextVariant2',
 'DeploymentSchedule',
 'DeploymentScheduleInput',
 'DeploymentUpdateRequest',
 'DocumentBlockInput',
 'DocumentSourceInput',
 'DownloadFileFileIdParameter',
 'DownloadSkillVersionSkillIdParameter',
 'DownloadSkillVersionVersionParameter',
 'Environment',
 'EnvironmentConfig',
 'EnvironmentConfigInput',
 'EnvironmentCreateRequest',
 'EnvironmentCredentialNetworking',
 'EnvironmentCredentialNetworkingVariant1',
 'EnvironmentCredentialNetworkingVariant2',
 'EnvironmentDeleted',
 'EnvironmentList',
 'EnvironmentUpdateRequest',
 'EnvironmentVariableCredentialCreate',
 'EnvironmentVariableCredentialCreateInjectionLocation',
 'EnvironmentVariableCredentialUpdate',
 'EnvironmentVariableCredentialUpdateInjectionLocation',
 'EnvironmentWork',
 'EnvironmentWorkData',
 'EnvironmentWorkHeartbeat',
 'EnvironmentWorkList',
 'EnvironmentWorkQueueStats',
 'EnvironmentWorkState',
 'EnvironmentWorkStopRequest',
 'EnvironmentWorkUpdateRequest',
 'ErrorResponse',
 'ErrorResponseError',
 'EvaluatedPermission',
 'EventDelta',
 'EventDeltaContent',
 'EventStart',
 'EventStartPreview',
 'EventStreamFrame',
 'File',
 'FileDeleted',
 'FileDocumentSourceInput',
 'FileImageSourceInput',
 'FileList',
 'FileRubric',
 'FileScope',
 'FileSessionResource',
 'FileSessionResourceInput',
 'FileUploadRequest',
 'GetAgentAgentIdParameter',
 'GetDeploymentDeploymentIdParameter',
 'GetDeploymentRunDeploymentRunIdParameter',
 'GetEnvironmentEnvironmentIdParameter',
 'GetEnvironmentWorkEnvironmentIdParameter',
 'GetEnvironmentWorkStatsEnvironmentIdParameter',
 'GetEnvironmentWorkWorkIdParameter',
 'GetFileMetadataFileIdParameter',
 'GetMemoryMemoryIdParameter',
 'GetMemoryStoreIdParameter',
 'GetMemoryStoreStoreIdParameter',
 'GetMemoryVersionStoreIdParameter',
 'GetMemoryVersionVersionIdParameter',
 'GetMemoryVersionViewParameter',
 'GetMemoryViewParameter',
 'GetSessionResourceResourceIdParameter',
 'GetSessionResourceSessionIdParameter',
 'GetSessionSessionIdParameter',
 'GetSessionThreadSessionIdParameter',
 'GetSessionThreadThreadIdParameter',
 'GetSkillSkillIdParameter',
 'GetSkillVersionSkillIdParameter',
 'GetSkillVersionVersionParameter',
 'GetVaultCredentialCredentialIdParameter',
 'GetVaultCredentialVaultIdParameter',
 'GetVaultVaultIdParameter',
 'GetWebhookWebhookIdParameter',
 'GitRepositoryBranchCheckout',
 'GitRepositoryCheckout',
 'GitRepositoryCommitCheckout',
 'GitRepositoryDeploymentResource',
 'GitRepositorySessionResource',
 'GitRepositorySessionResourceInput',
 'HeartbeatEnvironmentWorkDesiredTtlSecondsParameter',
 'HeartbeatEnvironmentWorkEnvironmentIdParameter',
 'HeartbeatEnvironmentWorkExpectedLastHeartbeatParameter',
 'HeartbeatEnvironmentWorkWorkIdParameter',
 'ImageBlockInput',
 'ImageSourceInput',
 'InitialEvent',
 'LegacyMultiagent',
 'LegacySkillReference',
 'LimitedNetwork',
 'LimitedNetworkInput',
 'ListAgentVersionsAgentIdParameter',
 'ListAgentVersionsLimitParameter',
 'ListAgentVersionsPageParameter',
 'ListAgentsCreatedAtGteParameter',
 'ListAgentsCreatedAtLteParameter',
 'ListAgentsIncludeArchivedParameter',
 'ListAgentsLimitParameter',
 'ListAgentsPageParameter',
 'ListDeploymentRunsCreatedAtGtParameter',
 'ListDeploymentRunsCreatedAtGteParameter',
 'ListDeploymentRunsCreatedAtLtParameter',
 'ListDeploymentRunsCreatedAtLteParameter',
 'ListDeploymentRunsDeploymentIdParameter',
 'ListDeploymentRunsHasErrorParameter',
 'ListDeploymentRunsLimitParameter',
 'ListDeploymentRunsPageParameter',
 'ListDeploymentRunsTriggerTypeParameter',
 'ListDeploymentsAgentIdParameter',
 'ListDeploymentsCreatedAtGteParameter',
 'ListDeploymentsCreatedAtLteParameter',
 'ListDeploymentsIncludeArchivedParameter',
 'ListDeploymentsLimitParameter',
 'ListDeploymentsPageParameter',
 'ListDeploymentsStatusParameter',
 'ListEnvironmentWorkEnvironmentIdParameter',
 'ListEnvironmentWorkLimitParameter',
 'ListEnvironmentWorkPageParameter',
 'ListEnvironmentsIncludeArchivedParameter',
 'ListEnvironmentsLimitParameter',
 'ListEnvironmentsPageParameter',
 'ListFilesAfterIdParameter',
 'ListFilesBeforeIdParameter',
 'ListFilesLimitParameter',
 'ListFilesScopeIdParameter',
 'ListMemoriesDepthParameter',
 'ListMemoriesLimitParameter',
 'ListMemoriesPageParameter',
 'ListMemoriesPathPrefixParameter',
 'ListMemoriesStoreIdParameter',
 'ListMemoriesViewParameter',
 'ListMemoryStoresCreatedAtGteParameter',
 'ListMemoryStoresCreatedAtLteParameter',
 'ListMemoryStoresIncludeArchivedParameter',
 'ListMemoryStoresLimitParameter',
 'ListMemoryStoresPageParameter',
 'ListMemoryVersionsApiKeyIdParameter',
 'ListMemoryVersionsCreatedAtGteParameter',
 'ListMemoryVersionsCreatedAtLteParameter',
 'ListMemoryVersionsLimitParameter',
 'ListMemoryVersionsMemoryIdParameter',
 'ListMemoryVersionsOperationParameter',
 'ListMemoryVersionsPageParameter',
 'ListMemoryVersionsSessionIdParameter',
 'ListMemoryVersionsStoreIdParameter',
 'ListMemoryVersionsViewParameter',
 'ListSessionEventsCreatedAtGtParameter',
 'ListSessionEventsCreatedAtGteParameter',
 'ListSessionEventsCreatedAtLtParameter',
 'ListSessionEventsCreatedAtLteParameter',
 'ListSessionEventsLimitParameter',
 'ListSessionEventsOrderParameter',
 'ListSessionEventsPageParameter',
 'ListSessionEventsSessionIdParameter',
 'ListSessionEventsTypesParameter',
 'ListSessionResourcesLimitParameter',
 'ListSessionResourcesPageParameter',
 'ListSessionResourcesSessionIdParameter',
 'ListSessionThreadEventsLimitParameter',
 'ListSessionThreadEventsPageParameter',
 'ListSessionThreadEventsSessionIdParameter',
 'ListSessionThreadEventsThreadIdParameter',
 'ListSessionThreadsLimitParameter',
 'ListSessionThreadsPageParameter',
 'ListSessionThreadsSessionIdParameter',
 'ListSessionsAgentIdParameter',
 'ListSessionsAgentVersionParameter',
 'ListSessionsCreatedAtGtParameter',
 'ListSessionsCreatedAtGteParameter',
 'ListSessionsCreatedAtLtParameter',
 'ListSessionsCreatedAtLteParameter',
 'ListSessionsDeploymentIdParameter',
 'ListSessionsIncludeArchivedParameter',
 'ListSessionsLimitParameter',
 'ListSessionsMemoryStoreIdParameter',
 'ListSessionsOrderParameter',
 'ListSessionsPageParameter',
 'ListSessionsStatusesParameter',
 'ListSkillVersionsLimitParameter',
 'ListSkillVersionsPageParameter',
 'ListSkillVersionsSkillIdParameter',
 'ListSkillsLimitParameter',
 'ListSkillsPageParameter',
 'ListSkillsSourceParameter',
 'ListVaultCredentialsIncludeArchivedParameter',
 'ListVaultCredentialsLimitParameter',
 'ListVaultCredentialsPageParameter',
 'ListVaultCredentialsVaultIdParameter',
 'ListVaultsIncludeArchivedParameter',
 'ListVaultsLimitParameter',
 'ListVaultsPageParameter',
 'ListWebhooksLimitParameter',
 'ListWebhooksPageParameter',
 'MCPOAuthCredentialAuth',
 'MCPOAuthCredentialCreate',
 'MCPOAuthCredentialUpdate',
 'MCPServer',
 'MCPToolset',
 'ManagedAgentThreadAgent',
 'Memory',
 'MemoryAPIActor',
 'MemoryActor',
 'MemoryContentSHA256',
 'MemoryCreateRequest',
 'MemoryDeleted',
 'MemoryList',
 'MemoryListItem',
 'MemoryMetadata',
 'MemoryMetadataPatch',
 'MemoryPath',
 'MemoryPrecondition',
 'MemoryPrefix',
 'MemorySessionActor',
 'MemoryStore',
 'MemoryStoreCreateRequest',
 'MemoryStoreDeleted',
 'MemoryStoreList',
 'MemoryStoreSessionResource',
 'MemoryStoreSessionResourceInput',
 'MemoryStoreUpdateRequest',
 'MemoryUpdateRequest',
 'MemoryUserActor',
 'MemoryVersion',
 'MemoryVersionList',
 'MessageContentInput',
 'Metadata',
 'MetadataPatch',
 'Model',
 'ModelEffort',
 'ModelEffortLevel',
 'ModelInput',
 'ModelInputVariant2',
 'MonetaryAmount',
 'Multiagent',
 'MultiagentAdvisor',
 'MultiagentAgentReferenceInput',
 'MultiagentInput',
 'MultiagentRosterEntryInput',
 'MultiagentSelfReferenceInput',
 'NetworkPolicy',
 'NetworkPolicyInput',
 'NullableSessionBudget',
 'NullableTimestamp',
 'OAuthRefreshCreate',
 'OAuthRefreshResponse',
 'OAuthRefreshUpdate',
 'OAuthTokenEndpointAuthCreate',
 'OAuthTokenEndpointAuthNoneCreate',
 'OAuthTokenEndpointAuthResponse',
 'OAuthTokenEndpointAuthSecretCreate',
 'OAuthTokenEndpointAuthUpdate',
 'OutcomeEvaluation',
 'OutcomeRubric',
 'Packages',
 'PackagesInput',
 'PauseDeploymentDeploymentIdParameter',
 'PermissionPolicy',
 'PersistedSessionEventBase',
 'PersistedSystemMessageEvent',
 'PersistedUserCustomToolResultEvent',
 'PersistedUserDefineOutcomeEvent',
 'PersistedUserInterruptEvent',
 'PersistedUserMessageEvent',
 'PersistedUserToolConfirmationEvent',
 'PersistedUserToolResultEvent',
 'PollEnvironmentWorkBlockMsParameter',
 'PollEnvironmentWorkEnvironmentIdParameter',
 'PollEnvironmentWorkReclaimOlderThanMsParameter',
 'PollEnvironmentWorkResponse',
 'PollEnvironmentWorkWorkerIdParameter',
 'RedactMemoryVersionStoreIdParameter',
 'RedactMemoryVersionVersionIdParameter',
 'RegenerateWebhookSigningSecretWebhookIdParameter',
 'ResolvedAgentReference',
 'ResolvedMultiagent',
 'ResolvedSkillReference',
 'ResultContentInput',
 'RunDeploymentDeploymentIdParameter',
 'SearchResultBlock',
 'SearchResultBlockCitations',
 'SelfHostedEnvironmentConfig',
 'SendSessionEventsRequest',
 'SendSessionEventsSessionIdParameter',
 'Session',
 'SessionAgentInput',
 'SessionAgentUpdate',
 'SessionBudgetLimit',
 'SessionBudgetReached',
 'SessionCreateRequest',
 'SessionDeleted',
 'SessionDeletedEvent',
 'SessionEndTurn',
 'SessionErrorEvent',
 'SessionEvent',
 'SessionEventBatch',
 'SessionEventList',
 'SessionExecutionError',
 'SessionExecutionErrorRetryStatus',
 'SessionList',
 'SessionMultiagent',
 'SessionRequiresAction',
 'SessionResolvedMultiagent',
 'SessionResource',
 'SessionResourceDeleted',
 'SessionResourceInput',
 'SessionResourceList',
 'SessionRetriesExhausted',
 'SessionStats',
 'SessionStatus',
 'SessionStatusIdleEvent',
 'SessionStatusRescheduledEvent',
 'SessionStatusRunningEvent',
 'SessionStatusTerminatedEvent',
 'SessionStopReason',
 'SessionThread',
 'SessionThreadAgent',
 'SessionThreadCreatedEvent',
 'SessionThreadList',
 'SessionThreadStats',
 'SessionThreadStatusIdleEvent',
 'SessionThreadStatusRescheduledEvent',
 'SessionThreadStatusRunningEvent',
 'SessionThreadStatusTerminatedEvent',
 'SessionUpdateRequest',
 'SessionUpdatedEvent',
 'SessionUsage',
 'SessionUsageCacheCreation',
 'SessionUsageEvent',
 'SessionUsageServerToolUse',
 'SessionUsageSnapshot',
 'SessionUsageSnapshotCacheCreation',
 'SessionUsageSnapshotServerToolUse',
 'SkillDeleted',
 'SkillList',
 'SkillReferenceInput',
 'SkillReferenceResponse',
 'SkillResource',
 'SkillUploadRequest',
 'SkillVersion',
 'SkillVersionDeleted',
 'SkillVersionList',
 'SkillVersionUploadRequest',
 'SpanModelRequestEndEvent',
 'SpanModelRequestStartEvent',
 'SpanModelUsage',
 'SpanOutcomeEvaluationEndEvent',
 'SpanOutcomeEvaluationOngoingEvent',
 'SpanOutcomeEvaluationStartEvent',
 'StaticBearerCredentialAuth',
 'StaticBearerCredentialCreate',
 'StaticBearerCredentialUpdate',
 'StopEnvironmentWorkEnvironmentIdParameter',
 'StopEnvironmentWorkWorkIdParameter',
 'StreamSessionEventsEventDeltasParameter',
 'StreamSessionEventsSessionIdParameter',
 'StreamSessionThreadEventsEventDeltasParameter',
 'StreamSessionThreadEventsSessionIdParameter',
 'StreamSessionThreadEventsThreadIdParameter',
 'SystemMessageEventInput',
 'TextBlockInput',
 'TextDocumentSourceInput',
 'TextRubric',
 'ToolConfig',
 'ToolDefaultConfig',
 'URLDocumentSourceInput',
 'URLImageSourceInput',
 'UnpauseDeploymentDeploymentIdParameter',
 'UnrestrictedNetwork',
 'UpdateAgentAgentIdParameter',
 'UpdateDeploymentDeploymentIdParameter',
 'UpdateEnvironmentEnvironmentIdParameter',
 'UpdateEnvironmentWorkEnvironmentIdParameter',
 'UpdateEnvironmentWorkWorkIdParameter',
 'UpdateMemoryMemoryIdParameter',
 'UpdateMemoryStoreIdParameter',
 'UpdateMemoryStoreStoreIdParameter',
 'UpdateMemoryViewParameter',
 'UpdateSessionSessionIdParameter',
 'UpdateVaultCredentialCredentialIdParameter',
 'UpdateVaultCredentialVaultIdParameter',
 'UpdateVaultVaultIdParameter',
 'UpdateWebhookWebhookIdParameter',
 'UserCustomToolResultEventInput',
 'UserDefineOutcomeEventInput',
 'UserInterruptEventInput',
 'UserMessageEventInput',
 'UserMessageInitialEvent',
 'UserToolConfirmationEventInput',
 'UserToolResultEventInput',
 'ValidateVaultCredentialMCPOAuthCredentialIdParameter',
 'ValidateVaultCredentialMCPOAuthVaultIdParameter',
 'Vault',
 'VaultCreateRequest',
 'VaultCredential',
 'VaultCredentialAuth',
 'VaultCredentialCreateAuth',
 'VaultCredentialCreateRequest',
 'VaultCredentialDeleted',
 'VaultCredentialList',
 'VaultCredentialMCPProbe',
 'VaultCredentialRefreshValidation',
 'VaultCredentialUpdateAuth',
 'VaultCredentialUpdateRequest',
 'VaultCredentialValidation',
 'VaultCredentialValidationHTTPResponse',
 'VaultDeleted',
 'VaultList',
 'VaultMetadata',
 'VaultMetadataPatch',
 'VaultUpdateRequest',
 'Webhook',
 'WebhookCreateRequest',
 'WebhookDeleted',
 'WebhookEventType',
 'WebhookList',
 'WebhookUpdateRequest',
 'WebhookWithSigningSecret']
